# Introduction {#intro}

Algebraic geometry is a fundamental and active area of research in mathematics and, loosely speaking, is concerned with studying the solutions of multivariate polynomial systems and their properties.
Solving such systems is not an easy task. Even in the univariate case, there is no known algorithm for computing the roots of polynomials with degree greater than five. 
Thus, an active area of research which spans both mathematics and computer science is the development of algorithms for solving and, more generally, working with, these polynomial systems. 
Some fundamental results in this area were presented at the International Symposium on Symbolic and Algebraic Manipulation which was held in Marseille in 1979 (now part of ISSAC). 
@buchberger1979 presented his criterion and an algorithm for computing a Groebner basis of a polynomial ideal, which is still one of the most efficient methods for solving multivariate polynomial systems. 
@lazard1979 also presented an algorithm, based on Macalay's multivariate resultants, for solving a system of homogeneous polynomial equations which has complexity singly exponential in the number of unknowns. 
@arnon1979 described an extension to Collins' algorithm for computing cylindrical decompositions, which allows one to determine the dimension of a semialgebraic set and deduce some of its topological properties. 
Since then, there have been many advances in these areas, both in extending the applications of these algorithms and making them more efficient. 
Our main focus of research in this thesis will be on the Cylindrical Algebraic Decomposition algorithm, and, more generally, on algorithms for partitioning sets into simpler pieces with well-understood properties. 

Cylindrical Algebraic Decomposition is possible due to Tarski's Theorem, a fundamental result in real algebraic geometry [@vdd1988tarski], which states that semialgebraic sets are closed under projection. 
Note that this result is not true for algebraic sets, neither real nor complex. Indeed, consider the projection of the solutions of the polynomial $xy = 1$ onto the $x$-axis. We get $\R \setminus \{ 0 \}$, which is not an algebraic set, but could be represented if we are allowed to use inequalities. Thus, we will be working over the category of semialgebraic sets: sets of points defined by Boolean combinations of polynomial equations and inequalities. 
Alfred Tarski first alluded, without proof, to his famous theorem in the abstract of @sierpinski1930. He then proved the theorem in [@tarsk1998] whose planned publication in 1939 was delayed due to the war. @seidenberg1954 published "A New Decision Method for Elementary Algebra", which applies Tarski's theorem to quantifier elimination problems over real closed fields, leading to the well-known Tarski-Seidenberg Theorem. 
@lojasiewicz1964 gives a constructive proof of the Tarski-Seidenberg theorem using successive projections onto $n-1$-dimensional space. This is the idea behind the cylindrical algebraic decomposition (CAD) algorithm. 
The notion and algorithm for computing a CAD was presented by @collins1975. 
The algorithm partitions $\R^n$ into cylindrical cells -- semialgebraic sets such that the projection of any two of them is either disjoint or coincides. 
Collins' algorithm is the first computationally tractable proof of the Tarski-Seidenberg theorem, the algorithm having complexity doubly exponential in the number of variables. 
CAD has wide ranging applications in real algebraic geometry. 
Perhaps the most famous application is the one Collins was thinking of -- quantifier elimination: given a Boolean formula where literals are polynomial equations and inequalities and some variables are bound by $\forall$ and $\exists$ quantifiers, return a Boolean formula without quantifiers representing the same set. 
A similar problem uses CAD to decide whether a formula in which all variables are quantified is true or false -- the decision problem. 
Other notable uses include computing the real roots of a multivariate polynomial system and determining the dimension of a semialgebraic set. 
CAD can also be used to deduce topological properties of semialgebraic sets, for example by computing homologies. <!-- TODO -->

The CAD algorithm is still an active and interesting area of study, with two main strands of research. Since the complexity of computing a CAD is doubly exponential in the number of variables, the algorithm can be intractable for even moderately-sized problems. It is impossible to lower this theoretical bound. Indeed @davenportHeintz1988 prove that quantifier elimination by CAD is doubly exponential. They present an example of a first-order Boolean formula with quantifiers which is linear in length while the formula obtained after quantifier elimination is doubly exponential in length. 
@brown07 later presented a simple and constructive proof of the same thing, giving an example of a formula with only one free variable and containing only linear polynomials whose quantifier-free counterpart is doubly exponential in length. 

CAD depends on a fixed coordinate ordering and this can greatly influence the number of cells produced. In the same paper, @brown07 show that the same input may produce a linear number of cells for one ordering, but a doubly exponential number of cells for another. They also present an example for which every coordinate ordering yields a doubly exponential number of cells [@brown07]. 
In some applications, we may be able to change the coordinate ordering. As such, one way to "speed up" CAD construction would be to find a coordinate ordering which yields the smallest number of cells. @hong1993 was one of the first to do this, using best first search, a heuristic search technique in AI, to find an optimal ordering. More recent developments include @delrio2022, who used complexity analysis to improve upon the current state-of-the-art heuristics, obtaining benchmark results 17 times slower than the theoretical best, while the state-of-the-art performs 25 times slower than the theoretical best. 
In addition, modern AI and machine learning techniques are being investigated as a means of finding the best coordinate ordering. For example, @huang2014 employed support vector machines and @chen2020 used artificial neural networks to identify an optimal ordering.
Both of these techniques outperformed classical heuristics, making this a promising application of AI and ML. 

However, in many cases we cannot change the coordinate ordering and, even if we could, @brown07 showed that for some inputs all coordinate orderings yield a doubly exponential number of cells. As such, making optimisations in the CAD algorithm itself has been an active area of study since Collins published his original algorithm in the 70s. Collins' algorithm works on the principal of projection and lifting. First, successive projections of input polynomials are performed, until we obtain a set of polynomials in one variable. The roots of these polynomials are isolated and then "stacks" of cells above each root and each interval in between the roots are constructed. The CAD of $n$-dimensional space is obtained by iterating this process, called the "lifting phase". 
Minimising the number of polynomials produced by the projection operation means fewer computations are needed during the lifting phase. @mccallum1998 proposed an improved projection operator, observing that some polynomials included in Collins' original projection operator can be removed. Many other projection operators, e.g., TODO!! have been proposed, each offering different properties. Another optimisation is to construct a "partial CAD", proposed by @collins1991. The idea is to use truth evaluation while constructing cells, taking quantifiers into account, so that only the cells we care about will be computed. As we do not have to ensure constant sign no every polynomial, this approach leads to savings during the lifting phase. The CAD algorithm has also been modified, often by weakening its properties, to solve specific problems. E.g., @mccallum1993 presents an algorithm, based on CAD, for deciding the consistency of a system of strict polynomial inequalities. These modifications often have much better complexity than the classical CAD, while producing sufficient decompositions to solve the problem at hand. 

A different strand of research is to compute cylindrical decompositions in which the cells have certain desirable properties. This contrasts with the optimisations previously discussed, as these CADs often contain more cells than those constructed using the classical algorithm. However, this trade-off is worthwhile because the additional conditions make the CADs more powerful. 
Indeed, @pianomovers1983 apply cylindrical algebraic decomposition to a motion planning problem in which one wants to find a path, or prove that none exists, for a rigid (possibly hinged) body to move through a space defined by a configuration of walls. This has obvious applications in robotics. In order to solve this problem, cells are required to be arranged in a particular way: the closure of every cell must be a union of cells in the decomposition. Using classical CAD, this condition cannot always be satisfied, but @pianomovers1983 prove the classical algorithm is sufficient if a linear change of coordinates is made.
These CADs are also useful if we wish to compute topological properties of semialgebraic sets. For example, @reif1979 gives an algorithm for computing the homology groups of an arbitrary real algebraic variety. As we alluded to earlier, over the reals, a formula cannot tell us much about the set it defines, so this is useful for deducing properties of semialgebraic sets, e.g., how many "holes" it has, or whether it is connected. 
Along similar lines, @arnon1984 present an algorithm to compute a CAD of the plane along with information about which cells "touch each other". They extend this result to 3-dimensional space in [@arnon1987]. In order to compute these cell adjacencies, we again need the property that the closure of every cell is a union of cells in the decomposition. @arnon1987 achieve this without making a change of coordinates. 

Another desirable property is that every cell in a cylindrical decomposition is a topologically regular cell. Loosely speaking, this means that each $k$-dimensional cell and its closure is homeomorphic to a $k$-dimensional sphere and its closure. 
This property can fail in the region of points where polynomials are not well behaved. For example, consider the Whitney umbrella, the set of points in $\R^3$ which satisfy the equation
$$
x^2 - y^2 z = 0.
$$
For almost every point $(x,y) \in \R^2$, this function is well-behaved, having only one value of $z$ at which it vanishes. However, above the origin, this function vanishes at every point. In addition, as $(x,y)$ approaches the origin, the $z$-coordinate tends to infinity. Thus, the set
$$
\{ 0 < x < 1, -1 < y < 1, x^2 - y^2 z = 0 \},
$$
which is a cylindrical cell in $\R^3$, is not topologically regular. 
@lazard10 presents an algorithm which produces such a decomposition, in the potential presence of these blow-up points, for dimension $\le 3$. This so-called "strong" cylindrical algebraic decomposition consists of only topologically regular cells and the closure of every cell is a union of some cells in the decomposition. @lazard10 takes an algebraic approach, employing techniques such as computing the saturation of a polynomial ideal, to make computations efficient and explains how the algorithm can be implemented in Maple. 
Many inputs to the CAD algorithm do not contain blow-up points. @jhd20 prove that the classical CAD algorithm will produce a strong decomposition for the given coordinate ordering and regardless of the method used to compute it. This is a very useful result as it allows us to take advantage of the nice properties of strong decompositions without doing any extra work to obtain them. 
However, sometimes blow-up points are unavoidable. For example, @bgv15 propose an algorithm for computing a triangulation of a definable monotone family which relies on a strong cylindrical decomposition of that family. Since these families depend on a fixed coordinate ordering and frequently contain blow-up points, we must be able to compute these strong decompositions in arbitrary dimension, in the potential presence of blow-ups and without having to make a change of coordinates. 

@bgv15 present a constructive proof that, given a family $V := \{V_1,\ldots,V_k\}$ of bounded definable sets in $\R^n$ such that $\dim(V_i) \le 2$ for all $1 \le i \le k$, there exists a cylindrical decomposition such that $V_1 \cup \ldots \cup V_k$ is a union of cells, each cell is monotone and the closure of every cell is a union of cells in the decomposition. A monotone cell is a stronger property than topological regularity and, by @bgv13 Theorem 1, all monotone cells are topologically regular. Their proof explains how such a decomposition can be constructed and depends on classical CAD and simple tools such as refinements by linear equations and splitting two-dimensional cells  by using a given curve interval. 
The main goal of this thesis will be to design and implement an algorithm, based on this result, for constructing such a decomposition in the semialgebraic case. 
The constructive proof works for more general definable sets and, in contrast to e.g. @collins1975 or @lazard10, is geometric in nature. As such, the properties we need to satisfy in order to complete the construction are described in detail but not the methods used to obtain them. For example, we are asked to consider critical points of the smooth 2-dimensional locus of a union of definable sets, or consider the boundary of a 2-dimensional cylindrical cell. 
We will use a combination of fundamental tools in differential geometry, e.g., partial derivatives and Jacobi determinants, well-known algorithms in algebraic geometry such as smooth stratification and quantifier elimination, and ideas from optimisation, such as Lagrange multipliers. 

A similar idea to that presented by @bgv15 is discussed by @vdd98 (Section 2.19), who introduces the concept of a Van-den-Dries regular cell.

::: {.definition}
[@vdd98, Section 2.19]
We say that a cylindrical cell $C \subset \R^n$ is Van-den-Dries regular if, for all $i \in \{1,\ldots,n\}$, if two distinct points $\mathbf{x},\mathbf{y} \in C$ are such that $x_1 = y_1, \ldots, x_{i-1} = y_{i-1}, x_{i+1}, \ldots, x_n = y_n$, but $x_i < y_i$, then for all $z_i$ such that $x_i < z_i < y_i$, $(x_1,\ldots,x_{n-1},z_i,x_{i+1},\ldots,x_n) \in C$. 
:::

All two-dimensional Van-den-Dries regular cells are topologically regular, so if $\dim(V_1,\ldots,V_k)$, the decomposition described by @vdd98 will consist of topologically regular cells. The result of @bgv15 is stronger in that the monotone decomposition is obtained for a family of sets which individually have dimension at most two. 



We will also describe an algorithm for computing a smooth stratification of a semialgebraic set. A smooth stratification is a finite partition of a set into smooth manifolds called "strata". We present an algorithm, based on the work of @gv1995 for computing a smooth stratification of a semialgebraic set such that each stratum is nicely defined, meaning that each stratum of codimension $k$ is defined by $k$ different polynomials. 
<!-- TODO why is the strat useful, give an example of notnicely defined input -->



