# Background { #sec:background }

## Semialgebraic sets and monotone cells

### Sets definable over O-minimal structures

We will be working mostly in the category *SemialgebraicSet* of semialgebraic sets and sometimes in the more general category of sets definable over an O-minimal structure.

We first define the O-minimal structures over the reals.

::: {.definition #definable-set}
A structure expanding the real numbers $\R$ is a collection $$
S := (S^n)_{n \in \N}
$$
where each $S^n$ is a set of subsets of the affine space $\R^n$ satisfying the following conditions.

1. All algebraic subsets of $\R^n$ are in $S^n$;
2. $S^n$ is a Boolean subalgebra of the powerset of $\R^n$;
3. If $A \in S^n$ and $B \in S^m$, then $A \times B \in S^{n+m}$;
4. Let $\proj \colon \R^{n+1} \to \R^n$ be the projection onto the first $n$ coordinates. If $X\in S^{n+1}$, then $\proj(X)
\in S^n$.

Elements of $S^n$ are called the definable subsets of $\R^n$ and a definable subset of $\R^n$ may also be referred to as a definable set.
If the structure $S$ satisfies properties 1-4 and the following property, it is called an O-minimal structure.

5. The elements of $S^1$ consist of the finite unions of points and open intervals of $\R$.
:::

The "O" in O-minimal stands for order, as every O-minimal structure requires the underlying set to be ordered.

::: {.definition #fr }
Let $S \subset \R^n$ be a definable subset of $\R^n$ and define the frontier of $S$
$$
\fr{S} := \cl{S} \setminus S,
$$
where $\cl{S}$ is the closure of $S$ in the Euclidean topology.
:::

::: {.definition #definable-function}
A map $f \colon A \to \R^m$, where $A \subset \R^n$, is called definable if its graph $G \subset \R^{n+m}$ is a definable set.
:::

::: {.remark}
Since definable sets are closed under projection, it can be easily deduced that $A$ is a definable set.
:::

::: {.remark}
For convenience, we will call a definable map $f \colon \R^n \to \R$ a definable function.
:::

::: {.definition #graph-def-map }
Let $X \subset \R^n$ and $Y \subset \R^m$ be definable sets (see Definition \@ref(def:definable-set)).
Let $f \colon X \to Y$ be a definable map from $X$ to $Y$. The graph of $f$ is the definable set
$$
\{ (\mathbf{x},f(\mathbf{x})) \in \R^{n+m} \mid \mathbf{x} \in X \}.
$$
Sometimes, the domain of $f$ is $\R^n$. In this case, we often use the restriction $f\vert_X$ so that only images of $f$ at points in $X$ are considered.
:::

We now define the semialgebraic sets.

::: { .definition #semialgebraic-set }
The semialgebraic subsets of $\R^n$ are the smallest class ${SA}_n$ of subsets of $\R^n$ satisfying the following properties.

1. If $f \in \R[x_1,\ldots,x_n]$, then $\{ \mathbf{x} \in \R^n \mid f(\mathbf{x}) = 0 \}$ and $\{ \mathbf{x} \in \R^n
\mid f(\mathbf{x}) > 0 \}$ are elements of ${SA}_n$;
1. If $A, B \in {SA}_n$, then $A \cup B$, $A \cap B$ and $\R^n \setminus A$ are elements of ${SA}_n$.
:::

::: {.remark}
It is easy to see that semialgebraic sets satisfy the properties of sets definable in an O-minimal structure over the
reals. Another example is the sub-Pfaffian sets (see Definition \@ref(def:sub-pfaff)).
:::

::: {.definition}
Let $X \subset \R^n$ and $Y \subset \R^m$ be definable sets. A definable map $f \colon X \to Y$ is called semialgebraic if its graph (see Definition \@ref(def:graph-def-map))
$$
\{ (\mathbf{x},f(\mathbf{x})) \in \R^{n+m} \mid \mathbf{x} \in X \}
$$
is a semialgebraic set.
:::

A semialgebraic set can be represented as a first-order Boolean formula with or without quantifiers. A first-order formula which does not contain quantifiers will be called a quantifier-free Boolean formula.

::: { .definition #qff }
A quantifier-free Boolean formula $F$ is constructed using the following rules:

1. If $f \in \R[x_1\ldots,x_n]$ then $f=0$ and $f>0$ are quantifier-free Boolean formulas;
2. if $F_1$ and $F_2$ are quantifier-free Boolean formulas, then $F_1 \land F_2$, $F_1 \lor F_2$ and $\neg F_1$ are quantifier-free Boolean formulas.
:::

::: { .definition #first-order-formula }
A first-order Boolean formula $F$ is constructed using rules 1 and 2 from Definition \@ref(def:qff) and the following
rule.

3. If $F'$ is a first-order Boolean formula and $y$ is a variable ranging over $\R$, then $\exists y\ F'$ and $\forall
y\ F'$ are first-order Boolean formulas.
:::

Semialgebraic sets are closed under taking finite unions and intersections and the difference of two semialgebraic sets is semialgebraic.
A fundamental result in semialgebraic geometry is the Tarski--Seidenberg Theorem, which asserts that semialgebraic sets are also closed under taking projection.

::: { .theorem #tarski-seinedberg }
[@tarski1951]
Let $S \subset \R^{n+1}$ and $\projop{n} \colon \R^{n+1} \to \R^n$ be the projection map onto the first $n$ coordinates. Then $\projop{n}(S) \subset \R^n$ is a semialgebraic set.
:::

One important consequence of this theorem is that quantifier elimination is possible over real numbers. In other words, a subset of $\R^n$ defined by a first-order formula with quantifiers is semialgebraic and can be represented by a quantifier-free Boolean formula.
Since the closure of a semialgebraic set may be represented by a first-order Boolean formula with quantifiers, it follows from the Tarski--Seidenberg Theorem that the closure of a semialgebraic set is a semialgebraic set.

We note the existence of an algorithm for performing quantifier elimination over real numbers. This algorithm will be used to provide theoretical complexity bounds for solving quantifier elimination problems later. For simplicity, in the formulation below polynomials have coefficients in $\mathbb{R}$, but the algorithm presented by @bpr2006 works for an arbitrary real closed field.

::: { .proposition #bpr-qe }
[@bpr2006, Algorithm 14.21]

Let $y_1 < \ldots < y_k < x_1 < \ldots < x_n$ be an ordered list of variables such that
the list $y_1,\ldots,y_k$ is partitioned into blocks $Y_{[1]}, \ldots, Y_{[w]}$, where each block $Y_{[i]}, 1 \le i \le w$ contains $k_i$ variables.
Let
$$
F := Q_1 Y_{[1]}, \ldots \ldots Q_w Y_{[w]} \> G
$$
be a first-order Boolean formula,
where each $Q_1,\ldots,Q_w$ is a quantifier $\forall$ or $\exists$ such that each $Q_i$ and $Q_{i+1}$ are different and $G$ is a quantifier-free Boolean formula containing $s$ different polynomials of maximum degree $d$ in $\R[y_1,\ldots,y_k,x_1,\ldots,x_n]$.
The formula $F$ is said to have $w$ quantifier alternations.
The number of different polynomials $s$, is not related to the number of variables $n$ or $k$ and is $\le$ to the number of atoms in $G$.

Then there is an algorithm, taking $F$ as input, which produces an equivalent quantifier-free Boolean formula $$
F' := \bigvee_{1 \le i \le I} \bigwedge_{1 \le j \le J_i} \left( \bigvee_{1 \le \ell \le L_{i,j}} f_{i,j,\ell}(x_1,\ldots,x_n) \ast_{i,j,\ell} 0 \right)
$$
where each $f_{i,j,\ell}$ is a polynomial in $\R[x_1,\ldots,x_n]$ and $\ast_{i,j,\ell} \in \{<, =, >\}$ determines its sign.

The quantifier-free Boolean formula $F'$ has the following bounds:
\begin{align*}
I &\le s^{(k_w + 1) \ldots (k_1 + 1)(n+1)}d^{\O(k_w) \ldots \O(k_1)\O(n)}, \\
J_i &\le s^{(k_w + 1) \ldots (k_1 + 1)}d^{\O(k_w) \ldots \O(k_1)}, \\
L_{i,j} &\le d^{\O(k_w) \ldots \O(k_1)}, \\
\text{Each polynomial } f_{i,j,\ell} &\text{ has maximum degree } d^{\O(k_w) \ldots \O(k_1)}.
\end{align*}

This algorithm has complexity
$$
s^{(k_w + 1) \ldots (k_1 + 1)(n+1)}d^{\O(k_w) \ldots \O(k_1)\O(n)}.
$$
:::

In many quantifier elimination problems, there is only a small number of quantifier alternations and this algorithm gives a favourable complexity bound (better than, e.g., using CAD). For example, the formula for computing the closure of a semialgebraic set contains only two quantifier alternations, and this algorithm gives a complexity bound singly exponential in the number of variables (see Lemma \@ref(lem:frontier)).

Another useful property of semialgebraic sets is that they admit a basic representation, as stated below.

::: {.proposition}
Every semialgebraic subset of $\R^n$ is the (not necessarily disjoint) union of finitely many semialgebraic subsets of the kind
$$
\{ \mathbf{x} \in \R^n \mid f_1(\mathbf{x}) = 0, \cdots f_s(\mathbf{x}) = 0, g_1(\mathbf{x}) > 0, \cdots, g_k(\mathbf{x}) > 0 \}
$$
where $s,k \in \N$ and $f_1,\ldots,f_s,g_1,\ldots,g_k \in \R[x_1,\ldots,x_n]$.
:::

::: {.proof}
This follows from the fact that the class of finite unions of this kind satisfy properties listed in Definition \@ref(def:semialgebraic-set).
:::

::: {.definition #pfaff-chain }
[@gv04, Definition 2.1]

A Pfaffian chain of order $r \ge 0$ and degree $\alpha \ge 1$ in an open domain $G \subset \R^n$ is a sequence of analytic functions
$$
f_1, \ldots , f_r
$$
in $G$ satisfying the differential equations
$$
{df}_j(\mathbf{x}) = \sum^n_{i=1} g_{ij}(\mathbf{x}, f_1(\mathbf{x}), \ldots, f_j(\mathbf{x})) dx_i
$$
for $1 \le j \le r$, where $g_{ij}(x_1,\ldots,x_n),y_1,\ldots,y_j$ are polynomials of degree not greater than $\alpha$.
:::

::: {.definition #pfaff-function }
[@gv04, Definition 2.1]

A function $f(\mathbf{x}) = P(\mathbf{x},f_1(\mathbf{x}),\ldots,f_r(\mathbf{x}))$, where $P(\mathbf{x}, f_1(\mathbf{x}), \ldots, f_r(\mathbf{x}))$ is a polynomial of degree not greater than $\beta \ge 1$ is called a Pfaffian function of order $r$ and degree $(\alpha, \beta)$. Note that $f$ is only defined in the domain $G$, where all functions $f_1,\ldots,f_r$ are analytic, even if $f$ itself can be extended as an analytic function in a larger domain.
:::

Examples of Pfaffian functions include the exponential, logarithmic, reciprocal and trigonometric functions, as well as the polynomials.

::: {.definition}
[@gv04, Definition 2.7]

A set $X \subset \R^n$ is called semi-Pfaffian in an open domain
$G \subset \R^n$ if it consists of points in $G$ satisfying a Boolean combination $F$ of some atomic equations and inequalities $f = 0$, $g > 0$, where $f, g$ are Pfaffian functions having a common Pfaffian chain defined in $G$.

The set $X$ is called restricted in $G$ if $\cl{X}$ is contained in $G$.

The set $X$ is called basic if the Boolean combination $F$ is a conjunction.
:::

::: {.definition #sub-pfaff}
[@gv04, Definition 2.8]

A set $X \subset \R^n$ is called sub-Pfaffian in an open domain $G \subset \R^n$ if
$$
X := \projop{n}(Y),
$$
where $Y \subset \R^m$ is a semi-Pfaffian set and $\R^n$ is a subspace of $\R^m$.
:::

::: {.definition}
[@gv04, Definition 2.9]

Let ${\cal I}^k := [-1,1]^k$ be the closed cube in an open domain $G \subset \R^k$.
The set $X \subset {\cal I}^n$ is called restricted sub-Pfaffian if $X := \projop{n}(Y)$, where $Y \subset {\cal I}^{n+m}$ is a restricted semi-Pfaffian set.
:::

The restricted sub-Pfaffian sets form a Boolean subalgebra. Restricted sub-Pfaffian sets are clearly closed under taking finite unions and intersections. The property that the complement of a restricted sub-Pfaffian set is restricted sub-Pfaffian is a particular case of Gabrielov's compliment theorem [@gabrielov1996]. The restriction to the closed cube ensures that the restricted sub-Pfaffian sets are definable in an O-minimal structure. Furthermore, @gv01 present an algorithm for constructing a cylindrical decomposition compatible with a restricted sub-Pfaffian set. Note that these properties and results do not apply to (restricted) semi-Pfaffian sets. Since polynomials are a type of Pfaffian function, semialgebraic sets are a particular case of sub-Pfaffian sets and, due to the Tarski--Seidenberg Theorem, semialgebraic sets satisfy the compliment theorem.

::: {.definition #pfaff-format}
[@gv04, Definition 2.11]

Consider a semi-Pfaffian set
$$
X := \bigcup_{1 \le i \le M} \{ \mathbf{x} \in \R^s \mid f_{i,1} = 0, \ldots, f_{i,I_i} = 0, g_{i,1} > 0, \ldots, g_{i,J_i} > 0 \} \subset G
$$
where $f_{ij}$ and $g_{ij}$ are Pfaffian functions of order $r$ and degree $(\alpha, \beta)$ defined in an open domain
$G$.
The format of $X$ is a tuple
$$
(r, N, \alpha, \beta, s)
$$
where $N \ge (I_1 + J_1) + \cdots + (I_M + J_M)$.
:::

### Monotone cells

We now present, closely following @bgv15, some useful properties of definable sets. These properties also apply to semialgebraic sets and are fundamental to the work presented in this thesis.

::: { .definition #affine-coordinate-subspace }
[@bgv15, Definition 2.1]

Let $L_{j,c} := \{ (x_1,\ldots,x_n) \mid x_j = c \}$ for some $1 \le j \le n$ and $c \in \R$.
Each intersection of the kind
$$
S := L_{j_1,c_1} \cap \ldots \cap L_{j_m,c_m}
$$
where $0 \le j \le m$, $1 \le j_1 < \cdots < j_m \le n$ and $c_1,\ldots,c_m \in \R$ is called an affine coordinate subspace of $\R^n$.
:::

::: { .definition #quasi-affine }
[@bgv15, Definition 2.2]
Let $\mathbf{f} = (f_1,\ldots,f_k) \colon X \to \R^k$ be a bounded continuous map defined on an open, bounded, non-empty
subset $X \subset \R^n$ having the graph $Y \subset \R^{n+k}$. Then $\mathbf{f}$ is called quasi-affine if, for any coordinate subspace $L \subset \R^{n+k}$, the restriction $\proj_{L}\vert_Y$ is injective if and only if $\proj_{L}(Y)$ is $n$-dimensional.
:::

::: {.remark}
The term quasi-affine map is not to be confused with quasi-affine variety.
Rather, it is a generalisation of the concept of an affine map from linear algebra.
Every affine map satisfies the definition of a quasi-affine map, but the definition also allows non-linear maps.
:::

::: { .definition #monotone-map }
[@bgv15, Definition 2.3]

Let $\mathbf{f} \colon X \to \R^k$ be a bounded, continuous, quasi-affine map defined on an open, bounded, non-empty
subset $X\subset \R^n$ having the graph $Y \subset \R^{n+k}$. Then $\mathbf{f}$ is called monotone if, for each affine coordinate subspace $S \subset \R^{n+k}$, the intersection $Y \cap S$ is connected.
:::

::: {.definition}
[@bgv15, Notation 2.4]

Let the space $\R^n$ have coordinate functions $x_1,\ldots,x_n$.
Given a subset
$$
I = \{x_{j_1}, \ldots, x_{j_m} \} \subset \{x_1 ,\ldots, x_n \},
$$ let $W$ be the linear subspace of $\R^n$ where all coordinates in $I$ are equal to zero.
We write $\opspan{x_{j_1},\ldots, x_{j_m}}$ to mean the
quotient space $\R^n / W$.
Similarly, for any affine coordinate subspace $L \subset \R^n$ on which all the
functions $x_j \in I$ are constant, we will identify $L$ with its image under the canonical surjection
to $\R^n / W$. We write $\R^k$, where $k \le n$, to mean $\opspan{x_1, \ldots, x_k }$, and $\projops{x_{i_1},\ldots,x_{i_k}}
\colon \R^n \to \opspan{x_{i_1},\ldots,x_{i_k}}$ denotes the projection map from $\R^n$ to $\opspan{x_{i_1},\ldots,x_{i_k}}$, where $\{i_1,\ldots,i_k\} \subset \{1,\ldots,n\}$.
:::

::: { .definition #monotone-cell }
[@bgv15, Definition 2.5]

The set $Y \subset \opspan{x_1,\ldots,x_n}$ is called a monotone cell if it is the graph of a monotone map $\mathbf{f} \colon X \to H$ where $H \subset \opspan{x_1,\ldots,x_n}$ and $X \subset \opspan{x_1,\ldots,x_n} \setminus H$.
:::

::: { .definition #monotone-map-on }
[@bgv15, Definition 2.10]

Let $X \subset \opspan{x_1,\ldots,x_n}$ be a monotone cell and $\mathbf{f} \colon X \to \opspan{y_1,\ldots,y_k}$ be a continuous map having graph $Y \subset \opspan{x_1,\ldots,x_n,y_1,\ldots,y_k}$. If $Y$ is a monotone cell, then $\mathbf{f}$ is called monotone on $X$.
:::

::: { .example #monotone-cells }
1. Observe that any quasi-affine map defined on a connected subset and having the graph in $\R^2$ is also monotone. This quasi-affine map will fail to be monotone if the set it is defined on is not connected.

2. Let $\Delta := \{ 0 < x < 1, y > 0, x + y < 1 \} \subset \R^2$ and $\varphi(x,y) = x^2 + y^2$. Let $Y \subset \R^3$
be the graph of the function $\varphi$ on $\Delta$. Observe that $\varphi\vert_\Delta$ is a quasi-affine map. However, $Y
\cap \{ z = 3/4 \}$ is not connected, hence $\varphi\vert_\Delta$ is not a monotone function [@bgv15, Example 4.3].
:::

::: { .proposition #monotone-topologically-regular }
[@bgv13, Theorem 1]

Every monotone cell is a topologically regular cell.
:::

The following properties of monotone cells are used in the proof of @bgv15, Theorem 3.20.

::: { .corollary }
[@bgv13, Corollary 7, Theorem 11]

Let $X \subset \R^n$ be a monotone cell, then:

1. $X \cap \{ x_i < c \}$, $X \cap \{ x_i = c \}$ and $X \cap \{ x_i > c \}$, for every $1 \le i \le n$ and $c \in \R$,
are either empty or monotone cells,
1. Let $Y \subset X$ be a monotone cell such that $\dim(Y) = \dim(X) - 1$ and $\fr{Y} \subset \fr{X}$. Then $X \setminus Y$ is a disjoint union of two monotone cells.
:::

::: { .proposition }
[@bgv13, Theorem 10]

Let $X \subset \R^n$ be a monotone cell. Then $\proj_{L}(X)$, for any affine coordinate subspace $L \subset \R^n$ is also a monotone cell.
:::

::: { .remark #monotone-proj-basis }
[@bgv15, Remark 2.11]
Let $Y \subset \R^n$ be a monotone cell and $L$ be a coordinate subspace such that $\proj_L\vert_Y$ is injective.
Then $Y$ is the graph of a monotone map defined on $\proj_L(Y)$, by [@bgv13, Theorem 7 and Corollary 5].
:::

We finally revise the definition of Big O notation, following @gv2009, Definition 6.1.

::: {.definition #big-o }
[@gv2009, Definition 6.1]
Let $f,g,h \colon \N^\ell \to \N$ be functions and $n \in \N$.

- The expression $f \le \O(g)^n$ means that there exists $c \in \N$ such that $f < (cg)^n$ at every point in $\N^\ell$.
- The expression $f \le g^{\O(h)}$ means that there exists a $c \in \N$ such that $f \le g^{ch}$ at every point in $\N^\ell$.
:::

