## Cylindrical algebraic decomposition

We now give some background on Cylindrical Algebraic Decomposition (CAD).
@collins1975 introduced both the concept of Cylindrical Algebraic Decomposition along with an algorithm to construct a CAD, which is a finite partition of $\R^n$ into so-called Cylindrical Cells, such that each polynomial in $\mathbf{F} \subset \R[x_1,\ldots,x_n]$ has a constant sign on every cylindrical cell in the decomposition.

Before describing Collins' algorithm, we will first define, closely following @bgv15, a cylindrical cell and cylindrical decomposition. Note that @bgv15 work in the broader class of definable sets.

::: { .definition #cells }
Cylindrical cells are defined by induction on $n\ge 1$. Each cylindrical cell $C$ is a connected definable subset of $\R^n$ with an *index*
$$
(i_1,\ldots,i_n) \in \{0,1\}^n.
$$

- When $n = 0$, there is a unique cylindrical cell $\mathbf{0} \in \R^0$.

- When $n = 1$, a $(0)$-cell (section cell) is a point $c \in \R$ and a $(1)$-cell (sector cell) is an open interval: $(a,b)$, $(-\infty,b)$, $(a,\infty)$, $(-\infty,\infty)$ where $a,b\in \R$.

- When $n > 1$, suppose that $(i_1,\ldots,i_{n-1})$-cells are already defined and let $C'$ be one of these cells.
An $(i_1,\ldots,i_{n-1},0)$-cell (section cell) is the graph of a continuous definable function $f : C' \to \R$.
An - $(i_1,\ldots,i_{n-1},1)$-cell (sector cell) is a subset of the cylinder $C' \times \R$, either
  $$
\begin{aligned}
\{ (\mathbf{x},t) &\mid \mathbf{x} \in C', f(\mathbf{x}) < t < g(\mathbf{x})\},\\
\{ (\mathbf{x},t) &\mid \mathbf{x} \in C', -\infty < t < g(\mathbf{x})\},\\
\{ (\mathbf{x},t) &\mid \mathbf{x} \in C', f(\mathbf{x}) < t < \infty\},\\
\{ (\mathbf{x},t) &\mid \mathbf{x} \in C', t \in \R \}
\end{aligned}
  $$
  where $f,g : C' \to \R$ are continuous definable functions such that $f(\mathbf{x}) < g(\mathbf{x})$ for all $\mathbf{x} \in C'$.
:::

::: {.definition}
Let $S \subset \R^n$ be a definable subset of $\R^n$ and define the *frontier of $S$*
$$
\fr{S} := \cl{S} \setminus S,
$$
where $\cl{S}$ is the closure of $S$ in the Euclidean topology.
:::

If $C \subset \R^n$ is a cylindrical cell, then it will be convenient to partition $\fr{C}$ into three subsets: the top ($C_T$), bottom ($C_B$) and side-wall ($C_W$).

First let $C$ be a sector $(i_1,\ldots,i_{n-1},1)$-cell and let $C' := \projop{n-1}(C)$. If $C$ is bounded from below by a continuous function $f : C' \to \R$, then $C_B$ is the graph of $f$. Similarly, if $C$ is bounded from above by the graph of a continuous function $g : C' \to \R$, then $C_T$ is the graph of $g$. It is clear that the top and bottom of every cylindrical sector cell (if non-empty) are always cylindrical section cells.

Now let $C$ be an $(i_1,\ldots,i_{k},0,\ldots,0)$-cell, where $i_{k}=1$, and $C' := \projop{k}(C)$. Since $C'$ is a sector cell, $C'_B$ and $C'_T$ are cylindrical section cells. The bottom $C_B$ of $C$ is the pre-image of $C'_B$ by the projection map $\projop{k}\vert_{\cl{C}}$ and the top $C_T$ of $C$ is the pre-image of $C'_T$ by the projection map $\projop{k}\vert_{\cl{C}}$.
It may be simpler to think of $C_B$ as the definable set $\cl{C} \cap (C'_B \times \R^{n - k + 1})$ and $C_T$ as the definable set $\cl{C} \cap (C'_T \times \R^{n - k + 1})$.
It is important to note that $C_B$ and $C_T$ may not be cylindrical cells. Indeed, they may fail to be graphs of continuous functions (see Definition \@ref(def:blow-up-point) and Example \@ref(exm:top-bottom-not-cylindrical).

For both section and sector cells, let the side wall, $C_W$, be $\fr{C} \setminus (C_B \cup C_T)$.
There is no requirement that $C_W$ will be (a union of) cylindrical cells.

::: {.definition #blow-up-point }
[@bgv15, Definition 9.2]

Let $\varphi : W \to \R$ be a continuous function on a semialgebraic set $W \subset \R^n$, and let $\Phi \subset \R^{n+1}$ be its graph.

A point $\mathbf{x} \in \overline{W} \setminus W$ is called a blow-up point of $\Phi$ if $$\proj^{-1}_{\R^n} (\mathbf{x}) \cap \overline{\Phi}$$ contains an open interval.
:::

::: {.remark #blow-up-codimension }
The closure of the graph of a continuous definable function is the graph of a continuous definable function everywhere
except, possibly, over a subset of codimension at least $2$ (see the proof of @bgv15, Lemma 3.14).
:::

::: { .example #top-bottom-not-cylindrical }
In $\R^3$, let $C' := \{ -1 < x < 1, \vert x \vert < y < 1 \}$ and $\varphi(x,y) = \vert x / y \vert$ so that $C$ is the graph of $\varphi\vert_{C'}$.
Consider $$
C_B := \{ -1 < x < 1, y = \vert x \vert, z = 1 \} \cup \{ (0,0,z) \mid 0 \le x \le 1 \}.
$$
$C_B$ is not the graph of a continuous function due to the blow-up point of $\varphi$ at the origin.
:::

We now define the cylindrical decomposition.

::: {.definition}
A cylindrical decomposition is defined by induction on $n \ge 0$.

- When $n = 0$, the unique cylindrical decomposition of $\R^0$ is the unique point in $\R^0$.

- When $n > 0$: Let $\cal D$ be a partition of $\R^n$ into cylindrical cells.
Define $\cal D'$ to be the set of all projections $C' := \projop{n-1}(C)$ for all $C$ in $\cal D$.
$\cal D$ is a cylindrical decomposition of $\R^n$ if $\cal D'$ is a cylindrical decomposition of $\R^{n-1}$. We call $\cal D'$ the decomposition of $\R^{n-1}$ induced by $\cal D$.
:::

Less formally, a partition $\cal D$ of $\R^n$ into definable subsets is cylindrical if the projection of any two cells of $\cal D$ onto $\R^{n-1}$ is either disjoint or coincides.

::: {.definition}
Let $S \subset \R^n$ be a definable set. A cylindrical decomposition $\cal D$ is compatible with $S$ if every cell $C$ of $\cal D$ is either a subset of $S$ or disjoint from $S$.
:::

::: {.definition}
A cylindrical decomposition $\cal E$ is called a refinement of $\cal D$ if $\cal E$ is compatible with every cell of $\cal D$. in other words, every cell of $\cal D$ is a union of cells in the refinement $\cal E$.
:::

::: { .remark }
[@bgv15, Remark 3.8]
Let $\cal D$ be a cylindrical decomposition of $\R^n$ and $C$ be a cylindrical cell of $\cal D$ such that $c := \projop{1}(C)$ is a single point. Then it follows immediately from the definition that $\cal D$ is compatible with the hyperplane $\{ x_1 = c \}$ and the set of all cells of $\cal D$ contained in this hyperplane form a cylindrical decomposition $\cal E$ of $\R^{n-1}$. Moreover, any refinement of $\cal E$ is also a refinement of $\cal D$.
:::

We now present some useful results proved by @bgv15 relating to desirable properties of cylindrical decompositions.

::: {.definition}
Let $S \subset \R^n$ be a definable set. A cylindrical decomposition $\mathcal{D}$ of $\R^n$, compatible with $S$, is called monotone with respect to $S$ if every cell $C \subset S$ of $\cal D$ is monotone.
:::

::: {.definition #frontier-condition}
Let $\cal D$ be a cylindrical decomposition of $\R^n$ and $C$ be a cell of $\cal D$. $C$ satisfies the frontier condition in $\cal D$ is $\fr{C}$ is a union of cells of $\cal D$ of smaller dimension. If it is unambiguous that $C$ is a cell of $\cal D$, then we just say that $C$ satisfies the frontier condition.
If every cell in $\cal D$ satisfies the frontier condition, then the cylindrical decomposition $\cal D$ satisfies the frontier condition.
:::

We saw in Example \@ref(exm:top-bottom-not-cylindrical) that the top and bottom of a 2-dimensional cylindrical section cell, even in $\R^3$, need not be a union of cylindrical cells.
However, it is clear from the cylindrical property that, if $C$ is a 2-dimensional section cell satisfying the frontier condition in a decomposition $\cal D$, then the top and bottom of $C$ are single cylindrical cells.
If $C$ is a 2-dimensional section cell, then it is said to satisfy the strong frontier condition if the one-dimensional components of its side-wall are 1-dimensional section cells. This condition may be impossible, even in $\R^3$, as Example \@ref(exm:side-wall) demonstrates.

::: {.example #side-wall}
Consider the two cylindrical cells
$$
V := \{ x > y > 0, z > 0, y = xz \}
$$ and $$
W := \{ x > y > 0, z > 0, y = 2xz \}
$$ in $\R^3$.
Any cylindrical decomposition compatible with $V$ and $W$ is also compatible with the two intervals
$$
I_1 = \{ (0,0,z) \mid 0 \le z \le 1/2 \}, I_2 = \{ (0,0,z) \mid 1/2 \le z \le 1 \}
$$
and the point $$v = (0,0,1/2).$$
Observe that $I = \{ (0,0,z) \mid 0 \le z \le 1 \}$ is the only one-dimensional component of the side-wall of $V$ and $I_1$ is the only one-dimensional component of the side-wall of $W$. In order to obtain the strong frontier condition, we need to partition $V$ into (at least) three cylindrical cells $V',V'',V'''$, one of which, say $V''$, will be one-dimensional. $V''$ should have endpoint $v$ (i.e., $\cl{V''} \cap I = v$).
The tangent at the origin of $c := \projop{2}(V'')$ is $1/2$. The pre-image of the projection map $W' := \projop{2}^-1\vert_{\cl{W}}(c)$ would satisfy the condition $\cl{W'} \cap I = v'$, where $v' = (0,0,1/4)$. However, $v'$ must be a zero-dimensional cell of the decomposition, which means we need to perform another refinement of $I$. An infinite sequence of refinements, introducing a new 0-dimensional cell $(0,0,1/2^k), k \in \N_{> 0}$, will take place. Thus, a decomposition in in which the side-walls of $V$ and $W$ are single 1-dimensional cells cannot exist.
:::

::: { .proposition #delete-zero-index }
[@bgv15, Lemma 3.3]

Let $C$ be an $(i_1,\ldots,i_{k-1},0,i_{k+1},\ldots,i_n)$-cell. Then
$$C' := \projops{x_1,\ldots,x_{k-1},x_{k+1},\ldots,x_n}(C)
$$
is a cylindrical $(i_1,\ldots,i_{k-1},i_{k+1},\ldots,i_n)$-cell and $C$ is the graph of a monotone map $f : C' \to \opspan{x_k}$.
:::

::: { .proposition }
[@bgv15, Lemma 3.4]

Let $C \subset \R^n$ be a 2-dimensional cylindrical cell which is the graph of a quasi-affine map. Then the side-wall $W \subset \fr{C}$ has exactly two connected components, each of which is either a point or a closed curve interval.
:::

::: {.remark}
It was proved by @pianomovers1983 that a cylindrical decomposition, compatible with a semialgebraic set and satisfying the frontier condition, can be obtained following a linear rotation of coordinates.
@jhd20 prove that a cylindrical decomposition having constant sign on a set of input polynomials will contain topologically regular cells and satisfy the frontier condition, regardless of the method used to construct it, as long as the input polynomials do not blow up anywhere.
Proposition \@ref(prp:monotone-topologically-regular) (@bgv13, Theorem 1) asserts that every monotone cell is topologically regular, so @bgv15, Theorem 3.20 describes the construction of a CAD, compatible with a family $V_1,\ldots,V_k$ of definable subsets of $\R^n$, each having dimension at most $2$, in the potential presence of blow-up points and without the need to make a change of coordinates.
:::

### Constructing a CAD {#sec:cad-construction}

::: {.remark}
A cylindrical algebraic decomposition (CAD) is a cylindrical decomposition in which every cell is a semialgebraic set. While the results of @bgv15 are proved for the wider class of cylindrical decompositions compatible with definable sets, we will restrict ourselves to CADs, allowing us to take advantage of properties of polynomials.
:::

::: {.definition}
Let $\mathbf{F} := (f_1,\ldots,f_s) \subset \Z[x_1,\ldots,x_n]$ be a set of polynomials with integer coefficients. A cylindrical algebraic decomposition $\cal D$ is called sign-invariant with respect to $\mathbf{F}$  (or simply $\mathbf{F}$-invariant) if each polynomial $f \in \mathbf{F}$ has a constant sign (either $< 0$, $= 0$ or $> 0$) on every cylindrical cell $C$ of $\mathcal{D}$.
:::

::: {.remark}
The fundamental theorem of algebra implies that for the coefficients of $\mathbf{F}$, we may choose any ring $K \subset \R$. $\Z$ has been chosen for convenience, but some authors (e.g., @pianomovers1983) choose $\Q$ instead. It is also common to take polynomials with coefficients over $\R$. However, the choice has been made to avoid this so as to work over the algebraic numbers $\mathcal{A}$, whose elements are easily represented in, and manipulated by, computers.
:::

Let $\mathbf{F} \subset \Z[x_1,\ldots,x_n]$ be a set of polynomials with integer coefficients. We will now describe the algorithm proposed by @collins1975, closely following @coste2000, for constructing an $\mathbf{F}$-invariant CAD of $\R^n$.

Collins' algorithm uses the idea of projection and lifting. More precisely, successive projections of the set of input polynomials to smaller and smaller dimensions are taken, until a set of univariate polynomials is obtained. The CAD of $\R^1$ is constructed by isolating the roots of these univariate polynomials, with section cells being the roots and sector cells being the open intervals in between them. The lifting phase then works recursively: given a collection of cells in $\R^k$ and a set of polynomials in $\R^{k+1}$, the roots of these polynomials within each cell $C$ are isolated. The section cells in the cylinder $C \times \R$ are the roots of these polynomials, while the sector cells are the bands in between the roots. The projection operation was designed such that the cylindrical property holds. I.e., above $C$, each polynomial has a constant number of roots and the roots of no two polynomials "cross over" each other.
The second property is called delineability.

Let us begin the description of the algorithm by considering a single polynomial $f \in \Z[x_1,\ldots,x_n]$.
We want to partition $\R^{n-1}$ into connected semialgebraic sets $C'$ such that, for all $\mathbf{x} \in C'$, $f(\mathbf{x},x_n)$ has constant degree and a constant number of roots.

::: {.proposition #coste-polynomial-to-cell }
[@coste2000, Proposition 2.16]

Let $f \in \Z[x_1,\ldots,x_n]$ and, $C' \subset \R^{n-1}$ be a connected semialgebraic set and $k \le d \in \N$ such that, for every point $\mathbf{x} \in C'$, the univariate polynomial $f(\mathbf{x},x_n) \in \A[x_n]$ has degree $d$ and exactly $k$ distinct (complex) roots in $C'$.
Then there are $\ell \le k$ distinct semialgebraic functions
$$\psi_1,\ldots,\psi_\ell : C' \to \R
$$
such that, for every $\mathbf{x} \in C'$, the set of real roots of $f(\mathbf{x},x_n)$ is exactly
$$\{ \psi_1(\mathbf{x}, \ldots, \psi_\ell(\mathbf{x}) \}.$$
Moreover, the multiplicity of each of these roots is constant.
:::

::: {.proof}
The argument relies on the "continuity of roots":

> Fix $\mathbf{c} \in C'$ and let $z_1,\ldots,z_k$ be the distinct roots of $f(\mathbf{c},x_n)$ with multiplicities $m_1,\ldots,m_k$.
Choose $\varepsilon > 0$ small enough that the open discs $D(z_i,\varepsilon), z_i \in \mathbb{C}$ (center $z_i$, radius $\varepsilon$) are disjoint. If $\mathbf{b} \in C'$ is sufficiently close to $\mathbf{c}$, then the polynomial $f(\mathbf{b}, x_n)$ has exactly $m_i$ roots, counted with multiplicities, in $D(z_i,\varepsilon)$ for $1\le i \le k$.

Since $f(\mathbf{b},x_n)$ has $k$ distinct complex roots, and $d = m_1+ \ldots + m_k$ complex roots counted with multiplicities, it follows that each $D(z_i,\varepsilon)$ contains exactly one root, denoted $\zeta_i$, of $f(\mathbf{b},x_n)$ with multiplicity $m_i$.
If $z_i$ is real, then $\zeta_i$ is real, otherwise the complex conjugate of $\zeta_i$ would be another root of $f(\mathbf{b},x_n)$ in the disc $D(z_i,\varepsilon)$.
If $z_i$ is complex then $\zeta_i$ is also complex, since the conjugation of every point in $D(z_i, \varepsilon)$ lies outside $D(z_i, \varepsilon)$, forming another disc $D(\overline{z_i}, \varepsilon)$.
It follows that, if $\mathbf{b} \in C'$ is close enough to $\mathbf{c}$, then $f(\mathbf{c},x_n)$ has the same number of real roots as $f(\mathbf{b},x_n)$. Since $C'$ is connected, $f(\mathbf{x},x_n)$ has the same number of real roots at every point $\mathbf{x} \in C'$, say $\ell$.
Define $\psi_i(\mathbf{x}) : C' \to \R$ to be the continuous (by making $\varepsilon$ small enough) semialgebraic function sending $\mathbf{x} \in C'$ to the $i$-th (in ascending order) real root of $f(\mathbf{x},x_n)$. It follows from the connectedness of $C'$ that each $\psi_i$ has constant multiplicity.
Observe that the graph of each $\psi_i$ can be expressed by a first-order Boolean formula, using existential quantifiers to express each of the $\ell$ roots of $f(\mathbf{x},x_n)$ and an equality condition to pick out the $i$-th root.
It follows that the graph of each functin $\psi_i$ is a semialgebraic set.
:::

To extend this result to more than one polynomial, we also need to ensure that the graphs corresponding to each root never intersect.

::: {.proposition}
[@coste2000, Proposition 2.18]

Let $f,g \in \Z[x_1,\ldots,x_n]$, $C' \subset \R^{n-1}$ such that, for all $\mathbf{x} \in C'$, the degree and number of roots of $f(\mathbf{x},x_n)$ and $g(\mathbf{x},x_n)$ is constant and the degree of the GCD of $f(\mathbf{x},x_n)$ and $g(\mathbf{x},x_n)$ is constant.
Let $\varphi,\psi : C' \to \R$ be continuous semialgebraic functions such that $f(\mathbf{x},\varphi(\mathbf{x})) = 0$ and $g(\mathbf{x},\psi(\mathbf{x})) = 0$ for all $\mathbf{x} \in C'$.
If there exists $\mathbf{c} \in C'$ such that $\varphi(\mathbf{c}) = \psi(\mathbf{c})$, then $\varphi(\mathbf{x}) = \psi(\mathbf{x})$ for all $\mathbf{x} \in C'$.
:::

::: {.proof}
We use the same method of proof as in the previous proposition.
For an arbitrary element $\mathbf{c} \in C'$, let $z_1 = \varphi(\mathbf{c}) = \psi(\mathbf{c}), \ldots, z_k$ be the distinct roots in $\mathbb{C}$ of the product
$$
f(\mathbf{c},x_n)\ g(\mathbf{c},x_n)
$$
(recall that $fg = 0$ if either $f=0$ or $g=0$).
Let $m_i$ (resp $p_i$) be the multiplicity of $z_i$ as a root of $f(\mathbf{x},x_n)$ (resp. $g(\mathbf{x}, x_n)$) where multiplicity zero indicates that $z_i$ is not a root.
The degree of $\gcd(f(\mathbf{x}, x_n), g(\mathbf{x}, x_n))$ is $\min(m_1,p_1) + \cdots + \min(m_k,p_k)$ and each $z_i$ has multiplicity $\min(m_i,p_i)$ as a root of this GCD.
Choose $\varepsilon > 0$ small enough that the discs $D(z_i,\varepsilon)$ are disjoint.
For each $\mathbf{b} \in C'$ close enough to $\mathbf{c}$, each disc contains a root of multiplicity $m_i$ of $f(\mathbf{b}, x_n)$ and a root of multiplicity $p_i$ of $g(\mathbf{b}, x_n)$. Since the degree of the GCD of $f$ and $g$ (evaluated at any $\mathbf{x} \in C'$) is equal to $\min(m_1,p_1) + \cdots + \min(m_k,p_k)$, this GCD must have one root of multiplicity $\min(m_i,p_i)$ in each disc $D(z_i,\varepsilon)$ such that $\min(m_i,p_i) > 0$.
In  particular, it follows that $\varphi(\mathbf{b}) = \psi(\mathbf{b})$. Since $C'$ is connected, this equality holds for all $\mathbf{x} \in C'$.
:::

Now we have algebraic conditions on the polynomials in the set of level-$(n-1)$ projection polynomials $\mathbf{F}' = \proj(\mathbf{F})$. We now describe how these properties can be satisfied and, as such, how the set $\mathbf{F}'$ can be constructed. We will need the concept of the principal subresultant coefficient of two polynomials $f$ and $g$.

::: {.definition}
Let $f,g \in \Z[x_1,\ldots,x_{n-1}][x_n]$ be polynomials, with degrees $d$ and $e$ respectively, such that
\begin{align*}
f(x_n) &= a_d x_n^d + \cdots + a_1 x_n + a_0 \\
g(x_n) &= b_e x_n^e + \cdots + b_1 x_n + b_0. \\
\end{align*}
Then the Sylvester matrix associated to $f$ and $g$ is the $(d + e) \times (d + e)$-matrix defined as follows.
$$
S_{f,g}(f,g) =
\begin{pmatrix}a_{d} & \ldots & a_{0} & 0 & \ldots & \ldots & 0\\
0 & a_{d} & \ldots & a_{0} & 0 & \ldots & 0\\
\ldots & 0 & a_{d} & \ldots & a_{0} & \ldots & 0\\
b_{e} & \ldots & b_{0} & 0 & \ldots & \ldots & 0\\
0 & b_{e} & \ldots & b_{0} & 0 & \ldots & 0\\
\ldots & 0 & b_{e} & \ldots & b_{0} & \ldots & 0
\end{pmatrix}.
$$
:::

::: {.definition}
Let $f,g \in \Z[x_1,\ldots,x_{n-1}][x_n]$ be polynomials with degrees $d$ and $e$ respectively. The principal subresultant coefficient of order $j$ of $f$ and $g$, denoted $\psrc_j(f,g)$, is the determinant of the $(m + n - 2j) \times (m + n - 2j)$-matrix obtained from the Sylvester matrix associated to $f$ and $g$ by deleting the  first and last $j$ rows and columns.
:::

Let $f,g \in \Z[x_1,\ldots,x_{n-1}][x_n]$ and $X \subset \Z[x_1,\ldots,x_n]$.

- $f$ has a constant number of complex roots over $X$ if
$$
\psrc_k(f, \partial f / \partial x_n),
$$
for $1 \le k \le \deg(f)$, is either zero or nonzero everywhere in $X$.
- $f$ and $g$ have constant GCD in $X$ if
$$
\psrc_k(f, g),
$$
for $1 \le k \le \min(\deg(f),\deg(g))$, is either zero or nonzero and $\deg(f) = \deg(g)$ everywhere in $X$.
- If, for the leading term of $f$ (or $g$) vanishes at some points in $\Z[x_1,\ldots,x_{n-1}]$, we need to take the principal subresultant coefficients of the reductum of $f$ (or $g$).
[@coste2000, pp36]

From these properties of the principal subresultant coefficient, we can define a projection operator.

::: {.definition}
Consider $f \in \Z[x_1,\ldots,x_n]$ as a univariate polynomial in $x_n$. I.e.,
$$
f(x_n) = a_d x_n^d + \cdots + a_1 x_n + a_0
$$
where $a_d,\ldots,a_0 \in \Z[x_1,\ldots,x_{n-1}]$.
Let $\lc{f} = a_d$ denote the leading coefficient of $f$ and $\red(f) = a_{d-1}x_n^{d-1} + \cdots + a_1 x_n^1 + a_0$ be the reductum of $f$.

Let $\mathbf{F} \subset \Z[x_1,\ldots,x_n]$. We define the projection operator, $\proj(\mathbf{F})$ as follows:

- Let $d := \deg(f_i)$. If $d > 1$, then $\proj(f_1,\ldots,f_i,\ldots,f_s)$ contains
$$
\psrc_k(f_i, \partial f_i / \partial x_n)
$$
for all $1\le k \le d$.

- Let $d := \min(\deg(f_i), \deg(f_j))$. If $d > 0$, then $\proj(f_1,\ldots,f_i,\ldots,f_j,\ldots,f_s)$ contains
$$
\psrc_k(f_i, f_j)
$$
for all $1 \le k \le d$.

- If $\deg(f_i) > 0$ and $\lc(f_i)$ is non-constant, then $\proj(f_1,\ldots,f_i,\ldots,f_s)$ contains
$$
\lc(f_i) \text{ and } \proj(f_1,\ldots,\red(f_i),\ldots,f_n).
$$
:::

::: {.theorem #cad-lift}
[@coste2000, Theorem 2.19]
Let $\mathbf{F} \subset \Z[x_1,\ldots,x_n]$ be a family of polynomials and let $C'$ be a connected $\proj(\mathbf{F})$-invariant semialgebraic subset of $\R^{n-1}$ -- an $(i_1,\ldots,i_{n-1})$-cell.
Then there exist continuous definable functions
$$
\psi_1,\ldots, psi_\ell : C' \to \R
$$
such that for all $\mathbf{x} \in C'$, the set $\{ \psi_i(\mathbf{x}), \ldots, \psi_k(\mathbf{x}) \}$ coincides with the real roots of polynomials in $\mathbf{F}$, defining the $(i_1,\ldots,i_{n-1},0)$-cells in the cylinder $C' \times \R$ and $\{ -\infty < t < \psi_1(\mathbf{x}), \ldots, \psi_i(\mathbf{x}) < t < \psi_{i+1}(\mathbf{x}), \ldots, \psi_k(\mathbf{x}) < t < \infty \}$ are the $(i_1,\ldots, i_{n-1},1)$-cells in the cylinder $C' \times \R$.
:::

This follows from the results previously proved. Applying Theorem \@ref(thm:cad-lift), we are able to pass from a $\projop{k-1}(\mathbf{F})$-invariant CAD of $\R^{k-1}$ to a $\projop{k}(\mathbf{F})$-invariant CAD of $\R^k$. Thus, by iterating the projection operation until we obtain a set of polynomials in $\Z[x_1]$, isolating their roots, and then iteratively applying Theorem \@ref(thm:cad-lift)$, we are able to obtain an $\mathbf{F}$-invariant CAD of $\R^n$.

### Bounds and variations

We have described how to construct a CAD of $\R^n$ which is sign-invariant with respect to a set of polynomials. We now
present the bounds, along with some variations, from @bpr2006.

::: { .proposition #collins }
[@bpr2006, Algorithm 11.2]

Let $\mathbf{F} := f_1,\ldots,f_s$ be a set of polynomials in $\Z[x_1, \ldots ,x_n]$ with maximum degree $d$.
There is an algorithm, taking $\mathbf{F}$ as input, which produces an $\mathbf{F}$-invariant CAD $\cal D$ of $\R^n$.
The complexity of the algorithm is
$$(sd)^{O(1)^{n}}.
$$
This is also an upper bound on the number of cells in $\cal D$, number of polynomials defining cells and their degrees.
:::

Observe that these bounds are doubly exponential in the number of variables. It is not possible to improve upon this doubly exponential bound.
Indeed, @davenportHeintz1988 give an example of a CAD in which a doubly exponential number of cells is obtained. In practice, we can obtain a CAD with fewer cells, e.g., by constructing a truth invariant or partial CAD.

::: { .corollary #collins-sets}
Let $S_1,\ldots,S_k$ be a finite collection of semialgebraic subsets of $\R^n$ defined by quantifier-free Boolean formulas $F_1,\ldots,F_k$ respectively. Together, these formulas include $s$ different polynomials in $\Z[x_1,\ldots,x_n]$ with maximum degree $d$.
There is an algorithm, taking $\{F_1,\ldots,F_k\}$ as input, which produces a cylindrical decomposition $\mathcal E$ of $\R^n$ compatible with each set $S_i, 1 \le i \le k$.
Complexity, number of cells, number of polynomials and degrees are the same as in Proposition \@ref(prp:collins) but, in practice, more efficient algorithms exist (see e.g., @collins1991 and @bradford2014).
:::

::: { .proof }
This construction follows immediately from Proposition \@ref(prp:collins), where truth values of $F_1,\ldots,F_k$ associated to each cell.
The complexity upper bound (and bounds on number of cell, polynomials and degrees) is the same as in Proposition \@ref(prp:collins).
:::

It is also common to construct a CAD compatible with a single semialgebraic set.

::: { .corollary #collins-set }
Let $S\subset \R^n$ be a semialgebraic set defined by a quantifier-free Boolean formula $F$ containing $s$ different polynomials in $\R[x_1,\ldots,x_n]$, having maximum degree $d$.
There is an algorithm, taking $F$ as input, which produces a cylindrical decomposition $\mathcal E$ of $\R^n$ compatible with $S$.
Complexity, number of cells, number of polynomials and degrees are the same as in Proposition \@ref(prp:collins).
:::

::: { .proof }
Immediate, by applying Corollary \@ref(cor:collins-set) to $\{ F \}$.
:::

The construction described in Corollary \@ref(cor:collins-sets) is somewhat naive.
A far more efficient algorithm are presented in e.g., @collins1991. An alternative approach is presented by @bradford2014.
While very useful in practice, these constructions are unable to lower the upper bound from Proposition \@ref(prp:collins) due to some extreme cases, e.g., when the input formulas define a sign-invariant CAD (see @bradford2014, Section 6.2.1].

### The projection operator

Since Collins published his CAD algorithm in 1975, many variations of the projection operator have been proposed. Most of these aim to minimise the number of polynomials  appearing in $\proj_{k-1}(\mathbf{F})$, so as to make the algorithm more efficient in practice.
For example, @collins1975 observed that, in dimension $2$, if the set $\mathbf{F} \subset \Z[x_1,x_2]$ of input polynomials is
squarefree and pairwise relatively prime, then it is sufficient to include only the leading
coefficients, resultants and discriminants of pairs of polynomials in $\proj(\mathbf{F})$. @mccallum1988 then proved that a
similar construction is possible in dimension $3$.
@mccallum1998 later improved upon his previous work by extending this result to dimension $n > 3$, as long as the set of input polynomials is well oriented.

::: {.definition}
[@mccallum1998, 6.1]
Let $\mathbf{F} \subset \Z[x_1, \ldots, x_n]$ be a set of polynomials and denote by $\prim(\mathbf{F})$ the set of all primitive parts of $\mathbf{F}$
$\mathbf{F}$ is called well-oriented if, when $n > 1$,

- for each element $f \in \prim(A)$, $f(\mathbf{x},y) = 0$ for all $y\in \R$ on a finite number of points $\mathbf{x} \in \R^{n-1}$. [@mccallum1998, condition WO1]

- $\proj(\mathbf{F})$ is well-oriented. [@mccallum1998, condition WO2]
:::

@brown2001 then observed that even more polynomials can be discarded, creating the Reduced McCallum Projection Operator. This is commonly used in practice, e.g., in `QEPCAD-B` [@brownQepcad].

Let $\mathbf{F} \subset \Z[x_1,\ldots,x_n]$ be a well-oriented set of polynomials and $\cal D$ be an $\mathbf{F}$-invariant CAD constructed using the McCallum projection operator [@mccallum1998]. Then, by @mccallum1988 Theorems 2.2.3 and 2.2.4, every cell $C$ of $\cal D$ is an analytic submanifold of $\R^n$. Informally, if $\dim(C) = k$, thent $C$ is a non-empty subset of $\R^n$ which "looks locally like $\R^k$" (see Definition \@ref(def:analytic-submanifold) for the precise definition).

::: {.definition #analytic-submanifold}
$S \subset \R^n$ such that $\dim(S) = k$ is an analytic submanifold if, for every point $\mathbf{x} \in S$, there is an analytic coordinate system about $\mathbf{x}$ with respect to which $S$ is locally the intersection of $n-k$ coordinate hyperplanes.
:::

::: {.corollary #mc-smooth}
Let $S \subset \R^n$ be a semialgebraic set defined by a quantifier-free Boolean formula constructed from the set of polynomials $\mathbf{F} \subset \Z[x_1,\ldots,x_n]$, such that $\mathbf{F}$ is well-oriented.
Then a CAD $\cal D$ of $\R^n$ compatible with $S$ and such that every cell $C$ of $\cal D$ is an analytic submanifold of $\R^n$ can be obtained by constructing an $\mathbf{F}$-invariant CAD of $\R^n$ using the McCallum projection operator.
:::

More recently, @mccallum2019 completed the proof that Lazard's projection operator is valid. McCallum also proved,
without the condition on well-orientedness of input polynomials, that every cell of a sign-invariant CAD constructed
using Lazard's projection operator is an analytic submanifold. Thus, we can generalise Corollary \@ref(cor:mc-smooth) further:

::: {.rolollry #lz-smooth}
Let $S \subset \R^n$ be a semialgebraic set defined by a quantifier-free Boolean formula constructed from the set of polynomials $\mathbf{F} \subset \Z[x_1,\ldots,x_n]$.
Then a CAD $\cal D$ of $\R^n$ compatible with $S$ and such that every cell $C$ of $\cal D$ is an analytic submanifold of $\R^n$ can be obtained by constructing an $\mathbf{F}$-invariant CAD of $\R^n$ using the McCallum projection operator.
:::

### Projection polynomials vs semialgebraic functions

Recall that Proposition \@ref(prp:coste-polynomial-to-cell) allows us to pass from a projection polynomial $f \in \Z[x_1,\ldots,x_k]$ to the continuous semialgebraic functions $\varphi : C' \to \R$, where $C' \subset \R^{n-1}$ is a cylindrical cell, from Definition \@ref(def:cells) which define some of the section cells in the cylinder $C' \times \R$. The construction described in @bgv15, Theorem 3.20 (and related lemmas) works with these continuous semialgebraic functions. However, we are given only the projection polynomials $f$ of which $\varphi$ defines one of the roots.

Let $C$ be a section cell in $\R^n$: a semialgebraic set which is the graph of a continuous semialgebraic function $\varphi : C' \to \R$, where $C' \subset \R^{n-1}$ is a cylindrical cell. A simple example in $\R^2$ demonstrates that, although $C$ is a semialgebraic set, $\varphi$ may not be a polynomial. Indeed, let
$$ C := \{ (x,y) \in \R^2 \mid x > 0, y > 0, y = x^2 \} $$
be a cylindrical cell in $\R^2$ such that $C' := \projop{1}(C) = \{ x \in \R \mid x > 0 \}$. We can write
$$
\varphi(x) = +\sqrt{x}
$$
such that $C$ is the graph of $\varphi\vert_{C'}$. However, it's clear that $\varphi$ is not a polynomial.

In computations, we work exclusively with section cells. When dealing with sector cells, we will consider the graphs of functions defining their top and bottom.
Since we will be using `SACLIB` and sometimes `Singular`, which are polynomial libraries, we will not be able to use the functions $\varphi$ in computations. We will instead use a different representation for a section cell $C$ in $\R^n$. Let $C$ be the root of a polynomial $f \in \Z[x_1,\ldots,x_n]$ and $C' := \projop{n-1}(C)$ satisfy the conditions in Proposition \@ref(prp:coste-polynomial-to-cell). Then
$$
C \subset Z := \{ (\mathbf{x},x_n) \in \R^n \mid \mathbf{x} \in C', f(\mathbf{x},x_n) = 0 \} \subset C' \times \R.
$$
In particular, $Z$ consists of the roots of $f$ in the cylinder $C' \times \R$, which includes the section cell $C$. It is
clear from the Tarski--Seidenberg theorem that it is possible to represent $C$ as a first-order Boolean formula. In practice, since $C$ is the root of a polynomial, we may define it using Thom's Lemma [@costeRoyThomLemma]. I.e., a root of a polynomial may be defined by sign conditions on its derivatives. Thus, let
$$
C = \{ (\mathbf{x},x_n) \in \R^n \mid \mathbf{x} \in C', f(\mathbf{x},x_n) = 0, g_1(\mathbf{x},x_n) > 0, \ldots, g_k(\mathbf{x},x_n) > 0 \}
$$
where $g_1,\ldots,g_k$ are derivatives of the polynomial $f$.

### CAD cells and their defining formulas { #sec:cell-formula }

Although it is possible to construct a "full" (sign-invariant) CAD, `QEPCAD-B` provides an implementation of the "truth-invariant" CAD described in Corollary \@ref(cor:collins-sets). Indeed, QEPCAD-B, being designed primarily to perform quantifier elimination, frequently constructs a "partial" CAD of $\R^n$ [@brownQepcad].
We will force the construction of the sign-invariant CAD and use McCallum's projection operator so as to obtain smooth
cells (see Corollary \@ref(cor:mc-smooth)).

Once constructed, one may want to examine individual cells of the CAD.
In order to do this, we will need a convenient representation for each cell.
Depending on the purpose for which the CAD has been constructed, a particular representation may be chosen. For example, if we only need a witness, i.e., some point in the cell, only the sample points are needed. Indeed, this is a common requirement and Maple's `RegularChains::CylindricalAlgebraicDecompose` function provides output in this representation [@chen2014].
On the other hand, one might want to view each cell as a semialgebraic set. In this case, a defining formula will be necessary.
Such a representation using only the input and projection polynomials may be impossible and, as such, an "extended language" has been introduced in both Maple and `QEPCAD` [@chen2014, @brownQepcad]. The extended language includes the rules of first-order Boolean formulas (see Definition \@ref(def:qff)) along with a means of representing "the $i$-th root of polynomial $f$". We find this representation a little inconvenient and would prefer each cell to be representable by an ordinary first-order Boolean formula.

To see how the signs of projection factors may be insufficient to represent a cylindrical cell, consider the following simple example in $\R^2$.
Let $f = x - y^2$ and construct an $\{f\}$-invariant CAD. The projection polynomials
$$
P = \{ x, x - y^2 \}.
$$
The two distinct cells $C_1$ and $C_2$ have signs $x > 0, x - y^2 = 0$. By Thom's Lemma, it is possible to represent these cells by sign conditions on derivatives of $f$.
In this example, it is clear that another polynomial, $y$, is needed to distinguish between these cells. @brown99 proposed an algorithm for constructing a solution formula if the projection polynomials are not sufficient. The basic idea is that "conflicting pairs", distinct cells having the same signature (signs of projection factors), are identified, then additional derivatives of projection factors are added so that the conflicting pairs can be distinguished.

The algorithm proposed by @brown99 is implemented as the "solution formula construction phase" in QEPCAD. A small modification has been made such that this algorithm may be used to construct formulas for individual cells as opposed to the set of points satisfying the input formula. More precisely, the definition of a conflicting pair was slightly modified.

::: {.definition}
Let $C_1$ and $C_2$ be distinct cells in a CAD $\cal D$ of $\R^n$. Each cell $C$ is assigned a truth value $T_C \in \{\tt{True}, \tt{False}, \tt{undet}\}$ and a list $S_C = (S_1,\ldots,S_k)$ where $S_i = (s_{i,1},\ldots,s_{i,s_i}, 1\le i \le k$ is the list of signs of level-$i$ (factorised) projection polynomials $f_1,\ldots,f_{i_s} \in \Z[x_1,\ldots,x_i]$, with $s_{i,j} \in \{-1,0,1\}$.
$(C_1, C_2)$ is called a conflicting pair in $\cal D$ if $T_{C_1}, T_{C_2} \in \{\tt{True}, \tt{False}\}$ and $T_{C_1} = T_{C_2}$ and $S_{C_1} = S_{C_2}$ (equality determined component-wise).
:::

For our purposes, the condition on truth values being equal has been dropped so that every cell in the CAD may be distinguished by the signs of its projection polynomials only. In all other aspects, Brown's solution formula construction algorithm may be applied unchanged. In order to represent a cell by a quantifier-free Booleean formula, it may be necessary to split a cell into several disjoint semialgebraic sets. Thus, each cell will be represented in disjunctive normal form, where each literal is a sign condition on a projection polynomial or one of its derivatives.


