# Quasi-Affine Cells { #sec:quasi-affine }

In this section, we develop an algorithm, based on @bgv15, Theorem 3.19, for constructing a CAD whose $2$, $1$, and
$0$-dimensional cells are the graphs of quasi-affine maps. This is the first step to constructing a monotone cylindrical decomposition, as described in @bgv15, Theorem 3.20.

::: {.proposition #bgv-quasi }
[@bgv15, Theorem 3.19]

Let $V_1,\ldots,V_k$ be bounded deﬁnable subsets in $\R^n$ with $\dim (V_i) \le 2$ for each
$1 \le i \le k$.
Then there is a cylindrical cell decomposition of $\R^n$, compatible with each $V_i$, such that every cylindrical cell contained in $V := V_1\cup\ldots\cup V_k$ is the graph of a quasi-affine map.
:::

The following will be proved.

::: { .theorem #bgv-quasi-algorithm }
Let
$F_1,\ldots,F_k$
be quantifier-free Boolean formulas containing $s$ different polynomials $\mathbf{F} = \{ f_1,\ldots, f_s \} \subset
\Z[x_1,\ldots,x_n]$, having maximum degree $d$, such that $F_i, 1\le i \le k$ defines a bounded semialgebraic set $V_i
\subset \R^n$ of dimension at most $2$.

Then there is an algorithm, taking $F_1,\ldots,F_k$ as input, which constructs an $\mathbf{F}$-invariant CAD
$\mathcal{D}$ of $\R^n$ such that each cell $C \subset V_1\cup\ldots\cup V_k$ is a smooth manifold and the graph of a
quasi-affine map.
In particular, $\mathcal{D}$ is compatible with each $V_1,\ldots,V_k$.
This algorithm has complexity
$$
\left(s\left(d+1\right)\right)^{2^{\O(n)}},
$$
which is also an upper bound on the number of cells in the CAD, number of polynomials and their degrees.
:::

## The $2$-dimensional locus

The proof of @bgv15, Theorem 3.19 begins by introducing $W$, the smooth $2$-dimensional locus of $V = V_1 \cup \ldots \cup V_k$.
Since $V$ is a semialgebraic set, it can be represented by a quantifier-free Boolean formula $F$.
$W$ can be computed using the smooth stratification algorithm described in Section \@ref(sec:smooth-strat).
In order to apply the algorithm, consider the sign sets $S_{(\ast_1,\ldots,\ast_s)} \subset \R^n$ of polynomials $f_1,\ldots,f_s$ appearing in the formula $F$, as described in Section \@ref(sec:strat-semialgebraic). Observe that a finite number of these sign-sets $S_1,\ldots,S_m$ form a partition of $V$.
For each $S_i \subset V$, apply the smooth stratification algorithm to obtain a family $(X_{i,1}, \ldots X_{i,n})$ of strata, where each $X_{i,j}$ is a smooth subset of $S_i$ of codimension $j$.
We have $\dim(S_i) \le 2$, since each of the sets in the union $V$ has dimension at most $2$. Hence, every stratum $X_{i,j}$ of codimension $j < n-2$ will be empty.
We obtain the smooth $2$-dimensional locus of $V$ by taking the union of strata of codimension $n-2$. For each stratum,
it is important to keep the set of $n-2$ polynomials defining it, as these will be needed in the next step. We will need
the strata of codimension $n-1$, as each $1$-dimensional cell must also be the graph of a quasi-affine map.

### Exploring an alternative approach { #sec:quasi-projop }

Recall from Section \@ref(sec:cad-construction) that smooth cells can be guaranteed by choosing a certain projection operator.
More precisely, according to @mccallum1998, Theorems 2.2.3 and 2.2.4, if there is a finite number of blow-up points
(i.e., if the set of input polynomials is well-oriented), then the McCallum
projection operator is guaranteed not to fail and will result in a CAD
where all cells are analytic submanifolds (see Definition \@ref(def:analytic-submanifold)).
Since $\dim(V_i) \le 2$ for all $1 \le i \le k$, blow-up points in $\cl(V_i)$ have dimension at most $0$ and the set of
input polynomials is well-oriented (see the Remark after Definition \@ref(def:blow-up-point)).
Hence, the McCallum projection operator is sufficient to produce smooth cells.
Note that the McCallum projection operator can fail if the set of input polynomials is not well oriented.
For our situation, where the input sets have dimension at most two, the CAD will be well-oriented, since blow-ups will
be isolated points.
However, if this condition fails, e..g, if we were to extend this result to input sets of higher dimension, the Lazard projection operator can be substituted, and will also produce smooth cells [@mccallum2019].

Thus, the smooth $2$-dimensional locus of $V$ can be obtained by constructing a CAD, using the McCallum projection operator, which is sign-invariant with respect to all of the polynomials appearing in the defining formulas for $V_1,\ldots,V_k$.
Recall from Definition \@ref(def:cells) that each cell has a binary index $(i_1,\ldots,i_n) \in \{0,1\}^n$ and the sum of elements of this index is equal to the dimension of the cell.
Since cylindrical cells are disjoint and the McCallum projection ensures that they are smooth, the smooth $2$-dimensional locus of $V$ can be found by taking the union of all cells whose binary index sums to $n-2$.

However, we also need a convenient way of defining each cell.
More precisely, for each cell $C \subset \R^n$ of codimension $k$, we would like to find an algebraic set $V \supset C$ defined by $k$ polynomial equations. Although the McCallum projection guarantees smoothness, it does not guarantee that these $k$ polynomial equations will appear in the set of projection factors.
Therefore, we will need to use the smooth stratification algorithm and keep a note of the polynomials $h_1 = 0,\ldots,h_{n-k} = 0$ corresponding to each stratum (see the discussion of @gv1995, Theorem 1 in Section \@ref(sec:strat-basic-formula)).
Using the stratification algorithm also seems cleaner, being the correct tool for the job.
In addition, the bound on the number of strata is singly exponential, while the bound on the number of CAD cells is doubly exponential. An estimate for the number of cells, or the number of strata, with a given dimension is not currently known, but it seems likely that the number of strata will be less than the number of CAD cells.
@gv04, Theorem 3.7 gives a method (which can be turned into an algorithm) for efficiently listing all sign sets associated with a set of polynomials and @bpr2006, Algorithm 14.21 (presented in Proposition \@ref(prp:bpr-qe)) describes how quantifier elimination can be performed in singly exponential time.

In terms of the implementation, we currently use a CAD algorithm to perform emptiness checking. This is because the singly exponential algorithm from Proposition \@ref(prp:bpr-qe) has not yet been implemented.
Thus, using a projection operator which produces smooth cells and gives us the $k$ defining equations for a cell of codimension $k$ would be very appealing.
Only a single recomputation of the initial smooth CAD would be needed, as opposed to multiple calls to the CAD algorithm, which is required for the emptiness check in the stratification algorithm in its current implementation.
In addition, @kremer2020 propose an algorithm, along with its implementation, for refining a CAD to be compatible with some new polynomials. This gives us hope that we may be able to avoid a full re-computation. Investigating whether such a projection operator exists would be an interesting strand of further research.

## Cells as graphs of quasi-affine maps

We now discuss how to obtain quasi-affine cells. A $k$-dimensional cell $C$ is the graph of a quasi-affine map if, for each affine coordinate subspace $L \subset \R^n$, the image of the projection map $\proj_{L}(C)$ is $k$-dimensional if and only if the map $\proj_{L}\vert_C$ is injective (see Definition \@ref(def:quasi-affine)).
In order to satisfy this property, @bgv15, Lemma 3.19 states that the CAD $\cal D$ also needs to be compatible with the
critical points (see Definition \@ref(def:critical-point)), $W_{i}$ and $W_{i,j}$, of projections of $W$ onto one and $2$-dimensional coordinate subspaces $\opspan{x_i,x_j}$ and $\opspan{x_i}$.

Let $W'_k$ be one of the smooth strata of dimension $k$ computed in the previous section, with $k\in \{1,2\}$.
Since $W'_k$ has codimension $n-k$ and is a basic semialgebraic set, its formula contains $n-k$ polynomial equations and, possibly, some inequalities.
Let $h_1,\ldots,h_{n-k}$ be the polynomials from @gv1995, Theorem 1. As discussed in Section
\@ref(sec:strat-basic-formula)), the algebraic set $h_1 = 0, \ldots, h_{n-k} = 0$ has dimension $k$ at every point in $W'_k$.
Consider the Jacobi matrix
$$
J_{\hat{w}}:=\begin{pmatrix}\partial h_{1}/\partial x_{i_{1}} & \ldots & \partial h_{1}/\partial x_{i_{\ell}}\\
\vdots &  & \vdots\\
\partial h_{n-k}/\partial x_{i_{1}} & \ldots & \partial h_{n-k}/\partial x_{i_{\ell}}
\end{pmatrix},
$$
where $\{i_1,\ldots,i_\ell\} \subset \{1,\ldots,n\}$.
Let $w := \{j_1,\ldots,j_{n-\ell}\}$ be the complement $\{ 1 , \ldots, n \} \setminus \{ i_1,\ldots,i_\ell \}$
so that $\hat{w}$ denotes the complement $\{i_1,\ldots,i_\ell\} = \{1,\ldots,n\} \setminus w$.
Regular points of the projection of $W_k'$ onto $\opspan{w}$ are those at which the matrix $J_{w}$ has full rank.
Thus, we can compute the critical points $W'_{i,j}$ of $\projops{x_i,x_j}$ by finding the points at which the Jacobi matrix $J_{\hat{ij}}$ does not have full rank.

Note that, for $W'_{i,j}$, the corresponding $J_{\hat{ij}}$ will be a $((n-2) \times (n-2))$-matrix, so we simply need to find the points at which $\det(J_{\hat{ij}}) = 0$.
On the other hand, $J_{\hat{i}}$ will be an $((n-2) \times (n-1))$-matrix. It will fail to have
full rank if the determinants of all of the $((n-2) \times (n-2))$-minors are zero. Observe that the minors of
$J_{\hat{i}}, i \in \{1,\ldots,n\}$ are the $((n-2)\times (n-2))$-Jacobi matrices
$J_{\hat{ij}}, j \in \{1,\ldots,n\} \setminus \{i\}$. I.e., they will coincide with the square matrices associated with $W'_{i,j}$.
Thus, the CAD should have constant sign on each of the determinants
$$
\det(J_{\hat{ij}}) \text{ for all } 1 \le i < j \le n,
$$
for all $2$-dimensional smooth strata of $V$, whose definition includes $n-2$ polynomial equations.

Now consider the critical points $Z$ of $\projops{x_i,x_j}(W'_1)$, where $W'_1$ is a smooth $1$-dimensional stratum. If
$\dim(Z) = 1$, then every point of $\projops{x_i,x_j}(W'_1)$ is critical as $W'_1$ is smooth. Note that $Z$ may contain
isolated critical points of $\projops{x_i}$ and $\projops{x_j}$.
Otherwise, $\dim(Z) = 0$, so $Z$ is a collection of isolated points $(c_i,c_j)$. $c_i$ is also a critical point of
$\projops{x_i}(W'_1)$ and $c_j$ is also a critical point of $\projops{x_j}(W'_1)$. Therefore, it is sufficient to
consider only critical points of projections onto $1$-dimensional coordinate subspaces. Hence, we only consider Jacobi matrices
$J_{\hat{i}}$ for all $1\le i \le n$, for the $n-1$ polynomials defining $W'_1$. Critical points are those at which their determinants are equal to zero.

\newpage
### Pseudo-code { #sec:quasiaffine-algorithm }

We now present pseudo-code for the quasi-affine part of the algorithm.

::: {.algorithm data-latex="Quasi-Affine CAD"}
$${\cal D} := \textproc{QuasiAffineCad}(F_1,\ldots,F_k)$$

**Input:**

- $F_1,\ldots,F_k$: a quantifier-free Boolean formula defining
$V = V_1 \cup \ldots \cup V_k,$
where $V \subset \R^n$ and $\dim(V_i) \le 2, 1 \le i \le k$.

**Output:**

- $\cal D$: an $\mathbf{F'}$-invariant CAD of $\R^n$ compatible with each $V_1,\ldots V_k$ such that each cell $C
  \subset V$ is the graph of a quasiaffine map, where $\mathbf{F'} \subset \Z[x_1,\ldots,x_n]$ contains all
  polynomials from formulas $F_1,\ldots,F_k$ and, possibly, some additional polynomials which are zero at singular
  points of $V_1\cup \ldots \cup V_k$ and the critical points of projections of $Y_1 \cup \ldots \cup V_k$ onto $1$-
  and $2$-dimensional coordinate subspaces.

\begin{algorithmic}[1]
\Procedure{QuasiAffineCad}{$F_1,\ldots,F_k$}
\State \Comment{stratify the input sets to obtain smooth locus}
\State $(\mathcal{W}_1, \mathcal{W}_2) = \textproc{SmoothTwoLocus}(\{ F_1 \lor \ldots \lor F_k \})$
\State \Comment{$2$-dimensional strata}
\For {each stratum $W'_2 \in \mathcal{W}_2$ and each pair $1 \le i_1 < i_2 \le n$}
    \State\Comment{get the $n-2$ defining polynomials}
    \State $\{ h_1,\ldots,h_{n-2} \} = W'_2$
    \State define the $((n-2) \times (n-2)$ Jacobi matrix
    \begin{equation}
    J_{W'_2,\hat{i_1 i_2}} :=
\begin{pmatrix}\partial h_{1}/\partial x_{j_{1}} & \ldots & \partial h_{1}/\partial x_{j_{n-2}}\\
\vdots &  & \vdots\\
\partial h_{n-2}/\partial x_{j_{1}} & \ldots & \partial h_{n-2}/\partial x_{j_{n-2}}
\end{pmatrix}
\label{eq:jacobi-two}
\end{equation}
    \State compute $\det(J_{W'_2,\hat{i_1 i_2}})$
    \State \Comment{$\det(J_{W'_2,\hat{i_1 i_2}}) = 0$ at critical points of $\projops{i_1,i_2}$}
\EndFor

\State \Comment{$2$-dimensional strata}
\For {each stratum $W'_1 \in \mathcal{W}_1$ and each $1 \le i \le n$}
    \State\Comment{get the $n-1$ defining polynomials}
    \State $\{ h_1,\ldots,h_{n-1} \} = W'_1$
    \State define the $((n-1)\times (n-1))$ Jacobi matrix
  \begin{equation}
  J_{W'_1,\hat{i}} :=
\begin{pmatrix}\partial h_{1}/\partial x_{j_{1}} & \ldots & \partial h_{1}/\partial x_{j_{n-1}}\\
\vdots &  & \vdots\\
\partial h_{n-1}/\partial x_{j_{1}} & \ldots & \partial h_{n-1}/\partial x_{j_{n-1}}
\end{pmatrix}
\label{eq:jacobi-one}
\end{equation}
    \State compute $\det(J_{W'_1,\hat{i}})$
    \Comment{$\det(J_{W'_1,\hat{i}}) = 0$ at the critical points of $\projops{i}$}
\EndFor

\State \Comment{get polynomials appearing defining input sets for the CAD}
\State $\mathbf{F} \gets \textproc{ExtractPolynomials}(\{F_1,\ldots,F_k\}) \subset \Z[x_1,\ldots,x_n]$
\State compute $\mathcal{D} \gets \textproc{ClassicalCad}(\mathbf{F}')$ for
$$
\mathbf{F}' := \mathbf{F} \cup\ \bigcup_{W'_2,1\le i < j \le n} \det\left(J_{W'_2,\hat{ij}}\right) \cup \bigcup_{W'_1, 1
\le i \le n} \det\left(J_{W'_1,\hat{i}}\right),
$$
where $W'_1 \in \mathcal{W}_1$ and $W'_2 \in \mathcal{W}_2$ and $\hat{w}$ denotes the complement $\{1, \ldots, n\} \setminus w$

\State \Return $\mathcal{D}$
\EndProcedure
\end{algorithmic}
:::

Three subroutines are called in the above algorithm.
The first one, $\textproc{SmoothTwoLocus}$, is a wrapper for $\textproc{Stratify}$ from Section \@ref(sec:strat-alg-description).
As described in Section \@ref(sec:strat-semialgebraic), $\textproc{SmoothTwoLocus}$ represents the input set $V = V_1
\cup \ldots \cup V_k$, defined by the quantifier-free Boolean formula $F_1 \lor \ldots \lor F_k$, as a collection of
basic semialgebraic sets so that $\textproc{Stratify}$ can be applied to each of them.
Once the stratification has been computed, the strata of codimension $n-1$ and $n-2$ are collected.
The subroutine returns a pair $(\mathcal{W}_1, \mathcal{W}_2)$, where $\mathcal{W}_k, k \in \{1,2\}$ is a family of
sets of polynomials $W'_k = \{h_1,\ldots, h_{n-k}\} \subset \Z[x_1,\ldots,x_n]$ which can be used to define some
algebraic sets of codimension $n-k$.
The second subroutine, $\textproc{ExtractPolynomials}$, simply returns the set of polynomials appearing in a collection
of quantifier-free Boolean formulas.
Finally, given a set of polynomials $\mathbf{F} \subset \Z[x_1,\ldots,x_n]$, the $\textproc{ClassicalCad}$ subroutine returns an $\mathbf{F}$-invariant CAD of $\R^n$.

## Correctness and complexity

The correctness of Theorem \@ref(thm:bgv-quasi-algorithm) follows from the proof of @bgv15, Lemma 3.19.
Let $\mathcal{W}_1$ and $\mathcal{W}_2$ be the $1$- and $2$-dimensiooal strata computed by the stratification algorithm
from Section \@ref(sec:strat-alg-description) given the input set $V = V_1\cup \ldots \cup V_k$ (computed on line 3 of
the algorithm in Section \@ref(sec:quasiaffine-algorithm)).
These strata clearly form the smooth $2$-dimensional locus of $V$, as required by @bgv15, Theorem 3.19.
Furthermore, @gv1995, Theorem 1 gives us the polynomials $h_1,\ldots,h_{k}$ defining each stratum of codimension
$k$.
The algorithm then computes a classical CAD which has constant sign on the polynomials defining sets $V_1,\ldots,V_k$
and the determinants of matrices $J_{W'_2,\hat{ij}}$ and $J_{W'_1,\hat{i}}$, defined in Equations \@ref(eq:jacobi-two) and \@ref(eq:jacobi-one) respectively.
These determinants are equal to zero at the critical points of projections of $2$- and $1$- dimensional strata $W'_2$
and$W'_1$, which form a partition of $V$.
Thus, $\mathcal{D}$, the CAD output by the algorithm from Section \@ref(sec:quasiaffine-algorithm) is compatible with the
critical points of projections of the smooth $2$-dimensional locus of $V$ onto $1$- and $2$-dimensional coordinate
subspaces.
This completes the construction required by the proof of @bgv15, Lemma 3.19.

### Complexity { #sec:quasi-complexity }

We now analyse the complexity of the algorithm from Section \@ref(sec:quasi-affine-algorithm). Let $V_1,\ldots,V_k \subset
\R^n$ be the family of input sets defined by quantifier-free Boolean formulas $F_1,\ldots,F_k$ which contain $s$
different polynomials having maximum degree $d$.
By the result from Section \@ref(sec:strat-cotmplexity), the smooth stratification step with emptiness checking has complexity
$$
3^{s}\left(s(d+1)\right)^{\O(n)^{2}}.
$$
The critical points of $1$- and $2$- dimensional strata are then computed. This is done by computing determinants of $(n-1)$- and $(n-2)$-dimensional
Jacobi matrices, containing the $n-1$ and $n-2$ polynomial equations which define the strata of codimension $1$ and $2$ respectively.
These polynomials have maximum degree $(d + 1)^{2}$.
In order to estimate the maximum degree of polynomials appearing in the Jacobi determinant of a $(k \times k)$-matrix,
suppose that elementary row operations -- swapping two rows, multiplying a row by a number and adding one row to another
-- will be used to convert the matrix into row echelon form.
Then the determinant can be computed by multiplying the elements on the main diagonal of the row echelon matrix
together.
Note that the complexity of performing these row operations to transform the matrix into row echelon form is
$\O\left(n^2\right)$.
Elementary row operationns do not change the upper bound on degree. For the determinant, multiplying $k$ polynomials of maximum degree $d$ will result in a polynomial of maximum degree $kd$. Thus, the maximum degree of the determinant of the $((n-2)\times (n-2))$-matrix will be $(n-2)(d + 1)^{2}$ and the $((n-1) \times (n-1))$-matrix will be $(n-1)(d + 1)^{2}$. These are both bounded from above by
$$
n (d + 1)^{2}.
$$

For the critical points of $\projops{x_i}, 1 \le i \le n$, there will be $n$ Jacobi determinants, and for $\projops{x_i,x_j}, 1 \le i < j \le n$, there will be $(n-1) + (n-2) + \cdots + 1 = \tfrac{1}{2} (n-1)n$, which is asymptotically the same as $n^2$.
According to Section \@ref(sec:strat-complexity), the smooth stratification algorithm will produce at most $s^n (d+1)^2$. The bound on the number of strata of each codimension is not known, but the total number of strata is, of course, an upper bound. Therefore, there will be at most $n \left(s^n (d+1)^2\right)$ additional polynomials.

A classical CAD, having constant sign on the $s$ input polynomials along with the $n \left(s^n (d+1)^2\right)$ Jacobi determinants, which have maximum degree $n(d + 1)^{2}$, is then constructed.
According to Proposition \@ref(prp:collins) (@bpr2006, Algorithm 11.2), classical CAD has complexity
$$
\left(s'd'\right)^{\O(1)^{n}},
$$
where $s'$ is the number of input polynomials and $d'$ their maximum degree.
Using the bounds obtained from the application of smooth stratification, we get
$$
\left(\left(s+n\left(s^{n}(d+1)^{2}\right)\right)n\left(d+1\right)^{2}\right)^{\O(1)^{n}},
$$
which can be simplified to
$$
\left(n s^n \left(d+1\right)\right)^{\O(1)^n}.
$$
Since the expression $n^{\O(1)^{n}}$ can be simplified to $2^{\O(1)^{n}}$ we get an upper complexity bound, for constructing a quasi-affine CAD, of
$$
\left(s(d+1)\right)^{\O(1)^{n}}.
$$
By Proposition \@ref(prp:collins), this is also an upper bound on the number of cells, number of polynomials defining the CAD and their maximum degree.

Adding the stratification step, we get a total complexity of
$$
3^{s}\left(s(d+1)\right)^{\O(n)^{2}}
+ \left(s(d+1)\right)^{\O(1)^{n}},
$$
which is bounded from above by the doubly exponential CAD computation, leading to a complexity upper bound of
$$
\left(s(d+1)\right)^{\O(1)^{n}}.
$$

