# Monotone Cells

Now we have a CAD $\cal D$ such that each 2-dimensional cell is the graph of a quasi-affine map, let us return to [@bgv15 Theorem 3.20] and discuss how to obtain monotone cells. 

::: {.definition #sub-cad}
Let $\cal D$ be a CAD of $\R^n$ and suppose that $c = \{ x_1 = c_1,\dots,x_k = c_k \}$ is a $0$-dimensional section cell in the decomposition induced by $\cal D$ on $\R^k$. 
By [@bgv15 Remark 3.8], the set of all cells of $\cal D$ contained in the effing coordinate subspace 
$$
\{ x_1=c_1,\dots,x_k=c_k \}
$$
forms a cylindrical decomposition of $\R^{n-k}$. This decomposition will be called the *sub-decomposition* of $\cal D$ above $c$, and $c$ the *base cell* of the sub-decomposition. 
:::

The construction proceeds by induction on $n$. 

- The base case, $n=1$ is straightforward, since $(0)$ and $(1)$-cells are already monotone. 

- When $n>1$, consider each cell $C$ of $\cal D$ and let $C'' := \proj op{1}(C)$

  - If $\dim(C'') = 0$, apply the inductive hypothesis to the sub-decomposition of $\cal D$ above $C''$.
  - Otherwise, $C$ has index $\{1,i_2,\dots,i_n\} \in \{0,1\}^n$. Let $\alpha$ be the smallest among $\{2,\dots,n\}$ such that $i_\alpha = 1$. 
    Then $C' := \proj op{\alpha}(C)$ is a 2-dimensional sector cell and $C$ is the graph of a quasi-affine map 
    $$
    \mathbb{f} = (f_1,\dots,f_{n-2}) : \opspan{x_1,x_\alpha} \to \opspan{x_2,\ldots,x_{\alpha - 1}, x_{\alpha+1},\ldots,x_n}.
    $$
    Since $\mathbb{f}$ is quasi-affine, each component $f_j : \opspan{x_1,x_\alpha} \to \opspan{x_j}$ is quasi-affine, too. 

    Let $X \subset \opspan{x_1,x_\alpha}$. By [@bgv15, Lemma 3.18], there exists a refinement of the CAD of $\opspan{x_1,x_\alpha}$, obtained by intersecting $X$ with straight lines and half-planes of the kind 
    $$
    \{x_1 < c\}, \{x_1 = c\}, \{x_1 > c\}
    $$
    where $c \in \R$, such that $X$ is a union of semi-monotone sets $B$ and $f_j\vert_B$ is a monotone function.
    By [@bgv15 Lemma 3.11], refinements of this kind preserve the cylindrical structure of $\cal D$.

## Two-dimensional semi-monotone sectors

::: {.theorem #bgv-monotone}
[@bgv15, Lemma 3.18]

Let $X \subset \R^2$ be an open, bounded set and $f : X \to \R$ be a quasi-affine function. 
Then there is a cylindrical decomposition of $\R^2$ compatible with $X$, obtained by intersecting $X$ with straight lines $$\{x_1 = c\}$$ and half-planes $$\{x_1 < c\},\{x_1 > c\}$$ such that the restriction $f\vert_B$ for every cell $B \subset X$ is a monotone function. 
:::

### Two-dimensional semi-monotone sets {#semi-monotone-sets}

The proof of Theorem \@ref(thm:bgv-monotone) proceeds in two stages: first, $X \subset \opspan{x_1,x_\alpha}$ is refined such that each $Y \subset X$ is a semi-monotone set. 
Consider the intersection $X \cap \{x_1 = c\}$ for all $c\in \R$. This intersection is a finite union of pairwise disjoint intervals. Let ${\cal I} (c)$ be the family of these intervals associated with the point $c$. Define 
$$
\gamma := \{ (x_1,x_2) \in \R^2 \mid x_2 \text{ is an endpoint of an interval in } {\cal I}(x_1) \}.
$$

:::{.lemma #gamma-top-bottom}
Let $C$ be a $(1,0,\ldots,0,1)$-cell and $X := \projops{x_1,x_\alpha} (C)$. Then 

1. $X$ is a cylindrical sector cell in $\R^2$.
1. The family ${\cal I}(C)$ is either empty or contains a single open interval for all $c\in \R$.
1. $\gamma$ consists of the union of the top and bottom of $X$, each of which (if non-empty) is the graph of a continuous definable function.
:::

::: {.proof}
Let $X' := \projop{1}(C)$ and $C' := \projop{\alpha-1}(C)$. 
Observe that $X'$ is a $(1)$-cell and $C'$ is a $(1,0,\ldots,0)$-cell.
By definition 
$$
C = \{ (\mathbf{x},t) \mid \mathbf{x} \in C', f(\mathbf{x}) < t < g(\mathbf{x})\}
$$
where $f,g : \R^{\alpha - 1} \to \R$ are continuous definable functions such that $f(\mathbf{x}) < g(\mathbf{x})$ for all $\mathbf{x} \in C'$.

Since $C'$ is a $(1,0,\ldots,0)$-cell, it can be viewed as the graph of a continuous definable map 
$$
\mathbf{h} = (h_1,\ldots,h_{\alpha - 2}) : X' \to \opspan{x_2,\ldots,x_{\alpha-1}}.
$$
$C$ can therefore be rewritten in terms of only $x_1$ and $t$.
$$
C := \{ (x_1,\mathbf{h}(x_1),t) \mid x_1 \in X', f(x_1,\mathbf{h}(x_1)) < t < g(x_1,\mathbf{h}(x_1))\}.
$$

Define
\begin{align}
\phi &:\> C'' \to \R & \psi &:\> C'' \to \R\\
\phi(x_1) &= f(x_1,\mathbf{h}(x_1)) & \psi(x_1) &= g(x_1,\mathbf{h}(x_1))

(\#eq:phi-psi)
\end{align}

Observe that $\phi$ and $\psi$ are continuous, definable functions. By the definition of $f$ and $g$, we also have $\phi(x_1) < \psi(x_1)$ for all $x_1\in X'$. 

Thus, we can write
\begin{equation}
X = \{ (x_1,t) \mid x \in X', \phi(x_1) < t < \psi(x_1) \}.

(\#eq:cell-x)
\end{equation}
It is clear that $X$ is a cylindrical sector cell.
By the definition of sector cell, the bottom of $X$ is the graph of $\phi$ and the top of $X$ is the graph of $\psi$. 

Now consider the family
$$
{\cal I}(c) := \{ t \mid \phi(c) < t < \psi(c) \}.
$$
Using Equation \@ref(eq:cell-x), it is easy to deduce that if $c \in X'$ then ${\cal I}(c)$ contains a single open interval. On the other hand, if $c \not \in X'$, ${\cal I}(c)$ is clearly empty.  

It follows that $\gamma$ consists of the points of the top and bottom of $X$, which are the graphs of functions $\psi$ and $\phi$ respectively. 
:::

The refinement is achieved by finding a set of real numbers 
$$
(c_1,\ldots,c_t)
$$
such that, for each $1 \le i < t$,
$$
X \cap \{c_i < x_1 < c_i+1\}
$$
is a semi-monotone set. By [@bgv13, Theorem 1.7], this can be achieved by ensuring that 
$$
\gamma \cap \{ c_i < x_1 < c_{i+1}\}
$$ 
contains only monotone curve intervals.

Applying Lemma \@ref(lem:gamma-top-bottom) to $C$, we obtain continuous definable functions $\phi,\psi : X' \to \R$ defining the bottom, $X_B$, and top, $X_T$, of $X$ respectively. 

Let $$
(c_1,\ldots,c_t)
$$
be the critical points of functions $\phi$ and $\psi$. Then, for all $1 \le i < t$, $\phi$ (resp $\psi$) is either strictly increasing in, strictly decreasing in, or independent of $x_1$ on the interval $(c_i, c_{i+1})$. 

### Finding the critical points of $\phi$ and $\psi$ {#sec:lagrange-refinement}

We now discuss how to find these critical points. 

Let 
\begin{equation}
{\cal A} = ({\cal A}_1,\ldots,{\cal A}_n),

(\#eq:proj-fac-set)
\end{equation}
where ${\cal A}_i \subset \Z[x_1,\ldots,x_i]$, be the projection factor set for $\cal D$. For convenience, we say that $g(\mathbf{x}) = 0$ for some $g \in A_k$ and $\mathbf{x} \in \R^n$, such that $k < n$, if $g(\projop{k}(\mathbf{x})) = 0$.
Let $C$ be a $(1,0,\ldots,0,1)$-cell of the decomposition induced by $\cal D$ on $\R^{\alpha}$ and consider the $(1,0,\ldots,0)$-cell
$$
C' := \projop{\alpha - 1}(C)
$$ 
of the decomposition induced by $\cal D$ on $\R^{\alpha - 1}$. Observe that
$$
\projop{1}(C) = (a,b) \subset \R \cup \{-\infty, \infty\}
$$
and, since $C'$ is a section cell, there exist polynomials 
$$
g_2 \in {\cal A_2},\ldots,g_{\alpha - 1} \in {\cal A_{\alpha - 1}}
$$ such that $g_i(\mathbf{x}) = 0$ for all $1\le i \le \alpha - 1$ and $\mathbf{x} \in (C')$. 
Therefore, there exists a one-dimensional algebraic variety 
$$
V' := \left\{ g_2(\mathbf{x}) = 0, \ldots, g_{\alpha - 1}(\mathbf{x}) = 0 \right\}
$$ 
such that $C' \subset V'$. 

Now consider the top of $C$, denoted by $C_T$. 
By definition, if $C$ is not bounded from above, then $C_T$ does not exist. Otherwise, $C_T$ is the graph of a continuous definable function $h : C' \to \R$. 
In the first case, there is nothing to do, since $C_T$ can be thought of as being independent of $x_\alpha$.
In the second case, $C_T$ can be written as
\begin{equation}
\{ (x_1,\ldots,x_\alpha) \mid a < x_1 < b, g_2(x_1,\ldots,x_{\alpha - 1}) = 0, \ldots, g_{\alpha - 1}(x_1,\ldots,x_{\alpha - 1}) = 0, x_\alpha = h(x_1,\ldots,x_{\alpha - 1}) \}.

(#eq:c-alpha-top)
\end{equation}
By **TODO** $C_T$ is $C^\infty$ smooth, therefore $h$ is a differentiable function everywhere in $C'$. 

This representation lends itself naturally to the problem of Lagrange multipliers. 

::: {.proposition #lagrange-multipliers}
Let $f : \R^n \to \R$ and $g_1,\ldots,g_k : \R^n \to \R$ be continuous functions with continuous first partial derivatives. 
Local maxima and minima of $f$, subject to the constraints $g_1=0,\ldots,g_k=0$ can be found by computing the critical points of the function
$$
\mathcal{L}(\mathbf{x}, \lambda_1,\ldots,\lambda_k) = f(\mathbf{x}) - \lambda_1 g_1(\mathbf{x}) - \cdots - \lambda_k g_k(\mathbf{x}),
$$
where $\mathbf{x} \in \R^n$ and $(\lambda_1,\ldots,\lambda_k) \in \R^k$ are new variables. 

Critical points can be found by solving the system of equations
\begin{equation}
\dfrac{\partial f}{\partial x_i} - \lambda_1 \dfrac{\partial g_1}{\partial x_i} - \cdots - \lambda_k \dfrac{\partial g_k}{\partial x_i}= 0,

(\#eq:lagrange)
\end{equation}
where $1\le i \le n-1$,

for $\lambda_1,\ldots,\lambda_k$. 
:::

::: {.remark #lagrange-solve}
Using variables $(x_1,\ldots,x_{\alpha-1})$, constraints $g_2,\ldots,g_{\alpha - 1}$ and function $h$ from Equation \@ref(eq:c-alpha-top), the system from Equation \@ref(eq:lagrange) can be written in matrix form as follows.
$$
\begin{pmatrix}\dfrac{\partial g_{2}}{\partial x_{1}} & \cdots & \dfrac{\partial g_{\alpha-1}}{\partial x_{1}}\\
\vdots &  & \vdots\\
\dfrac{\partial g_{2}}{\partial x_{\alpha-1}} & \cdots & \dfrac{\partial g_{\alpha-1}}{\partial x_{\alpha-1}}
\end{pmatrix}\begin{pmatrix}\lambda_{1}\\
\vdots\\
\lambda_{\alpha-2}
\end{pmatrix}=\begin{pmatrix}\dfrac{\partial h}{\partial x_{1}}\\
\vdots\\
\dfrac{\partial h}{\partial x_{\alpha-1}}
\end{pmatrix}
$$

It is clear that, if a solution exists, then the last column 
$\left(\tfrac{\partial h}{\partial x_{1}},\ldots, \tfrac{\partial h}{\partial x_{\alpha-1}}\right)^T$
will be a linear combination of the first $\alpha - 1$ columns (in $g_2,\ldots,g_{\alpha - 1}$). 
Hence, optimal values for $(x_1,\ldots,x_{\alpha-1})$ exist and satisfy
\begin{equation}
\det\begin{pmatrix}\dfrac{\partial g_{2}}{\partial x_{1}} & \cdots & \dfrac{\partial g_{\alpha-1}}{\partial x_{1}} & \dfrac{\partial h}{\partial x_{1}}\\
\vdots &  &  & \vdots\\
\dfrac{\partial g_{2}}{\partial x_{\alpha-1}} & \cdots & \dfrac{\partial g_{\alpha-1}}{\partial x_{\alpha-1}} & \dfrac{\partial h}{\partial x_{\alpha-1}}
\end{pmatrix}=0.

(\#eq:jacobi-det)
\end{equation}
::: 

Equation \@ref(eq:jacobi-det) gives a direct formula for formula to solve Equation \@ref(eq:lagrange) for $x_1,\ldots,x_{\alpha - 1}$. Refinement points $(c_1,\ldots,c_t)$ are the $x_1$-coordinates of these solutions. 

Since $C_T$ is a section cell, there exists a polynomial $g_\alpha \in {\cal A}_\alpha$ such that $$
C_T := \{ \mathbf{x} \in \R^\alpha \mid \projop{\alpha - 1}(\mathbf{x}) \in C', g_\alpha(\mathbf{x}) = 0 \}.
$$ Thus, there exists an algebraic variety 
\begin{equation}
V := \left\{ g_2(\mathbf{x}) = 0, \ldots, g_{\alpha-1}(\mathbf{x}) = 0 g_\alpha(\mathbf{x}) = 0 \right\}

(\#eq:variety-v)
\end{equation}
such that $C_T \subset V$, where $g_2,\ldots,g_{\alpha - 1}$ are the same polynomials appearing in Equation \@ref(eq:c-alpha-top).

Note that $g_\alpha \in \Z[x_1,\ldots,x_\alpha]$, while $h$ from Equation \@ref(eq:jacobi-det) is expected to be a continuous differentiable function from $\R^{\alpha - 1} \to \R$. 
We need to compute derivatives of the implicit $g_\alpha$. I.e., 
\begin{equation}
\dfrac{d x_\alpha}{d x_i} = \dfrac{\partial g_\alpha / \partial x_i}{\partial g_\alpha / \partial x_\alpha}

(\#eq:total-deriv)
\end{equation}
for $1\le i \le \alpha - 1$. 
Let $J_T$ be the determinant of the matrix of partial derivatives from Equation \@ref(eq:jacobi-det) with each $\partial h / \partial x_i, 1 \le i \le \alpha - 1$ replaced with $d x_\alpha / d x_i$ from Equation \@ref(eq:total-deriv). Observe that the denominator of $\partial h / \partial x_i$, for all $1 \le i \le \alpha - 1$, is equal to 
$$d_T := \partial g_\alpha / \partial x_\alpha,$$ 
so the last column of the matrix can be written as
$$
\dfrac{1}{d_T} \left( \partial g_{\alpha} / x_1 , \ldots , \partial g_{\alpha} / x_{\alpha - 1}\right)^T.
$$
Thus, the determinant
$$
J_T = \frac{1}{d_T} J'_T,
$$
where $J'_T$ is the matrix from Equation \@ref(eq:jacobi-det) with the $\partial h / \partial x_i$ replaced with $\partial g_\alpha / \partial x_i$ for $1\le i \le \alpha - 1$. I.e., 
\begin{equation}
\det\begin{pmatrix}\dfrac{\partial g_{2}}{\partial x_{1}} & \cdots & \dfrac{\partial g_{\alpha-1}}{\partial x_{1}} & \dfrac{\partial g_\alpha}{\partial x_{1}}\\
\vdots &  &  & \vdots\\
\dfrac{\partial g_{2}}{\partial x_{\alpha-1}} & \cdots & \dfrac{\partial g_{\alpha-1}}{\partial x_{\alpha-1}} & \dfrac{\partial g_\alpha}{\partial x_{\alpha-1}}
\end{pmatrix}=0.

(\#eq:jacobi-det-2)
\end{equation}

Observe that $J_T$ is a rational function: a fraction in which the numerator and denominator are both polynomials. $\mathbf{x} \in \R^{\alpha - 1}$ is a solution of this rational function if and anly if $J'_T(\mathbf{x}) = 0$ and $d_T(\mathbf{x}) \ne 0$. Thus, solutions of the system $$
\{ J'_T = 0, d_T \ne 0 \}
$$ should be found. 
Observe that this is a semialgebraic set, since 
$ \{ d_T(\mathbf{x}) \ne 0 \} \leftrightarrow \R^{\alpha - 1 } \setminus \{ d_T(\mathbf{x}) = 0 \} $.
Note that, when $\deg(d_T) = 0$, $d_T$ is a constant and therefore has no solutions. Thus, the condition $d_T = 0$ can be dropped.

Repeating this process to obtain $J'_B$ and $d_B$, if sector cell $C$ is bounded from below, we have a set of polynomial equations 
\begin{equation}
\{ g_2,\ldots,g_{\alpha-1}, J'_B, J'_T \},

(#eq:lagrange-solve)
\end{equation}
and inequalities
\begin{equation}
\{ s_1 g_{1,1} > 0, \ldots, s_\ell g_{1,\ell} > 0, d_B \ne 0, d_T \ne 0 \}

(#eq:lagrange-solve-ineqs)
\end{equation}
where $\{ g_{1,1},\ldots,g_{1,\ell} \} \subset \Z[x_1]$ are polynomials from ${\cal A}_1$ and $s_1,\ldots,s_\ell \in \{-1,1\}$ such that $$
x \in X' \leftrightarrow s_1 g_{1,1}(x) > 0 \land \ldots \land s_\ell g_{1,\ell}(x) > 0.
$$
We can easily find pairs $(s_j, g_{1,j}) \in \{-1,1\} \times {\cal A}_1$ by considering the sign of the sample point $c$ of $X'$ on each polynomial $g_{1,j} \in {\cal A}_1$. 

- If $g_{1,j} > 0$, then $s_j = 1$. 
- If $g_{1.j}(c) < 0$, then $s_j = -1$. 
- The final case, $g_{1,j}(c) = 0$, is impossible since an irreducible univariate polynomial cannot be zero over an interval.
We want to find $x_1$-coordinates of the roots of polynomials from Equation \@ref(eq:lagrange-solve) subject to the constraints from Equation \@ref(eq:lagrange-solve-ineqs). 

CAD can, of course, be used to do this, since we are really solving the quantifier elimination problem
$$
\exists x_2,\ldots,x_{\alpha - 1},x_\alpha P(x_1,\ldots,x_\alpha)
$$ where
\begin{align}
P(x_1,\ldots,x_\alpha) = & s_1 g_{1,1}(x_1) > 0 \land \ldots \land s_\ell g_{1,\ell}(x_1) > 0 
(\#eq:lagrange-solve-qe-ineqs) \\
\land & g_2(x_1,x_2) = 0 \land \ldots \land g_{\alpha - 1}(x_1,\ldots,x_{\alpha - 1} = 0 
(\#eq:lagrange-solve-qe-constraints) \\
\land & d_B(x_1,\ldots,x_\alpha) \ne 0 land d_T(x_1,\ldots,x_\alpha) \ne 0 
(\#eq:lagrange-solve-qe-denominators) \\
\land & ( J'_B(x_1,\ldots,x_{\alpha - 1} = 0 \lor J'_T(x_1,\ldots,x_{\alpha - 1}) = 0 ).
(\#eq:lagrange-solve-qe-jacobis) \\
\end{align}
Computing the projection onto $\R^1$ of polynomials $\{g_2,\ldots,g_{\alpha - 1} J'_B, J'_T \}$ from Equations \@ref(eq:lagrange-solve-qe-constraints) and \@ref(eq:lagrange-solve-qe-jacobis), a system
$$
\cal{F} := \{ f_1=0 ,\ldots,f_r=0 \} \subset \Z[x_1]
$$
is obtained, whose real roots include the refinement points $(c_1,\ldots,c_t)$.
Let ${\cal E} \subset \Z[x_1]$ be the set of polynomials obtained by computing the projection onto $\R^1$ of $\{ d_B, d_T \}$ (from Equation \@ref(eq:lagrange-solve-qe-denominators)) and 
$${\cal G} := \{ s_1 g_{1,1}, \ldots, s_\ell g_{1,\ell} \}
$$
from Equation \@ref(eq:lagrange-solve-qe-ineqs).
$(c_1,\ldots,c_t$ can be found by computing the real roots of $\cal F$ subject to the inequalities $\cal G$, then discarding those such that a polynomial in $\cal E$ is zero.

> In the implementation `IPFSFB` is used, to compute a "finest square-free basis" of polynomials in $\cal F$. 
> 
> - this was just copying from Brown's `CONSTRUCT` function. it returns a list of real roots in the form $[(M,J),...]$ where $M$ is the minimal polynomial and $J$ the isolating interval. It also computes multiplicities, which we don't need.
> - in fact, why do we even need a squarefree basis at all. should find out which is the most efficient algorithm from saclib, of squarefree basis or the real root finding algorithms. maybe do some discussion on this. 

It is clear that $(c_1,\ldots,c_t)$ lie in an open interval $X = (a,b) \subset \R \cup \{ -\infty, \infty \}$. Thus, rather than using strict inequalities from Equation \@ref(eq:lagrange-solve-qe-ineqs), we could find the roots of $\cal F$ in the interval $(a,b)$. 

Each real root will be represented by a pair
$$
c_i := (m_1,J_1)
$$
where $c_i$ is the unique root of the polynomial $m_i \in \Z[x_1]$ in the (left-open right-closed) isolating interval $J_i$. 
Note that $\cal B$ contains only algebraic numbers and roots will appear in ascending order.

### Working with sub-decompositions above a 0-cell { #sec:sub-cad }

Note that we are working in a sub-decomposition $\cal D$ of $\R^{k+n}$ above a $0$-cell $\mathbf{c}$ of $\R^k$ ($k \ge 0$). Therefore the polynomials appearing in Equation \@ref(eq:variety-v) are actually in $\Z[y_1,\ldots,y_k][x_1,\ldots,x_n]$. 
From a polynomial $f \in \Z[y_1,\ldots,y_k][x_1,\ldots,x_n]$, a polynomial $g := f(\mathbf{c}) \in \A[x_1,\ldots,x_n]$ can be obtained by evaluating $f$ at $\mathbf{c}$. Evaluated polynomials $g$ define the sub-cad of $\R^n$ above $\mathbf{c}$ because $\mathbf{c}$ is a $0$-cell. 

Note that, since $\mathbf{c}$ is an algebraic number, $g$ has algebraic coefficients. Since roots of $g$ are algebraic numbers, there exists a polynomial $h \in \Z[x_1,\ldots,x_n]$ such that, $g(\mathbf{x}) = 0$ if and only if $h(\mathbf{x}) = 0$ for all $\mathbf{x} \in \R^n$. A method for obtaining the polynomial $h$ with integer coefficients is now described. 

1. If $f$ is independent of all $y_1,\ldots,y_k$, there is nothing to do, just set $h := f$. Otherwise, $f$ depends on at least one of $y_1,\ldots,y_k$.

1. If $\mathbf{c}$ is rational, then $g = f(\mathbf{c})$ has coefficients in $\Q$. There exists a non-zero $a \in \Z$ such that $h := a g$ has integer coefficients and the same roots as $g$. 

1. Otherwise, $\mathbf{c}$ is not rational. Then $f(\mathbf{c})$ has coefficients in $\A$. There exists an algorithm, which takes $g$ as input and returns a polynoial $h \in \Z[x_1,\ldots,x_n]$ such that $g(\mathbf{x}) = 0$ if and only if $h(\mathbf{x}) = 0$ for all $\mathbf{x} \in \R^n$. 

::: {.remark}
Let $f \in \Q[x_1,\ldots,x_n]$ be a polynomial such that
$$
f(x_1,\ldots,x_n) = \dfrac{a_1}{b_1} m_1 + \cdots + \dfrac{a_k}{b_k} m_k
$$
where $m_i = x_1^{d_{i,1}} \cdots x_n^{d_{i,n}}$ for $1 \le i \le k$ is a monomial in $x_1,\ldots,x_n$.

Let $M := \lcm(b_1, \ldots, b_k)$ be the least common multiple of denominators and construct
$$
g(x_1,\ldots,x_n) = M f(x_1,\ldots,x_n) = \dfrac{M a_1}{b_1} m_1 + \cdots + \dfrac{M a_k}{b_k} m_k.
$$
Each coefficient in $g$ will be an integer number since $M$ is divisible by all $b_1,\ldots,b_k$ and polynomials $f$ and $g$ have the same roots.
:::

::: {.definition #norm}
Let $K$ be a field and $L$ a finite (algebraic) extension of $K$. 
The field $L$ can be thought of as a finite dimensional vector space over $K$. 

Consider $f$ and $m$ as polynomials in $\Q[x_1,\ldots,x_n,x_\alpha]$. compute the resultant of $f$ and $m$ to obtain a polynomial in $\Q[x_1,\ldots,x_n]$. somehow this gives us the norm of an algebraic polynomial. 

:::

::: {.remark}
Let $f \in \A[x_1,\ldots,x_n]$ be a polynomial such that
$$
f(x_1,\ldots,x_n) = a_1 m_1 + \cdots + a_k m_k
$$
where $m_i = x_1^{d_{i,1}} \cdots x_n^{d_{i,n}}$ is a monomial in $x_1,\ldots,x_n$ and $a_i$ is an element of $\Q(\alpha)$ for $1 \le i \le k$.

Let $m \in \Z[\alpha]$ be the minimal polynomial for $\Q(\alpha)$. $f$ can be written as a polynomial in $\Q[x_1,\ldots,x_n,\alpha]$ and $m$ can be viewed as a polynomial in $\Z[x_1,\ldots,x_n,\alpha]$ which is independent of all $x_1,\ldots,x_n$. Compute
$$
g := \res_\alpha (f,m)
$$
to obtain a polynomial in $\Q[x_1,\ldots,x_n]$. The property that $f(\mathbf{x}) = 0$ if and only if $g(\mathbf{x}) = 0$ follows from the following property of resultants:

> Let $I = \langle f, m \rangle$ be the ideal generated by polynomials $f, m \in K[x_1,\ldots,x_n][\alpha]$, where $K$ is an algebraically closed field. If at least one of $f$ and $m$ is monic, then
>$$
\res_\alpha (f,m) \in I \cap R.
>$$

It follows that $\mathbf{x} \in K^n$ is a common zero of the elements of $I \cap R$ if and only if it is a zero of $\res_\alpha(f,m)$.

**TODO** this property came from the wiki page on resultants. does it need proving?
:::

## Two-dimensional monotone sections

Recall $X := \projops{x_1,x_\alpha}(C)$ and let $(c_1,\ldots,c_r)$ be the refinement points computed in the previous section such that 
$$
Y := \{ c_i < x_1 < c_{x+1}\} \cap X,
$$
for some $1 \le i \le r$, is a two-dimensional semi-monotone set. 
Let us return to [@bgv15, Theorem 3.18] to further refine $Y$ such that every two-dimensional section cell is a monotone cell.

Let $f_j : Y \to \opspan{x_j}$ be a component of the quasi-affine map $\mathbf{f} : X \to \R$. Since $\mathbf{f}$ is quasi-affine, each component of $\mathbf{f}$ is quasi-affine and the restriction of component $f_j$ to $Y$ is quasi-affine since $Y \subset X$. 
Hence, $f_j$ is either strictly increasing in, strictly decreasing in, or independent of each variable $x_1, x_\alpha$. 
In addition, the restriction $f\vert_{Y \cap \{x_\alpha = c\}}$ for any $c \in \R$ is either strictly increasing in, strictly decreasing in, or independent of $x_\alpha$. 
We will compute a refinement of $Y$ such that $f_j\vert_Y$ is monotone, each $B \subset Y$ in the refinement. 
As before, only refinements of the kind 
$$
\{ x_1 < c \}, \{ x_1 = c \}, \{ x_1 > c \},
$$
$c \in \R$, which preserves both the cylindrical structure and existing monotone cells will be performed. 

### Case 1: $2 \le j \le \alpha - 1$

::: {.lemma #one-dim-qa-is-monotone}
Let $Y \subset \R^n$ be the graph of a quasi-affine map
$$
\mathbf{f} : (a,b) \to \R^{n-1}
$$ 
such that $(a,b) \subset \R$. Then $Y$ is a monotone cell. 
:::

::: {.proof}
It is clear that
$$
\dim(Y) = 1.
$$
Hence, we need to show that $Y$ is either strictly increasing in, strictly decreasing in, or independent of $x_i$ for all $1\le i \le n$.
Consider the projection map $\projops{x_i} : \R^n \to \opspan{x_i}$. 

Suppose that the restriction
$$
\projops{x_i}\vert_Y
$$
is injective, Then it is clear that the image $\projops{x_i}(Y)$ is $1$-dimensional, since $Y$ itself is $1$-dimensional. On the other hand, suppose that the image
$$
\projops{x_i}(Y)
$$ 
is one-dimensional, then it is clear that $\projops{x_i}\vert_Y$ is injective if $\mathbf{f}$ is either strictly increasing in, strictly decreasing in, or independent of $x_i$. It follows that $\mathbf{f}$ is a monotone map, therefore its graph, $Y$, is a monotone cell.
:::

Suppose that $2 \le j \le \alpha - 1$. 
Since
$$
\projops{x_j,x_\alpha}(C)
$$
is one-dimensional, connected and the graph of a quasi-affine map, it follows from Lemma \@ref(lem:one-dim-qa-is-monotone) that $\projops{x_j,x_\alpha}(C)$ is a monotone cell and $f_j\vert_Y$ is already a monotone function. No refinement is needed. 

### Case 2: $\alpha + 1 \le j \le n$

Now suppose that $\alpha + 1 \le j \le n$.
By [@bgv13, Theorem 3], if functions $$\inf_{x_\alpha} f_j : \opspan{x_1} \to \opspan{x_j} \text{ and } \sup_{x_\alpha} f_j : \opspan{x_1} \to \opspan{x_j}$$ are monotone, then $f_j$ itself is monotone. 
Hence, we need to find refinement points
$$
\{ b_1,\ldots,b_r \} \subset (c_i,c_{i+1})
$$
such that, for each $1\le \ell < r$, the restrictions of both $\inf_{x_\alpha} f_j$ and $\sup_{x_\alpha} f_j$ to $B := \{ b_\ell < x_1 < b_{\ell + 1} \}$ are monotone.

Consider $$
Z := \projops{x_1,x_j}(C).
$$
If $\dim(Z) < 2$, then it is clear that $\dim(Z) = 1$, because 
$$
Y' := \projop{1}(C)
$$ is one-dimensional.
It follows that $\inf_{x_\alpha} f_j$ and $\sup_{x_\alpha} f_j$ coincide. Since $Z$ is one-dimensional, connected and the graph of a quasi-affine map, Lemma \@ref(lem:one-dim-qa-is-monotone) implies that $f_j$ is already monotone and no refinement is needed. 

On the other hand, if $\dim(Z) = 2$, since $\mathbf{f}$ is quasi-affine, $\projops{x_1,x_j}\vert_C$ is injective. 
Let $Z_T$ be the graph of $\sup_{x_\alpha} f_j$. Despite the notation, $Z_T$ is not necesarily the top of $Z$. In particular, $Z_T$ may have non-empty intersection with $Z$. 
Since semialgebraic sets are closed under intersection and projection, there exist points 
$$\{b_1,\ldots,b_k\} \subset (c_i,c_{i+1})
$$ such that for all $1 \le i < k$ $$
Z^{b_i,b_{i+1}}_T := Z_T \cap \{ b_i < x_1 < b_{i+1} \}
$$
is either a subset of $Z$ or is disjoint from $Z$. 
First suppose that $Z^{b_i,b_{i+1}}_T \subset Z$ for some $1 \le i < k$. 
In this case, $Z$ is not bounded from above, so $\sup_{x_\alpha} f_j \vert_{\{ b_i < x_1 < b_{i+1} \}}$ is independent of $x_1$ and is therefore already monotone.
On the other hand, suppose that $Z^{b_i,b_{i+1}}_T \cap Z = \emptyset$.
In this case, $Z^{b_i,b_{i+1}}_T \subset \projops{x_1,x_j}(C_T)$. 
If there exists a point $b \in (b_i,b_{i+1})$ such that $\projops{x_1,x_j}(C_T) \cap \{x_1 = b\} \cap Z \neq \emptyset$, 
then it is  clear that $C_T \cap \{ b_i < x_1 < b_{i+1} \}$ is not the graph of a continuous function.
I.e., $\projops{x_1,x_\alpha,x_j}(C_T)$ contains an open interval above $(b,y) \in Y_T$. 
Since $\dim(C) = 2$, all blow-up points $(b,y)$ have dimension $0$ and therefore there is a finite number of them. Repeating this process for $\alpha + 1 \le j \le n$, it follows that there exist points 
$$\{ b_{i,1}, \ldots, b_{i,k_i} \} \subset (b_i, b_{i+1})
$$ such that, for all $1 \le j < k_i$, $C_T \cap \{ b_{i,j} < x_1 < b_{i,j+1} \}$ is the grah of a continuous map. 
In particular, $C_T \cap \{ b_{i,j} < x_i < b_{i,j+1} \}$ is the graph of $\mathbf{f}\vert_{Y_T \cap \{ b_{i,j} < x_1 < b_{i,j+1} \}}$. 

Apply the same argument to $\inf_{x_\alpha} f_j$ (for $C_B$) so that, $C_T$ and $C_B$, if non-empty, are split into one-dimensional countinuous curves which are graphs of continuous functions, and the intervals above $0$-dimensional blow-up points. Once this property has been satisfied, we are left with a similar construction of optimisation with constraints as in Scetion \@ref(sec:lagrange-refinement).

### Critical points of the top and bottom of $C$

We now discuss how to perform this refinement on the CAD structure. Let us assume that $C_T\ne \emptyset$. We must construct subsets $W \subset Y$ such that $f_j\vert_{W_T}$ is a smooth, continuous functions. 
Let 
$$
{\cal A} = ({\cal A}_1, \ldots, {\cal A}_n)
$$
be the projection factor set as defined in Equation \@ref(eq:proj-fac-set) and
$$
C' := \projop{j-1}(C), C^j := \projop{j}(C),
$$
Begin with $j := \alpha+1$ so that $C'$ is a cylindrical sector cell and there exists an algebraic variety $V$ containing polynomials $g_2,\ldots,g_{j-1}$ with each $g_i \in {\cal A}_i, 2 \le i \le j-1$, defined in Equation \@ref(eq:c-alpha-top), such that $C'_T\subset V$.
By definition $$
C^j_T = \cl{C^j} \cap (C'_T \times \R)
$$ and there exists a polynomial $g_j \in {\cal A}_j$ such that $g_j(\mathbf{x}) = 0$ for all $\mathbf{x} \in C^j_T$. Since $C^j_T$ is either empty or the graph of a continuous function everywhere except, possibly, for a finite number of blow-up points, we need to find $x_1$-coordinates of points in $C'_T$ such that $g_j$ vanishes over an open interval. 
Since $C^j_T$ is one-dimensional, one way to achieve this is by computing a smooth stratification of $C^j_T$. If the projection of a one-dimensional stratum onto $x_1$ is a $0$-dimensional point $b \in \R$, then $b$ is the $x_1$-coordinate of a blow-up point. 

Alternatively, since the refinement points form a $0$-dimensional semialgebraic subset of $\R$, this set can be represented as a first-order Boolean formula
$$
\exists x_2,\ldots,x_{j-1} \exists_\infty x_j ((x_1,\ldots,x_{j-1}) \in C'_T, g_j(x_1,\ldots,g_j) = 0)
$$
where $\exists_\infty x$ is a special quantifier defined in `QEPCAD` meaning "there exist infinitely many values of $x$". 
Using $\exists_\infty$, som of the costly computations with algebraic numbers can be avoided, thereby improving efficiency in practice. **TODO refer to qepcad user documentation.**
Theoretically speaking, [@bpr2006, Algorithm 14.21] provides a singly exponential upper bound for quantifier elimination. **TODO what is the bound?**

Eliminating the $j-1$ quantifiers, we obtain the desired points $(b_{i,1},\ldots,b_{i,k_i})$, where each $b_{i,j}$ is the $x_1$-coordinate of a blow-up point of $g_j$. 
Now we can assume that $C^j_T\cap \{ b_{i,j} < x_1 < b_{i,j+1}\}$ is the graph of a continuous function. More precisely, the implicit function $g_j$ can be considered as a function from $C'_T \cap \{ b_{i,j} < x_1 < b_{i,j+1}\}$ to $\R$. We have a very similar construction as in Section \@ref(sec:lagrange-refinement). 
That is, polynomials $g_2,\ldots,g_{j-1}$ will provide the constraints in the first $j-2$ columns of the matrix in Equation \@ref(eq:jacobi-det), while $\partial h / \partial x_i, 1 \le i \le j - 1$ in the last column should be replaced with $\partial g_j / \partial x_i$
Denote this polynomial by $J_T$, and repeat with $C^j_B$ if appropriate. Inequalities $s_1 g_{1,1} > 0, \ldots, s_1 g_{1,\ell} > 0$ (from Equation \@ref(eq:lagrange-solve-qe-ineqs)), $d_T \ne 0$ and $d_B$ (from Equation \@ref(eq:lagrange-solve-qe-denominators)) are obtained and solved for $x_1$ in a very similar way as in Section \@ref(sec:lagrange-refinement). We obtain a set of refinement points
$$
\{ b_{j,1}, \ldots, b_{j,r_j} \} \subset (c_i,c_{i+1})
$$
such that each of $C^j_T$ and $C^j_B$ is either empty or the graph of a continuous, monotone function. 

The process is completed by induction in $j$. Suppose that the refinement has been performed for $\alpha + 1 \le j$. If $j = n$ we are done, and $C$ is now monotone. Otherwise, let $j := j+1$. By the induction hypothesis, we know that $C^{j-1}_T \cap \{b_{j-1,i} < x_1 < b_{j-1,i+1}\}, 1 \le i < r_{j-1}$ is either empty or the graph of a continuous function. 
If $C^{j-1}_T = \emptyset$, there is nothing to do and the process will terminate, since $C^j_T$ is empty. 
Otherwise, take $g_{j-1} \in {\cal A}_{j-1}$ used in the induction hypothesis and find $g_j \in {\cal A}_j$ such that $g_j(\mathbf{x}) = 0$ for all $\mathbf{x} in C^j_T$. 
Perform the same computation described abov, to refine $C^j_T$ such that one-dimensional components are graphs of continuous, monotone functions and repeat with $C^j_B$.
As before, a set of refinement poits
$$
b_{j,1}, \ldots, b_{j,r_j}
$$
is obtained

When the process terminates, the union of sets of refinement points $$
\{b_{\alpha + 1,1}, \ldots, b_{\alpha + 1,r_{\alpha + 1}}\}, \ldots, \{b_{n,1}, \ldots, b_{n,r_n}\}
$$
forms the refinement of $C$ into two- and one-dimensional monotone cells.

## Implementation Details

We now discuss implementation details of this step of the algorithm. First psuedocode is presented.

### Algorithm

---

**Input:** 
$$({\cal E}, {\cal A})$$

  - $\cal E$: a cylindrical algebraic decomposition of $\R^{k+n}$, such that each cell is the graph of a quasi-affine map. Each cell $C$ of $\cal E$ has a truth-value (*true* or *false* attached.
  
  - ${\cal A} = {\cal A}_1,\ldots,{\cal A}_{k+n}$ is the family of projection polynomials where each ${\cal A}_i \subset \Z[x_1,\ldots,x_i]$. 

**Output:** 
$$
{\cal R} := \{ {\cal R}_{\mathbf{b}} = \{ c_1,\ldots,c_t \} \subset \A \mid \mathbf{b} \in \R^{k-1} \text{ is a } (0,\ldots,0) \text{-cell in the decomposition induced by } {\cal E} \text{ on } \R^k \}
$$
such that, for each ${\cal R}_\mathbf{b}$, intersecting the sub-cad $\cal D$ above $\mathbf{b}$ with straight lines and half-planes of the kind $\{x_1 < c_i \}, \{x_1 = c_i \}, \{x_1 > c_i\}, 1 \le i \le t$ results in a refinement of $\cal D$ such that each true cell of $\cal D$ with dimension at most $2$ is monotone. 

---

First, define a subroutine
$${\rm sub}_{\mathbf{y}} (g) \mid g \in \Z[y_1,\ldots,y_m,x_1,\ldots,x_n], \mathbf{y} \in \A^m, n > 0,$$
which computes $h := g(\mathbf{y}) \in \A[x_{1},\ldots,x_m]$ and returns the normalised polynomial of $h$, in $\Z[x_{m+1},\ldots,x_n]$ (see Section \@ref(sec:sub-cad)). 

It will be convenient to overload this operator and write ${\rm sub}_{\mathbf{y}} (L)$, where $L$ is a set (or list) of polynomials to mean $\{ {\rm sub}_{\mathbf{y}} (g) \mid g \in L \}$.

Now define a structure to store refinement polynomials
$$
{\cal F} := \{ {\cal F}_{\mathbf{b}} := \emptyset \mid \mathbf{b} \in \R^{k-1}, k > 0 \text{ is a } (0,\ldots,0) \text{-cell in the decomposition induced by } {\cal E} \text{ on } \R^{k-1} \}
$$
and a similar structure to store refinement points 
$$
{\cal R} := \{ {\cal R}_{\mathbf{b}} := \emptyset \mid \mathbf{b} \in \R^{k-1}, k > 0 \text{ is a } (0,\ldots,0) \text{-cell in the decomposition induced by } {\cal E} \text{ on } \R^{k-1} \}
$$
*(Note: for each $(0,\ldots,0)$-cell $\mathbf{b}$, ${\cal F}_\mathbf{b}$ is a set of univariate polynomials, ${\cal R}_{\mathbf{b}}$ is the set of roots of polynomials ${\cal F}_\mathbf{b}$. When $k=1$, then the CAD of $\R^0$ consisting of the unique point of $\R^0$ is used -- practically speaking, we work directly with the CAD $\cal E$.)*

Let $\mathbf{b}$ be a $(0,\ldots,0)$-cell of the decomposition induced by $\cal E$ on $\R^{k-1}, k > 0$. Let $\cal D$ be the sub-decomposition of $\R^n$ of $\cal E$ above $\mathbf{b}$. 

Consider each cell $C$ of $\cal D$ with truth value *true*. Let $C$ have index
$$
(0,\ldots,0,1,i_{k+1},\ldots,i_{k+n})
$$
in $\cal E$. If $i_{k+1} + \cdots + i_n > 2$, then $\dim(C) > 2$ and the algorithm will fail. Otherwise, let $\alpha$ be the smallest among $x+1,\ldots,k+n$ such that $i_{k+1} = \ldots = i_{\alpha - 1} = 0$ and $i_\alpha = 1$. 
Then:

- Let

  - $\mathbf{b} := \projop{k-1}(C)$,

    *(Note: observe that $\mathbf{b} \in A^{k-1}$. If $k = 1$, then $\mathbf{b}$ is the unique cell, $\mathbf{0}$, in the CAD of $\R^0$. In this case, it is clear that ${\rm sub}_\mathbf{0} (g) \equiv g$.)*

  - $C'' (C''_B, C''_T) \subset \A := \projop{k}(C)$,

  - ${\cal G} := {\rm sub}_{\mathbf{b}} \{ g_i \mid k+1 \le i \le \alpha - 1, g_i \in {\cal A}_i, g_i(\mathbf{x}) = 0 \ \forall \mathbf{x} \in \projop{\alpha-1}(C) \}$,

  - $C' := \projop{\alpha}(C)$. 

- $C'_T$ and $C'_B$ be the top and bottom, respectively, $C'$. 
  
(*Note: If $C'$ is not bounded from above (resp. below) by a continuous definable function, i.e., there is no section above (resp. below) $C'$, then let $C'_T := \emptyset$ (resp $C'_B$) and skip any computations involving $C'_T$ (resp $C'_B$).)*

- Let $j = \alpha$ and do:

  - **(*)** For $\delta \in \{B, T\}$, if $C_\delta$ is not empty, do:

    - Let ${\rm sub}_{\mathbf{b}} (g_j) \in \Z[x_{k+1,\ldots,x_j}]$ be such that $g_\alpha(\mathbf{x}) = 0$ for all $\mathbf{x} \in $C'_\delta$. 

    - Compute
    $$
f_\delta := \det\begin{pmatrix}\dfrac{\partial g_{k+1}}{\partial x_{k}} & \cdots & \dfrac{\partial g_{j-1}}{\partial x_{k}} & \dfrac{\partial g_{j}}{\partial x_{k}}\\
\vdots &  &  & \vdots\\
\dfrac{\partial g_{k+1}}{\partial x_{j-1}} & \cdots & \dfrac{\partial g_{j-1}}{\partial x_{j-1}} & \dfrac{\partial g_{j}}{\partial x_{j-1}}
\end{pmatrix},
    $$
from Equation \@ref(eq:jacobi-det), using constraints $g_{k+1},\ldots,g_{\alpha+1}$, and discarding denominators $\partial g_\alpha / \partial x_\alpha$ of the total derivatives in the last column. 

  - Let $${\cal H} := \{ g_{k+1},\ldots,g_{j-1}, f_B, f_T \}$$
be a set of polynomials and compute
$$
{\cal F}_{\mathbf{b}} := {\cal F}_{\mathbf{b}} \cup \projop{1}({\cal H}) \subset \Z[x_k].
$$

  - If $j < n$, then
  
    - Add $g_j$ to $\cal G$, i.e., let
      $$
      {\cal G} := {\cal G} \cup \{ g_j \}.
      $$

    - Let $j := j+1$.

    - Let
      $$
      C' := \projop{j}(C)
      $$
      $C'$ is a section cell, and its top and bottom may not be graphs of continuous functions. Use QE to compute
      $$
      ...
      $$

- For each $(0,\ldots,0)$-cell $\mathbf{b} \in \A^k$, consider 
$$
{\cal F}_{\mathbf{b}} \in {\cal F} \in \Z[k],
$$
compute
$$
{\cal R}_{\mathbf{b}} := (c_1,\ldots,c_t)
$$
by isolating the real roots of polynomials in ${\cal F}_{\mathbf{b}}$.

- Return the family ${\cal R}$ of refinement points. 

---

**TODO**
- what if $f_j$ does not exist
- what if $\alpha = k+1$

## Computing the refinements

Now we have refinement points $\cal R$, we need to compute the refinement of the CAD $\cal D$ such that, for each $\cal R_k, 1 \le k \le n$, the points $c_i \in {\cal R_k}$ are $0$-cells in the CAD induced by $\cal D$ on $\R^k$. We proceed by induction on $k$

