# Frontier Condition {#sec:frontier}

Suppose we have a CAD $\cal D'$ monotone with respect to each bounded semialgebraic set $V_1,\ldots,V_k$, such that $\dim(V_i) \le 2, 1 \le i \le k$.
The algorithm from Section \@ref(sec:monotone-algorithm) produces such a CAD, which is also sign-invariant on a set of
polynomials $\mathbf{F} \subset \Z[x_1,\ldots,x_n]$. It is clear that $\mathbf{F}$ should contain the polynomials in
defining formulas for sets $V_i$, along with some additional polynomials which ensure that each cell $C \subset V_1 \cup
\ldots \cup V_k$ is monotone.
In this section, we describe how to refine $\mathcal{D'}$ in order that it satisfies the frontier condition. A refinement, $\mathcal{D''}$ of $\mathcal{D'}$ satisfies the frontier condition if $\fr{C}$ is a union of cells of $\mathcal{D''}$, for each cell $C \subset V_1 \cup \ldots \cup V_k$ of $\mathcal{D''}$ (Definition \@ref(def:frontier-condition)).

We first present a motivating example, a subset of the Whitney umbrella, which was presented by @jhd20.

::: { .example #whitney-jhd }
[@jhd20, Example 2.1]

Let $f := x^2 z - y^2$ and observe that $f(0,0,z) = 0, z \in \R$, i.e., $f$ blows up above the origin. Let $\Delta := \{(x,y) \in \R^2 \mid 0 < x < 1, -x < y < x \} \subset \R^2$ and let
$$
W := \{ (x,y,z) \in \R^3 \mid (x,y) \in \Delta, f(x,y,z) = 0 \}.
$$
Consider $\fr{W}$, which can be expressed as the disjoint union of four basic semialgebraic sets:
\begin{align*}
\fr{W} =&\ \{ (x,y,z) \in \R^3 \mid 0 < x < 1, y = x, z = 1 \} \\
\cup&\ \{ (x,y,z) \in \R^3 \mid 0 < x < 1, y = -x, z = 1 \} \\
\cup&\ \{ (x,y,z) \in \R^3 \mid x = 1, -1 < y < 1, z = y^2 \} \\
\cup&\ \{ (0,0,z) \in \R^3 \mid 0 \le z \le 1 \}.
\end{align*}
Due to the blow-up point above the origin, $\fr{W}$ contains the subset $B := \{ (0,0,z) \in \R^3 \mid 0 \le z \le 1 \}$.

A CAD having constant sign on the polynomials
$$
\{ x, x - 1, x + y, x - y, y^2 - x^2 z \}
$$ defining $W$ will not isolate the blow-up subset $B$, because two additional polynomials, $z$ and $z-1$, are needed to define it.
:::

It is clear from Example \@ref(exm:whitney-jhd) that a sign-invariant CAD may not always be sufficient to construct a
CAD with frontier condition. @pianomovers1983 proved that the frontier condition can be obtained following a linear
rotation of coordinates and @jhd20 proved that a well-based CAD (see Definition \@ref(def:well-based)) will always
satisfy the frontier condition. The result of @pianomovers1983 is related to that in @jhd20 because the rotation of
coordinates is performed in order for a well-based CAD to be constructed (see Section \@ref(sec:well-based)).
In the following sections, we discuss what to do when a rotation of coordinates is not permitted and when blow-up points may be present.

Note that $W$, from Example \@ref(exm:whitney-jhd), is a $(1,1,0)$-cell, but it is not monotone. In fact, $W$ is not
even the graph of a quasi-affine map, since $\projops{x,z}(W)$ is $2$-dimensional, but the projection map $\projops{x,z}\vert_W$ is not injective. The blow-up subset $B$, contained in $\fr{W}$ means that $W$ is not a topologically regular cell, since $\fr{W}$ is not homeomorphic to a circle.
In the procedures described in the following sections, due to @bgv15 and @lazard10, the cells on which the frontier condition is to be satisfied must be topologically regular cells.

## Frontier condition construction { #sec:frontier-bgv }

Given the monotone CAD $\mathcal{D'}$ computed in the algorithm from Section \@ref(sec:monotone-algorithm), our final step, according to [@bgv15, Theorem 3.20] is to compute a refinement $\mathcal{D''}$ of $\mathcal{D'}$ such that the frontier $\fr{C} = \cl{C} \setminus C$ of every cell $C \subset V = V_1\cup \ldots \cup V_k$ is a union of cells of $\cal D''$.

The construction from @bgv15, Theorem 3.20 proceeds as follows. For each $2$-dimensional cell $C \subset V$, consider
the semialgebraic set $\fr{C}$. Since $C$ is monotone, we can assume that $\fr{C}$ is homeomorphic to a circle.
Construct a partition $\cal U$ of $\fr{C}$ into monotone curves and points, such that $\cal U$ is
compatible with all $1$-dimensional cells of $\cal D'$.
Let $\mathbf{c} = (c_1,\ldots,c_n)$ be one of the $1$-dimensional components of $\cal U$. If $c_1$ is not a $0$-dimensional cell of the decomposition induced by $\cal D'$ on $\R^1$, then perform a refinement of the kind $x_1 < c_1, x_1 = c_1, x_1 > c_1$. Recall that these refinements, according to [@bgv15, Lemma 3.11], preserve the cylindrical structure and monotone cells. Otherwise, $c_1$ is a $0$-cell and we apply the same argument to the sub-CAD of $\cal D'$ above $c_1$.

Now let $T \in {\cal U}$ be one of the $1$-dimensional components. If $T$ is not an existing $1$-dimensional cell of
$\cal D'$, then it is a subset of a $2$-dimensional cell $Z$ of $\cal D'$. In fact, it divides $Z$ into two cells $Z
\setminus T$, both of which, according to [@bgv13, Theorem 11], are $2$-dimensional monotone cylindrical cells. Hence, replacing $Z$ by $T$ and the two monotone connected components of $Z \setminus T$ makes $Z$ compatible with $\fr{C}$, while the refinement of $Z$ consists of only monotone cells.

Repeating this process for each $0$- and $1$-dimensional component of $\cal U$, we obtain a refinement of $\cal D'$ compatible with $\fr{C}$.
This completes the construction of a cylindrical decomposition $\mathcal{D''}$ satisfying the frontier condition and
monotone with respect to each of the bounded semialgebraic sets of dimension at most $2$, $V_1,\ldots,V_k$.

The most computationally difficult part of implementing this construction is computing $\fr{C}$.

::: {.lemma}
Let $S \subset \R^n$ be a semialgebraic set defined by a quantifier-free Boolean formula $F$
containing $s$ different polynomials in $\R [x_1, \ldots ,x_n]$ having maximum degree $d$.
There is an algorithm, taking $F$ as input, which represents the semialgebraic set $\fr{ S }$ by a quantifier-free Boolean formula $F'$ with complexity
$$(sd)^{\O(n^2)}.
$$
This is also an upper bound on the number of polynomials in $F'$ and their degrees.
:::

The above is presented, proved and discussed as Lemma \@ref(lem:frontier) in Section \@ref(sec:novel-frontier-fr).
The obvious way of computing the frontier involves solving a quantifier elimination problem with two quantifier
alternations. Using a theoretically efficient algorithm, e.g., [@bpr2006, Algorithm 14.21], this procedure has complexity singly exponential in the number of variables. $\partial C$ is represented by a quantifier-free Boolean formula $F$.

Once $\fr{C}$ has been computed, we first construct the family $\cal U$ of $1$-dimensional curve intervals $T$ and the
points between them $\mathbf{c}$. By Lemma \@ref(lem:one-dim-qa-is-monotone), $1$-dimensional quasi-affine cells are
always monotone. Thus, we may apply the method described in Section \@ref(sec:quasi-affine) to obtain Jacobi matrices
whose determinants are zero at the critical points of projections onto $1$- and $2$-dimensional coordinate subspaces.
We require that each smooth $1$-dimensional cell $D$ in $\fr{C}$ is smooth and will include $n-1$ polynomial equations
in its defining formula, which define an algebraic variety which has dimension $1$ at every point in $D$.
This is so that we can refine $\fr{C}$ to be compatible with the critical points of $\projops{x_i}(D), 1\le i \le n$
defined by $\det(J_{\hat{i}}) = 0$, as we did in Chapter \@ref(sec:quasi-affine). Thus, we would
also need to apply the smooth stratification algorithm to $\mathcal{U}$ to ensure that its components are effectively
nonsingular.

A further refinement of each $1$-dimensional component $T$ of $\cal U$ to be compatible with existing cells of $\cal D'$ may also be required.
For each $1$-dimensional component $T \in {\cal U}$ and each $1$-dimensional cell $D$ of $\cal D'$, consider $E := T \cap D$ such that $E \ne \emptyset$.
If $E \subset D$, then $T$ should be split into $0$- and $1$-dimensional cells such that the endpoints of $E$ are the new $0$-cells.
This makes $\cal U$ compatible with all cells of the CAD $\cal D'$.

Consider each $T \in {\cal U}$ which is a subset of a $2$-dimensional cell $Z$. The refinement can be performed exactly as described by @bgv15, Theorem 3.20. I.e., partition $Z$ into $Z_1 \cup T \cup Z_2$ where $Z_{1,B}=Z_B$ and $Z_{1,T} = T$ and $Z_{1,B}=Z_T$ and $Z_{1,T} = Z_T$.

Now consider the $0$-dimensional components $\mathbf{c} = (c_1,\ldots,c_n)$ of $\cal U$. Refinements of $\cal D$ to be
compatible with $\mathbf{c}$ again proceed as described by @bgv15. I.e., Consider $C' := \projop{k}(C)$ such that $C'$
is $0$-dimensional and equal to $(c_1,\ldots,c_k)$, but $\projop{k+1}(C)$ is $1$-dimensional. Perform a refinement of
the sub-CAD above $(c_1,\ldots,c_k)$ by intersecting it with $\{ x_k < c_k \}, \{ x_k = c_k \}, \{ x_k > c_k \}$ -- the refinements defined in @bgv15, Lemma 3.11. Repeat until $(c_1,\ldots,c_n)$ is a cell in the refinement.

Let $\cal D''$ be the refinement of $\cal D'$, compatible with $\fr{C}$ for all $2$-dimensional cells $C$ of $\cal D'$. This CAD is compatible with, and monotone with respect to all $V_1,\ldots,V_k$, and the frontier of each cell $C \subset V_1\cup \ldots V_k$ of $\cal D''$ is the union of some other cells of $\cal D''$ of smaller dimension.
$\cal D''$ satisfies the frontier condition, so the construction is complete.

We have proved that the following algorithm exists, and will discuss its complexity later.

::: { .theorem #lazard-rn }
Let $\mathbf{F} \subset \Z[x_1,\ldots,x_n]$ be a set of $s$ polynomials with maximum degree $d$.
Let $\mathcal{D}$ be an $\mathbf{F}$-invariant CAD of $\R^n$, compatible with some bounded definable semialgebraic sets
$V_1,\ldots,V_k$, which have $\dim(V_i) \le 2$ and such that each cell $C \subset V_i$ is monotone.

Then there is an algorithm, taking $\mathcal{D}$ as input, which produces a refinement $\mathcal{D'}$ of $\mathcal{D}$ such that each cell $C \subset V_1\cup\ldots\cup V_k$ of $\mathcal{D'}$ satisfies the frontier condition.
This algorithm has complexity
$$
\left(s\left(d+1\right)\right)^{\O(1)^{n}},
$$
which is also an upper bound on the number of cells in the CAD, number of polynomials and their degrees.
:::

Let us apply this algorithm to Example \@ref(exm:whitney-jhd). In order to make $W = \{ (x,y,z) \in \R^3 \mid 0 < x < 1, -x < y < x, x^2 z - y^2 = 0 \}$ a monotone cell, it can be split into three cells as follows:
\begin{align*}
W_1 &:= \{ (x,y,z) \in \R^3 \mid 0 < x < 1, -x < y < 0, x^2 z - y^2 = 0 \},\\
W_2 &:= \{ (x,y,z) \in \R^3 \mid 0 < x < 1, y = 0, z = 0 \},\\
W_3 &:= \{ (x,y,z) \in \R^3 \mid 0 < x < 1, 0 < y < x, x^2 z - y^2 = 0 \}.
\end{align*}
Now $\fr{W_1}$ and $\fr{W_3}$, the two $(1,1,0)$-cells are homeomorphic to circles, with $W_2$, a $(1,0,0)$-cell, being part of both $\fr{W_1}$ and $\fr{W_2}$.
Each of the frontiers of the $2$-dimensional cells $W_1$ and $W_3$ are partitioned into points and monotone curve intervals compatible with the existing cells in the decomposition:
\begin{align*}
\mathcal{U}_{W_1} := \{ C_{1,1} &= \{ 0 < x < 1, y = -x, z = 1 \},\\
C_{1,2} &= \{ x = 1, -1 < y < 0, z = y^2 \},\\
W_2 &= \{ 0 < x < 1, y = 0, z = 0 \},\\
C &= \{ x = y = 0, 0 < z < 1 \},\\
\mathbf{a} &= (0,0,0), \mathbf{b} = (0,0,1), \mathbf{c} = (1,0,0), \mathbf{d} = (-1, 1, 1) \},\\
\mathcal{U}_{W_3} := \{ C_{2,1} &= \{ 0 < x < 1, y = x, z = 1 \},\\
C_{2,2} &= \{ x = 1, 0 < y < 1, z = y^2 \},\\
W_2 &= \{ 0 < x < 1, y = 0, z = 0 \},\\
C &= \{ x = y = 0, 0 < z < 1 \},\\
\mathbf{a} &= (0,0,0), \mathbf{b} = (0,0,1), \mathbf{c} = (1,0,0), \mathbf{e} = (1, 1, 1) \}.
\end{align*}
Suppose that our decomposition is the "coarsest" possible CAD compatible with $\{W_1,W_2,W_3\}$. I.e., it contains the
smallest number of cells required for it to be cylindrical and compatible with each set $W_1$, $W_2$ and $W_3$. Then the following refinements will take place:

- refine the $(1,0,1)$-cell $\{ 0 < x < 1, y = -x \}$ to be compatible with $C_{1,1}$,
- refine the $(1,0,1)$-cell $\{ 0 < x < 1, y = x \}$ to be compatible with $C_{2,1}$,
- refine the $(0,1,1)$-cell $\{ x = 1 \}$, which is actually a sub-CAD of $\R^2$ above $x=1$ to be compatible weth the
  cells $\mathbf{d}$, $C_{1,2}$, $\mathbf{c}$, $C_{2,2}$ and $\mathbf{e}$i, and
- refine the $(0,1,1)$-cell $\{ x = 0 \}$ to be compatible with $\mathbf{a}$, $C$ and $\mathbf{b}$.

The first three refinements involve intersecting monotone $2$-dimensional cells, in this case planes, with monotone
curves, thus the refinements remain monotone. The final refinement involves dividing the plane $\{ x = 0 \}$ into two
half-planes $\{ x = 0, y < 0 \}$ and $\{ x = 0, y > 0 \}$ and then dividing the $1$-dimensional cylinder above the origin, $\{ x = 0, y = 0 \}$, so that it is compatible with $\{ x = 0, y = 0, 0 \le z \le 1 \} \subset \fr{W}$.
If the CAD was constructed so that it had constant sign on the polynomials defining $W_1$, $W_2$ and $W_3$, many of these refinements would not have been needed. In particular, $C_{1,1}, C_{1,2}, C_{2,1}, C_{2,2}, \mathbf{a}, \mathbf{c}, \mathbf{d}$ and $\mathbf{e}$ will already be cylindrical cells. However, the final refinement, to be compatible with $C$ and its top $\mathbf{b}$ is still required to obtain the frontier condition.


## Lazard's method { #sec:lazard-3 }

The method described in Section \@ref(sec:frontier-bgv) is relatively straightforward as it relies on techniques we have used before (obtaining quasi-affine subsets and performing refinements). However, we may want to find an alternative method, so as to avoid the QE required to compute the frontiers of $2$-dimensional cylindrical cells.
In the following section, we will explore an alternative method to obtain the frontier condition, based on an algebraic construction described by @lazard10.

@lazard10 presents an algorithm for constructing an $\mathbf{F}$-invariant cylindrical algebraic decomposition of $\R^n, n\le 3$ such that every cell is a topologically  regular cell and the frontier condition is satisfied.
Lazard refers to a decomposition having these properties as a *strong* decomposition (see Definition \@ref(def:laz-strong)).

::: {.definition #laz-properties }
[@lazard10, Definition 2.7]

1. A cylindrical cell $C$ is locally boundary connected if the intersection with $C$ of every small open ball centred on the boundary of $C$ is connected.
2. A $k$-dimensional cylindrical cell is well-bordered if $\fr{C}$ is the closure of some $k-1$-dimensional cylindrical cells.
3. A cylindrical cell $C$ is closure finite if $\fr{C}$ is a union of cells.
:::

Note that @lazard10 calls property 2 of Definition \@ref(def:laz-properties) "boundary smooth" and Property 3 boundary
coherent. However, @jhd20 propose the more descriptive terms "locally boundary connected" and "closure finite", which will be used here.

::: {.remark}
[@lazard10, Definition 2.7]

These properties can be extended from cells to the whole CAD. I.e., a CAD $\mathcal{D}$ is called well-bordered (resp.
closure finite, boundary smooth) if every cell in $\mathcal{D}$ is well-bordered (resp. closure finite, locally boundary connected).
:::

::: {.remark}
If a cylindrical cell satisfies Property 2 of Definition \@ref(def:laz-properties) (locally boundary connected) then it is a topologically regular cell.

If a cylindrical cell $C$ satisfies Property 3 of Definition \@ref(def:laz-properties), then $\fr{C}$ is a finite
disjoint union of cylindrical cells of smaller dimension. If each cell in $\fr{C}$ belongs to the same cylindrical
decomposition as $C$, then $C$ is said to satisfy the frontier condition.
:::

::: {.definition #laz-strong}
[@lazard10, Definition 2.7]

A CAD is called strong if every cell is locally boundary connected, well-bordered and closure finite.
:::

::: {.definition}
[@lazard10, Definition 4.1]

Let $\mathcal{D}$ be an $\mathbf{F}$-invariant CAD of $\R^n$ and $\mathcal{D'}$ be the decomposition induced by $\mathcal{D}$ on $\R^{n-1}$. A cell $C'$ of $\mathcal{D'}$ is called *bad* if there is a polynomial $f \in \mathbf{F} \subset \Q[x_1,\ldots,x_n]$ such that $f$ is primitive and has positive degree in $x_n$ and $f(\mathbf{x})$, for all $\mathbf{x} \in C'$ vanishes over an open interval. Every point $\mathbf{x}$ in the bad cell $C'$ is a blow-up point of the polynomial $f$ (see Definition \@ref(def:blow-up-point)).
:::

According to @lazard10, Corollary 4.7, in dimension $\le 2$, there is nothing to do as Collins' algorithm already produces these strong decompositions.
In fact, any decomposition in dimension $\le 2$ is well-based so, according to @jhd20, a strong decomposition will be obtained regardless of the method used to construct it.
For a cylindrical decomposition of $\R^3$, the process works in three steps:

1. Obtain well-bordered cells
2. Obtain locally boundary connected cells
3. "Lift above bad points" to satisfy the frontier condition.

First, we must ensure that every cell is well-bordered. The following result shows that this is already the case for sign-invariant decompositions of $\R^3$.

::: {.proposition #lazard-5-4}
[@lazard10, Corollary 5.4]

Every $\mathbf{F}$-invariant CAD of $\R^n, n \le 3$ is well-bordered.
:::

Proposition \@ref(prp:lazard-5-4) follows from @lazard10, Lemma 5.1 and Theorem 5.3.
The former asserts that every $0$- and $1$-dimensional cell in a CAD of arbitrary dimension is well-bordered.
The latter asserts that any cell in an $\mathbf{F}$-invariant CAD $\mathcal{D}$ of $\R^3$, such that the decomposition $\mathcal{D}'$ induced by $\mathcal{D}$ on $\R^2$ is strong, is well-bordered.
Note that $\mathcal{D}'$ is a $\projop{2}(\mathbf{F})$-invariant CAD of $\R^2$ and is always strong by @lazard10, Corollary 4.7.
@lazard10, Proposition 5.2 depends on the following result.

::: {.proposition #lazard-5-2}
[@lazard10, Proposition 5.2]

Let $\cal D$ be a CAD of $\R^n$ and $\cal D'$ the decomposition induced by $\cal D$ on $\R^{n-1}$. Let $C$ be a cell of
$\cal D$ and $C' := \projop{n-1} (C)$ such that $C'$ is closure finite.
If $p \in \fr{C'}$, then $I := (p \times \R) \cap \fr{C}$ is connected.
$I$ is therefore a point or a closed segment, either bounded or unbounded.
Furthermore, if $C$ is a sector cell, then the set of points of $I$ which do not belong to the boundaries of the section cells delineating $C$ is either empty or an open interval.
:::

@lazard10, Theorem 5.12 describes how to pass from a well-bordered, $\mathbf{F}$-invariant CAD $\mathcal{D}$ of $\R^3$ to one in which every cell is locally boundary connected. This is done by refining $\mathcal{D}$ so that it has constant sign on some new polynomials. This refinement contains only well-bordered, topologically regular cells.
The construction of a CAD with monotone cells described in Section \@ref(sec:monotone-cells) also satisfies these
properties, if we limit ourselves to $n\le3$. Indeed, the algorithm from Section \@ref(sec:quasiaffine-algorithm)
returns a CAD with constant sign on $\mathbf{F'}$, the set of input polynomials and the additional polynomials added to
ensure that every cell is smooth and the graph of a quasi-affine map. Hence, every cell in this CAD is well-bordered.
The algorithm for obtaining monotone cells, described in Section \@ref(sec:monotone-algorithm) requires us to compute
refinements of the kind $\{ x_1 < c \}, \{ x_1 = c \}, \{ x_1 > c \}$ of a $(1)$-cell $C'$ in the sub-decomposition
above a $0$-dimensional cell.
This refinement is also applied to every cell $C$ in this sub-decomposition such that $C' := \projop{1}(C)$. Thus, the refined CAD is sign-invariant on $\mathbf{F'}$ and the cells $C$ projecting onto $C'$ are sign-invariant with respect to polynomials $x_1 - c$, defining each refinement point $c$.
Cells which were not refined are either already monotone or lie outside of the input sets $V_1,\ldots,V_k$.
As a result, we are able to apply Lazard's method for lifting with bad points to the CAD produced by the algorithm from Section \@ref(sec:monotone-algorithm).

@lazard10, Section 5.3 describes how to pass from an $\mathbf{F}$-invariant CAD of $\R^3$ such that every cell is well-bordered and locally boundary connected to one satisfying the frontier condition.
By @lazard10, Theorem 4.4, a cell $C$ already satisfies the frontier condition if no points in its frontier project onto a bad cell (see also @jhd20).
Thus, only cells which fail to satisfy this property need to be considered. By @lazard10, Lemma 4.3, in $\R^3$, if a bad cell exists, then it has dimension $0$.

::: { .proposition #only-bad-zero-cells }
[@lazard10, Lemma 4.3]

A sign-invariant CAD of $\R^2$ contains no bad cells.

For an $\mathbf{F} \subset \Q[x_1,x_2,x_3]$-invariant CAD $\mathcal{D}$ of $\R^3$, if the decomposition induced by $\mathcal{D}$ on $\R^2$ contains a bad cell, then it is a $(0,0)$-cell.
:::

This follows from the fact that, in $\R^n$, a blow-up subset of a polynomial in $\Q[x_1,\ldots,x_n]$ in $\R^{n-1}$ has
codimension at least $2$ (see Remark after Definition \@ref(def:blow-up-point)).

::: { .proposition #no-blow-up }
[@lazard10, Theorem 4.4]

Let $\mathcal{D}$ be an $\mathbf{F}$-invariant CAD of $\R^n$ and $C$ be a cell of $\mathcal{D}$ with $C' := \proj_{\R^{n-1}}(C)$. If the decomposition induced by $\cal D$ on $\R^{n-1}$ is strong and none of $C'$ and any cell $D'$ such that $D' \cap \fr{C'} \ne \emptyset$ is bad, then $C$ is well-bordered, locally boundary connected and $\fr{C}$ is a union of some cells of $\mathcal{D}$.
:::

::: {.proof}
This result follows from the following fact about roots of multivariate polynomials: given a polynomial $f  \in \Q[x_1,\ldots,x_{n-1}][x_n]$, i.e., considered as a univariate polynomial with polynomial coefficients, its complex roots depend continuously on the parameters in the region of the parameter space where the polynomial does not vanish identically. In fact, this is only true in the projective closure of $\mathbb{C}$ as some roots may pass through the point at infinity if the leading coefficient is zero.

First suppose that $C$ is a section cell. I.e., it is a root of some polynomial $f$ and $\fr{C}$ is defined as the limit of this root over the boundary of $C'$. Thus $\projop{n-1}$ is a continuous, injective map from $\fr{C}$ to $\fr{C'}$. This follows from the condition that the decomposition induced by $\cal D$ on $\R^{n-1}$ is strong and that if the root defining the section $C$ is infinite over some cell $C'' \subset \fr{C'}$, then it is also infinite over $\fr{C''}$.

Now suppose that $C$ is a sector cell. If nonempty, the top $C_T$ and bottom $C_B$ of $C$ are section cells. We complete the proof by describing $W := \fr{C} \setminus (C_T \cup C_B)$.
We will only consider the case where $C \cap \{ \mathbf{x} \times \R \}$ is an open interval bounded from below by a point in $C_B$ and above by a point in $C_T$.

Let $\dim(C) = d + 1$. $\fr{C}$ consists of

- the cells in $\fr{C_B}$ and $\fr{C_T}$, which have dimension $< d$ and are contained in $\fr{C'} \times \R$,
- the intervals (which may be empty) bounded by the points in $\fr{C_B}$ and $\fr{C_T}$, contained in $C' \times \R$.

Since $C_B$ and $C_T$ are section cells, they are roots of polynomials $f$ and $g$ and, if finite, the points in $\fr{C_B}$ and $\fr{C_T}$ are also roots of $f$ and $g$ (respectively).
Therefore, these intervals are contained in some cells of $\cal D$. More precisely, the cells with dimension $d$ contained in $\fr{C'} \times \R$ are exactly those lying over a cell $C'' \subset \fr{C'}$ with dimension $d-1$.

A cell of dimension $< d$ either belongs to $\fr{C_B}$ or $\fr{C_T}$, or is a sector over a cell $D \subset \fr{C'}$ having dimension less than $d-1$.
As $C'$ is well-bordered, $D$ belongs to the boundary of some cell $E \subset \fr{C'}$ having dimension $d-1$.
Thus, the sector above $D$ is contained in the boundary of the sector above $E$, which has dimension $d$.

This proves that, if the decomposition induced by $D$ on $\R^{n-1}$ is strong, then $C$ is well-bordered and also satisfies the frontier condition. In addition, this proves that $C$ is a topologically regular cell as $C$ and $\fr{C}$ are either homeomorphic to $C'$ and $\fr{C'}$, if $C$ is a sector cell, or to an open cylinder, either bounded or unbounded, and its boundary. It is clear that an open cylinder contained in $C' \times \R$, where $C'$ is topologically regular, is also topologically regular.

The other cases are deduced by omitting the cells defined from $C_B$ and $C_T$ as appropriate.
:::

::: {.proposition #lazard-5-13}
[@lazard10 Proposition 5.13]

Let $\mathcal{D}$ be an $\mathbf{F}$-invariant CAD of $\R^3$ and $C$ be a well-bordered, locally boundary connected cell of $\mathcal{D}$.
Suppose that $D$ is a cell of $\mathcal{D}$ such that $B := D \cap \fr{ C } \neq \emptyset$ and $B \neq D$. Then either

  1. $C$ is a $1$-dimensional section cell whose endpoint, $B$, projects onto a bad cell, or
  2. there exists a cell $E$ of $\mathcal{D}$ such that $\dim(E) < \dim(C)$ and $\emptyset \neq D \cap \fr{ E } \neq D$.
:::

<!--
To illustrate this, consider the example of the whitney umbrella $W := \{ x^2 - y^2 z = 0 \}$. Let $C := \{ x > 0, y > 0, x^2 - y^2 z = 0 \} \subset W$ be one of the 2-dimensional topologically regular cells in a CAD of $\R^3$ compatible with $W$.
Then case $2$ applies, with $D = \{ x = 0, y = 0 \}$ and $E = \{ x > 0, y = 0, z = 0 \}$.
Taking $C = E$, (and the same $D$) we get case $1$.
-->

::: {.proof}
By the proof of @lazard10, Theorem 4.4, $D$ will always be a $(0,0,1)$-cell in the cylinder above a bad cell $D'$.

Consider each case for $C$ by the cell's binary index.

- $(1,1,1)$-cell: since $C$ is well-bordered, its boundary is the closure of some $2$-dimensional cells of $\cal D$ and
  $B$ is contained in the union of the boundaries of the 2-cells. Thus, case 2 applies and we can choose an appropriate
  $2$-dimensional cell in $\fr{C}$ for $E$.

- $(1,0,1)$- or $(0,1,1)$-cell, we write $(i,j,1)$-cell where $i+j=1$: observe that $C$ (if bounded) is delineated by
  some $(i,j,0)$-cells ($1$-dimensional curve intervals). Take $B$ to be the $1$-dimensional interval delineated by the endpoints of these cells. Since $B \neq C$, at least one of these endpoints is not a $(0,0,0)$-cell of $\cal D$. Case 2 applies, taking as $E$ the delineating $(i,j,0)$-cell.

- $(1,0,0)$- or $(0,1,0)$-cells: consider the previous case, letting $C = E$.

- $(1,1,0)$-cell: these are necessarily the root of a polynomial $f \in \Q[x_1,x_2,x_3]$ which vanishes identically on $D'$, a $(0,0)$ cell in the decomposition induced by $\cal D$ on $\R^2$.
Let $V_r$ be a small neighbourhood (with radius $r > 0$) centred around $D'$ and consider $V_r'$, the cylinder above the boundary of $V_r$. Since $C$ is a monotone cell, the maximum and minimum values of $x_3$ in this intersection are reached on the boundary of $C$, for sufficiently small $r$. The limits, as $r$ tends to $0$, of this maximum and minimum clearly belong to the boundary of $B$, even if these limits are not finite. Note that both the maximum and minimum cannot be infinite, since this would imply that either $B$ is empty, or coincides with $D$. Therefore, the non-infinite limits are the endpoints of some $1$-dimensional cell belonging to the boundary of $C$. Case 2 applies, taking $E$ to be this $1$-dimensional cell.

- $(0,0,1)$- or $(0,0,0)$-cells: do not satisfy the hypothesis, there is nothing to do.
:::

The following result shows how $(0,0,1)$-cells which project onto a bad point can be refined to obtain the frontier condition.

::: { .proposition #lazard-5-14 }
[@lazard10, Proposition 5.14]

Let $f \in \Q[x_1,x_2,x_3]$ be an irreducible polynomial and
$\mathbf{p} = (p_1,p_2)$ be a common root of the coefficients of the powers of $x_3$, which are polynomials in
$\Q[x_1,x_2]$.
Let $g\in \Q[x_1,x_2]$ be an irreducible polynomial having $\mathbf{p}$ as a root.
The limits of the common roots of $f$ and $g$ as $(x_1, x_2) \to \mathbf{p}, (x_1, x_2) \ne \mathbf{p}$ may be computed
as solutions of a $0$-dimensional polynomial system.
:::

::: {.proof}
Since $f$ is irreducible, it has at least two coefficients in $\Q[x_1,x_2]$ and their GCD is a constant.
Take $h \in \Q[x_1,x_2]$ to be a coefficient of $f$ which is not a multiple of $g$. Note that $h$ is irreducible so
$\{ g = 0, h = 0 \} \in \R^2$ is zero-dimensional and contains $\mathbf{p}$.
The saturation by $h$ of the ideal $\langle f,g \rangle$ is defined as
$$
S := \langle f, g, 1 - zh \rangle \cap \Q[x_1,x_2,x_3].
$$
The irreducible components of the zero set of $S$ are those of the zero set of $\langle f,g \rangle$ at which $h$ is not
identically zero.
It follows that the vertical line $\{ x_1 = p_1, x_2 = p_2 \}$ which is part of the zero set of $f$, $g$ and $h$, is not contained in the zero set of $S$. Meanwhile, the zero set of $S$ contains the limit points we are interested in finding.

Therefore, the ideal generated by $S$ and the coefficients of $f$ is $0$-dimensional and the limits of $\{ f=0,g=0 \}$
as $(x_1,x_2) \to \mathbf{p}$ can be computed as the solutions of $S$.
:::

The proof of @lazard10, Proposition 5.14 depends on taking Zariski closures. These are now defined and a relevant property presented, closely following @cox2013.

::: {.proposition #cox-zariski}
[@cox2013 p203, part of Theorem 10]

Let $I,J \subset K[x_1,\ldots,x_n]$ be ideals, then
$\cl{ V(I) \setminus V(J) } \subset V(I : J^\infty)$.
:::

::: {.proof}
We claim that $I \subset I:J \subset I:J^\infty \subset I(V(I) \setminus V(J))$. We have $I \subset I:J \subset \cdots \subset I:J^\infty$ from the definition.
Suppose that $f \in I:J^\infty$ and $a \in V(I) \setminus V(J)$. Then $fg^N \in I$ for all $g \in J$ and a suitable (large enough) $N\ge 0$. Since $a \in V(I)$, $f(a)g^N(a) = 0$ (for all $g\in J$ and large enough $N$). Since $a \not \in V(J)$, there exists $f \in J$ and $N \ge 0$ such that $g(a) \ne 0$. Hence $f(a) = 0$ for all $a \in V(I) \setminus V(J)$. We have $f \in I(V(I) \setminus V(J))$. Transitivity of $\subset$ proves the claim. Since $V$ reverses inclusion, we have $= \cl{ V(I) \setminus V(J) } = V(I(V(I) \setminus V(J))) \subset V(I:J^\infty)$.
:::

The proof of @lazard10, Proposition 5.14 begins with an irreducible polynomial $f \in \Q[x_1,x_2,x_3]$, such that there exists a $(1,1,0)$-cell $C \subset \{ \mathbf{x} \in \R^3 \mid f(\mathbf{x}) = 0 \}$, a point $\mathbf{p} = (p_1,p_2) \in \R^2$ such that $\mathbf{p}$ is a blow-up point of $f$, and $g \in \Q[x_1,x_2]$ such that $g(\mathbf{p}) = 0$.
Consider the variety $V(\langle f \rangle + \langle g \rangle ) = V(f) \cap V(g)$, which contains some of the $1$-dimensional cells which form part of $\fr{C}$ and the blow-up subset $B \subset \mathbf{p} \times \R$.
The saturation by $h$ of $I$,
$$
S := \langle f, g, 1 - zh \rangle \cap \Q[x_1,x_2,x_3]
$$
is constructed.
By Proposition \@ref(prp:cox-zariski) (@cox2013, Theorem 10),
$$
\cl{ V(\langle f,g \rangle) \setminus V(\langle h \rangle) } \subset S.
$$
Since our blow-up point $\mathbf{p}$ is $0$-dimensional, computing this Zariski closure "fills in the hole" left by removing the blow-up subset from $V(\langle f,g \rangle)$. Thus, we have the limit points of the cell $C$ as it approaches the blow-up subset $B$.
In order to find the refinement points above $\mathbf{p}$, we compute a generating set (Groebner basis) $\{ f_1,\ldots,f_k \}$ for $S$ and solve the system of equations
$$
f_1 = 0, \ldots, f_k = 0, g = 0, h = 0.
$$

Note that this procedure only works if the blow-up points have dimension $0$. Otherwise, the endpoints of $1$-dimensional cells in the frontier of $C$ will not be sufficient to satisfy the frontier condition.

### Lazard's lifting above bad points { #sec:lazard-algorithm }

Let $\cal D$ be an $\mathbf{F}$-invariant CAD of $\R^n, n \le 3$. If $n \le 2$, $\cal D$ is already strong -- well-bordered, locally boundary connected and satisfies the frontier condition. In particular, by Proposition \@ref(prp:only-bad-zero-cells), the frontier condition is already satisfied since there are no bad cells in the decomposition induced by $\mathcal{D}$ on $\R^2$ [@lazard10, Lemma 4.3].
Also by Proposition \@ref(prp:only-bad-zero-cells), any bad cells in the decomposition induced by $\mathcal{D}$ on $\R^2$ are $0$-dimensional [@lazard10, Lemma 4.3].
Therefore, the frontier condition is satisfied everywhere except in the neighbourhoods above bad cells in the induced decomposition of $\R^2$. The following algorithm is a special method for lifting above a bad cell.

::: {.algorithm data-latex="Lazard Lifting With Bad Points in $\R^3$"}
[@lazard10, Algorithm 5.15]

$$\mathcal{R} := \textproc{LazardLift3}({\cal A}, {\cal D})$$

**Input:**

  - ${\cal A} = {\cal A}_1,{\cal A}_2,{\cal A}_3$ is the family of projection polynomials, each $\mathcal{A}_k \subset \Q[x_1,\ldots,x_k]$,

  - $\cal D$: is an $\mathcal{A}$-invariant CAD of $\R^3$ such that every cell of $\mathcal{D}$ is a topologically regular cell.

**Output:**
$$
{\cal R} := \{ {\cal R}_{\mathbf{b}} = \{ c_1,\ldots,c_t \} \subset \A \}
$$
where $\mathbf{b}\in \R^{2}$ is a $(0,0)$-cell in the decomposition induced by $\cal D$ on $\R^2$.
A set of refinement points, as described in Section \@ref(sec:monotone-algorithm).

\begin{algorithmic}[1]
\Procedure{IsBad}{$\mathcal{A}_3, \mathcal{D}, \mathbf{b}$}
\State \Return $\exists f \in \mathcal{A}_3, C$ in $\mathcal{D}$ such that $C$ is a $(0,0,1)$-cell, $proj(C) =
\mathbf{b}$ and $f(\mathbf{x}) = 0$ for all $\mathbf{x} \in C$
\EndProcedure

\Procedure{LazardLift3}{$\mathcal{A}, \mathcal{D}$}
\State ${\cal R} \gets \emptyset$
\State Let $\cal D'$ be the decomposition induced by $\cal D$ on $\R^2$

\For{each $(0,0)$-cell $\mathbf{b}$ in $\cal D'$}
  \State \Comment{determine whether it is a bad cell}
  \If {$\textproc{IsBad}(\mathcal{D},\mathbf{b})$}
    \State $g_1 \in {\cal A}_1, g_2 \in {\cal A}_2$ such that $g_1(\mathbf{b}) = 0$ and $g_2(\mathbf{b}) = 0$
    \State ${\cal A'} := {\cal A}_1 \cup {\cal A}_2$
    \For {each $g \in {\cal A'}$}
      \If {$g \in \Q[x_1]$}
        \State $h \gets g_2$.
      \Else \Comment{$g \in \Q[x_1,x_2]$}
        \State $h \gets g_1$
      \EndIf

      \State $I \gets \langle f, g, 1 - z h \rangle \cap \Q[x_1,x_2,x_3]$ where $z$ is a new variable
      \State \Comment{saturation of ideal by $h$}
      \State Let $S$ be a generator system for the ideal $I$
      \State $L \gets \{ {\textproc{sub}}_{\mathbf{b}}(f') \in \Q[x_3] \mid f' \in S \}$
      \State compute real roots $(c_1,\ldots,c_t)$ of $L$
      \State Let ${\cal R} := {\cal R} \cup \{ {\cal R}_{\mathbf{b}} = (c_1,\ldots,c_t) \}$
    \EndFor \Comment{possible $g \in \mathcal{A'}$}
  \EndIf
\EndFor \Comment{$(0,0)$-cells}
\State \Return $\cal R$.
\EndProcedure
\end{algorithmic}
:::

Compute the refinements, given by $\mathcal{R}$, of sections above bad cells using the method described in Section \@ref(sec:compute-refinement).

Let us demonstrate this procedure by applying it to the subset of the Whitney umbrella from Example
\@ref(exm:whitney-jhd).
Reecall that $W = \{ (x,y,z)\in \R^3 \mid 0 < x < 1, -x < y < x, x^2 z - y^2 = 0 \}$ is not a topologically regular
cell, but it can be refined into threee monotone cells as follows:
\begin{align*}
W_1 &:= \{ (x,y,z) \in \R^3 \mid 0 < x < 1, -x < y < 0, x^2 z - y^2 = 0 \},\\
W_2 &:= \{ (x,y,z) \in \R^3 \mid 0 < x < 1, y = 0, z = 0 \},\\
W_3 &:= \{ (x,y,z) \in \R^3 \mid 0 < x < 1, 0 < y < x, x^2 z - y^2 = 0 \}.
\end{align*}
Let $\mathcal{D}$ be a sign-invariant CAD of $\R^3$, compatible with $W_1$, $W_2$ and $W_3$. A possible set of
projection polynomials, $\mathcal{A} = (\mathcal{A}_1, \mathcal{A}_2, \mathcal{A}_3)$, for $\mathcal{D}$ is:
\begin{align*}
\mathcal{A}_1 &:= \{ f_{1,1} = x, f_{1,2} = x-1 \} \subset \Z[x],\\
\mathcal{A}_2 &:= \{ f_{2,1} = x+y, f_{2,2} = x-y, f_{2,3} = y \} \subset \Z[x,y],\\
\mathcal{A}_2 &:= \{ f_{3,1} = x^2 z - y^2 \} \subset \Z[x,y,z].
\end{align*}
These polynomials are sufficient to define the three cells $W_1$, $W_2$ and $W_3$, as well as the cells
\begin{align*}
C_{1,1} &= \{ 0 < x < 1, y = -x, f_{3,1} = 0 \},\\
C_{1,2} &= \{ x = 1, -1 < y < 0, f_{3,1} = 0 \},\\
C_{2,1} &= \{ 0 < x < 1, y = x, f_{3,1} = 0 \},\\
C_{2,2} &= \{ x = 1, 0 < y < 1, f_{3,1} = 0 \},\\
W_2 &= \{ 0 < x < 1, y = 0, f_{3,1} = 0 \},\\
\mathbf{a} &= (0,0,0), \mathbf{b} = (1,0,0), \mathbf{c} = (-1, 1, 1), \mathbf{d} = (1, 1, 1),
\end{align*}
which are contained in $\fr{W_1}$ and $\fr{W_3}$. The cell $C := \{ x = 0, y = 0, z > 0 \}$ also has non-empty
intersection with both $\fr{W_1}$ or $\fr{W_3}$. However, due to the blow-up of $f_{3,1}$ above the origin, $C$ is not
contained in the frontiers of $W_1$ and $W_3$.
Thus, $(0,0) \in \R^2$ is a bad cell in the decomposition induced by $\mathcal{D}$ on $\R^2$.
It will be identified by the check on line 9 of the pseudo-code because $f_{3,1}$ is identically zero on the
$(0,0,1)$-cell $C$.

Polynomials $g_1 \in \mathcal{A}_1$ and $g_2 \in \mathcal{A}_2$ (line 10) are identified as $g_1 = x$ and $g_2 = y$. The
algorithm then loops over each polynomial $g$ in $\mathcal{A}' := \mathcal{A}_1 \cup \mathcal{A}_2$. Then $h$ is set to
$g_1$ if $g$ depends on $y$ and to $g_2$ otherwise (lines 12-17).

The following polynomials $g$ and $h$ are considered, with ideal $I$ where $w$ is a new variable (line 18), generator system $S$ (line 20) and substituted set
of polynomials $L$ (line 21) computed as follows:

1. $g \gets x-1, h \gets y$:
    - $I := (f_{3,1}, x - 1, 1 - w y) \cap \Q[x,y,z]$,
    - $S := \{1\}$,
    - $L := \{0\}$ (no refinementns required);
2. $g \gets x+y, h \gets x$
    - $I := (f_{3,1}, x + y, 1 - w x) \cap \Q[x,y,z]$
    - $S := \{ z - 1,x + y \}$
    - $L := \{ z - 1 \}$;
3. $g \gets y+x, h \gets x$
    - $I := (f_{3,1}, x - y, 1 - w x) \cap \Q[x,y,z]$,
    - $S := \{ z - 1,x + y \}$.
    - $L := \{ z - 1 \}$.

The second and third sets of substituted polynomials both contain the same element, $z - 1$, which has a single real
root: $z=1$.
The algorithm will output the set of refinement points $\{ \mathcal{R}_(0,0) = \{ 1 \} \}$.
This refinement point splits the cell $C = \{ x =0, y = 0, z > 0 \}$ into three cells
\begin{align*}
C_1 &:= \{ x = 0, y = 0, 0 < z < 1 \}, \\
C_2 &:= \{ x = 0, y = 0, 1 < z \}, \\
\mathbf{a}' &:= (0,0,1).
\end{align*}

The cells $C_1$ and $\mathbf{a}'$ are contained in both $\fr{W_1}$ and $\fr{W_2}$ so that the frontiers of the
two-dimensional cells contained in the $W$ are now made up of cells of $\mathcal{D}$.

## Extension of Lazard { #sec:lazard-n }

Every $2$-dimensional cylindrical cell in a CAD of $\R^n$ is the graph of a continuous definable map $\mathbf{f} =
(f_1,\ldots,f_{n-2}) \colon X \to \R^{n-2}$ where $X \subset \opspan{x_i,x_j}, 1 \le i < j \le n$ is a cylindrical
$(1,1)$-cell by Proposition \@ref(prp:delete-zero-index) (@bgv13, Lemma 3.3). According to the remark following
Definition \@ref(def:blow-up-point), each component $f_j \colon X \to \opspan{x_j}$ of $\mathbf{f}$ is a continuous definable map at every point in $\cl{X}$ except, perhaps, for a finite set of isolated points in $\fr{X} = \cl{X} \setminus X$.
Therefore, it might be natural to ask whether the result from @lazard10 for lifting with bad points can be generalised to cylindrical decompositions of $\R^n, n > 3$ compatible with semialgebraic sets of dimension at most $2$.
Our goal is to construct a CAD $\mathcal{D}$ of $\R^n$, monotone with respect to each set $V_1, \ldots, V_k$ such that $\dim(V_i) \le 2$ for all $1 \le i \le k$, such that $\cl{C}$, for each cell $C \subset V_1 \cup \ldots \cup V_k$ of $\mathcal{D}$ is a union of some cells of $\mathcal{D}$.
Note that this method is not claimed to work for all cells of $\mathcal{D}$, in particular, those of dimension $> 2$.
However, this algorithm still has value in the context of this research, since it can be used to complete the
construction from @bgv15, Theorem 3.20 without needing to compute frontiers or apply the stratification algorithm.

In Section \@ref(sec:lazard-3), we applied Lazard's method for lifting with bad cells to CADs of $\R^3$ which are output from the algorithm described in Section \@ref(sec:monotone-algorithm). Lazard's algorithm required the input CAD to have two properties. First, each cell must be locally boundary connected. Since each cell $C \subset V = V_1\cup \ldots \cup V_k$ is constructed to be monotone, it is already topologically regular by Proposition \@ref(prp:monotone-topologically-regular) (@bgv13, Theorem 1), and is therefore already locally boundary connected.
The second requirement is that every cell must be well-bordered. While Proposition \@ref(prp:lazard-5-4) (@lazard10, Corollary 5.4) asserts that any sign-invariant CAD of $\R^3$ is well-bordered, this property cannot be extended to CADs of arbitrary dimension. Indeed, @lazard10, Example 2.11 describes a $3$-dimensional cylindrical cell in $\R^4$ which cannot be well-bordered since its frontier consists of a single half-line. This condition is necessary to get the configuration of cells described in Proposition \@ref(prp:lazard-5-13) (@lazard10, Lemma 5.13), which is required to apply the algorithm for lifting with bad points. Therefore, it seems unlikely that this method could be generalised to cells of dimension $> 2$.

::: {.definition #strong-about-c }
Let $\mathcal{D}$ be a CAD of $\R^n$ and $C$ be a cell of $\mathcal{D}$. $\mathcal{D}$ will be called strong about $C$
if $C$ is well-bordered, closuree finite and every cell contained in $\cl{C}$ is locally boundary connected.
:::

We first extend Proposition \@ref(prp:lazard-5-4) (@lazard10, Corollary 5.4) to cells of dimension $\le 2$ in a sign-invariant CAD of $\R^n$.
This can be done by extending @lazard10, Theorem 5.3.

::: {.proposition #lazard-5-3}
[@lazard10, Theorem 5.3]

Let $\mathcal{D}$ be an $\mathbf{F}$-invariant CAD of $\R^3$ such that the decomposition induced by $\mathcal{D}$ on $\R^2$ is strong. Then every cell $C$ of $\mathcal{D}$ is well-bordered.
:::

::: {.proof}
If $\dim(C) < 2$, then $C$ is well-bordered by @lazard10, Lemma 5.1.

If $\dim(C) = 2$ and $C$ is a $(1,1,0)$-cell, then its boundary consists of some section cells which project onto
$1$-dimensional cells in $\mathcal{D}'$ and which are contained in $\fr{C'}$ and points or intervals projecting onto some $0$-cells in $\fr{C'}$ by Proposition \@ref(prp:lazard-5-2) (@lazard10, Proposition 5.2).
We need to prove that these points belong to the boundary of some of the $1$-cells contained in $\fr{C}$.
Let $\mathbf{c}$ be a $0$-cell of $\mathcal{D'}$ contained in $\fr{C'}$ such that $\mathbf{c}$ is the projection of exactly one point, $\mathbf{p}$, in $\fr{C}$.
Since $C'$ is well-bordered (as $\mathcal{D'}$ is strong), there is a $1$-dimensional cell $C'_1 \subset \fr{C'}$ such that $\mathbf{c}$ is an endpoint.
If $C'_1$ is the projection of a $1$-dimensional cell contained in $\fr{C}$, we are done -- the boundary of this $1$-dimensional cell consists of some isolated points including $\mathbf{p}$.
If $C'_1$ is not the projection of a section cell, then the limits of the sequences of points in $C$, which project onto $C'_1$, tend to $-\infty$ or $\infty$. Therefore $\mathbf{p}$ is either $-\infty$ or $\infty$, being an endpoint
of the interval $I$ associated to $C$ by Proposition \@ref(prp:lazard-5-2) (@lazard10, Proposition 5.2). This
contradicts the assumption that $\projopinv{2}(\mathbf{c}) \cap \fr{C}$ contains only $\mathbf{p}$.

If $\dim(C) = 2$ and $C$ is a sector ($(i_1,i_2,1)$-cell), then $\fr{C}$ consists of the two $(i_1,i_2,0)$-cells $C_B$
and $C_T$ which project onto $C'$ the side-walls $W = \fr{C} \setminus (C_B \cup C_T)$ which consists of points or intervals projecting onto the endpoints of $C'$.
If $W$ contains an isolated point above an endpoint $\mathbf{c}$ of $C'$. Then Proposition \@ref(prp:lazard-5-2) (@lazard10, Proposition 5.2) asserts that it belongs to the boundary of a section bounding $C$ from below or above (i.e., $C_B$ or $C_T$), and we are done.

Finally, suppose that $C$ is a $(1,1,1)$-cell.
By the proof of @lazard10, Theorem 4.4, we only need to consider points in $\fr{C}$ which projects onto a bad cell, say $\mathbf{b}$, of $\mathcal{D'}$.
By @lazard10, Lemma 4.3 $\dim(\mathbf{b}) = 0$.
$C_B$ and $C_T$ are $(1,1,0)$-cells, therefore we only need to consider the blow-up subsets $B := (\fr{C} \setminus (\cl{C_B} \cup \cl{C_T})) \cap (\mathbf{b} \times \R)$. By Proposition \@ref(prp:lazard-5-2) (@lazard10, Proposition 5.2) $B$ is an open interval.
As $C'$ is well-bordered, there is a $1$-dimensional cell $C'_1 \subset \fr{C'}$ such that $\mathbf{b}$ is an endpoint.
The set of points of $\fr{C}$ which project onto $C'_1$ are bounded from below and above by points of $\fr{C_B}$ and $\fr{C_T}$, thus they are $1$-dimensional section cells. The boundaries of these section cells are included in $\fr{C_B}$ and $\fr{C_T}$.
Proposition \@ref(prp:lazard-5-2) (@lazard10, Proposition 5.2) implies that these sections which project onto $C'_1$ define a (finite and non empty) $2$-dimensional sector cell which projects onto $C'_1$ whose boundary
contains $B$.

As all cases have been considered, this completes the proof.
:::

::: {.corollary #ext-lazard-5-3 }
(Corollary to @lazard10, Theorem 5.3)

Let $\mathcal{D}$ be an $\mathbf{F}$-invariant CAD of $\R^n$ and $C$ be a cell of $\mathcal{D}$ of dimension $\le 2$ such that the decomposition induced by $\mathcal{D}$ on $\R^{n-1}$ is strong about $C' := \projop{n-1}(C)$. Then $C$ is well-bordered.
:::

::: {.proof}
If $\dim(C) < 2$, then $C$ is well-bordered by @lazard10, Lemma 5.1.

Since $\mathcal{D'}$ is strong about $C'$, Proposition \@ref(prp:lazard-5-2) (@lazard10, Proposition 5.2) can be
applied. Suppose that $\dim(C) = 2$ and $C$ is an $(i_1,\ldots,i_{n-1},1)$-cell. $C'$ is a $1$-dimensional $(i_1,\ldots,i_{n-1})$-cell whose endpoints are $(0,\ldots,0)$-cells of $\mathcal{D'}$.
If $C$ is bounded from below (resp. above), then $C_B$ (resp. $C_T$) is an $(i_1,\ldots,i_{n-1},0)$-cell and the points
or closed intervals associated with $C$ by Proposition \@ref(prp:lazard-5-2) (@lazard10, Proposition 5.2) are the
side-walls of $C$. Since $C_B$ and $C_T$ are $1$-dimensional cells of $\mathcal{D}$, they are well-bordered, and the points of $\fr{C}$ that do not belong to $\cl{C_B} \cup \cl{C_T}$ are $(0,\ldots,0,1)$-cells of $\mathcal{D}$. This proves that $C$ is not only well-bordered, but actually satisfies the frontier condition.

If $\dim(C) = 2$ and it is not a sector cell, it is an $(i_1,\ldots,i_{n-1},0)$-cell and $C'$ is a closure finite
$2$-dimensional $(i_1,\ldots,i_{n-1})$-cell of $\mathcal{D'}$.
In particular, $\fr{C'}$ is a union of $0$- and $1$-dimensional cells.
Let us consider the cylinder $C' \times \R$, which is a union of $2$- and $3$-dimensional cells of $\mathcal{D}$.

For the $2$-dimensional $(i_1,\ldots,i_{n-1},0)$-cell $C$, the same situation as in Proposition \@ref(prp:lazard-5-3)
(@lazard10, Theorem 5.3) occurs -- $\fr{C}$ consists of some $1$-dimensional $(j_1,\ldots,j_{n-1},0)$-cells of
$\mathcal{D}$ which project onto some $(j_1,\ldots,j_{n-1})$-cells of $\mathcal{D}'$ which are contained in $\fr{C'}$,
and some points and open intervals projecting onto some $(0,\ldots,0)$-cells contained in $\fr{C'}$.
We will prove in Lemma \@ref(lem:fr-lex-less) that $(j_1,\ldots,j_{n-1},0)$ is lexicographically less than
$(i_1,\ldots,i_{n-1},0)$. We actually prove that the frontier of a cell is always contained in cells of smaller binary index, even if the
cell is not closure finite.
The same argument as in Proposition \@ref(prp:lazard-5-3) (@lazard10, Theorem 5.3) can be applied to show that $C$ is
well-bordered. In particular, no points in $\fr{C}$ can be contained in a $(j_1,\ldots,j_{n-1},1)$-cell which projects onto
a $1$-dimensional sector cell in $\fr{C'}$.
Since $C$ is $2$-dimensional, a $2$-dimensional cell cannot be part of $\fr{C}$. If such a cell, projecting on a $1$-dimensional cell in $\mathcal{D}'$ exists, then $C$ approaches $-\infty$ and $\infty$ as it approaches this cell.

The $(i_1,\ldots,i_{n-1},1)$-cells of $\mathcal{D}$ contained in $C' \times \R$ also have the same arrangement as $(1,1,1)$ cells in from Proposition \@ref(prp:lazard-5-3) (@lazard10, Theorem 5.3). Being careful to take blow-up points into account, the same argument as in the proof of Proposition \@ref(prp:lazard-5-3) (@lazard10, Theorem 5.3) shows that these cells are also well-bordered.
:::

By Proposition \@ref(prp:no-blow-up), if no cells which intersect $\fr{C}$ project onto a bad cell and the induced decomposition is strong, $C$ is well-bordered, locally boundary connected and satisfies the frontier condition. Since the proof of Proposition \@ref(prp:no-blow-up) only considers cells contained in $\projop{n-1}(\cl{C}) \times \R$ this property is also true for the weaker condition that the induced decomposition is strong about $\projop{n-1}(C)$.
Thus, we need to look at what happens in the neighbourhood of bad cells (blow-up points) only.
If there is a blow-up point, then we claim that the following situation, similar to that described in Proposition \@ref(prp:lazard-5-13) (@lazard10, Lemma 5.13), occurs.

::: {.lemma #ext-lazard-5-13 }
(Extension of Proposition \@ref(prp:lazard-5-13) [@lazard10, Proposition 5.13])

Let $\mathcal{D}$ be a sign-invariant decomposition of $\R^n$ and $C$ be a cell of $\mathcal{D}$ of dimension at most
$2$, such that the decomposition induced by $\mathcal{D}$ on $\R^{n-1}$ is strong about $\projop{n-1}(C)$. Let $D$ be a cell of $\mathcal{D}$ such that $B := D \cap \fr{ C } \neq \emptyset$ and $B \neq D$. Then either

  1. $C$ is a $1$-dimensional section cell whose endpoint, $B$, projects onto a bad cell, or

  2. there exists a cell $E$ of $\mathcal{D}$ such that $\dim(E) < \dim(C)$ and $\emptyset \neq D \cap \fr{ E } \neq D$.
:::

::: {.proof}
By the proof of [@lazard10, Theorem 4.4], $D$ will always be a $(0,\ldots,0,1)$-cell in the cylinder above a bad cell $D'$.

We consider each case by the cell's binary index.

- $(i_1,\ldots,i_{n-1},1)$-cell, where $\sum_{j=1}^{n-1} i_j = 1$: observe that $C$ (if bounded) is delineated by some
  $(i_1,\ldots,i_{n-1},0)$-cells ($1$-dimensional curve intervals). Take $B$ to be the $1$-dimensional interval delineated by the endpoints of these curves. Since $B \neq C$, at least one of these endpoints is not a $(0,\ldots,0,0)$-cell of $\cal D$. Case 2 applies, taking as $E$ the delineating $(i_1,\ldots,i_{n-1},0)$-cell.

- $(i_1,\ldots,i_{n-1},0)$-cells, where $\sum_{j=1}^{n-1} i_j = 1$: consider the previous case, letting $C = E$.

- $(i_1,\ldots,i_{n-1},0)$-cell, where $\sum_{j=1}^{n-1} i_j = 2$:
$C$ is necessarily the root of a polynomial $f \in \Q[x_1,\ldots,x_n]$ which vanishes identically on $D'$, a $(0,\ldots,0)$ cell in the decomposition induced by $\cal D$ on $\R^{n-1}$.
Let $V_r$ be a small neighbourhood (with radius $r > 0$) centred around $D'$ and consider $V_r'$, the cylinder above the boundary of $V_r$. Since $C$ is a monotone cell, the maximum and minimum values of $x_n$ in this intersection are obtained on the boundary of $C$, for sufficiently small $r$. The limits, as $r$ tends to $0$, of this maximum and minimum clearly belong to the boundary of $B$, if these limits are finite. Note that both the maximum and minimum cannot be infinite, since this would imply that either $B$ is empty, or coincides with $D$. Therefore, the non-infinite limits are the endpoints of some $1$-dimensional cell belonging to the boundary of $C$. Case 2 applies, taking $E$ to be this $1$-dimensional cell.

- $(0,\ldots,0,1)$- or $(0,\ldots,0,0)$-cells: do not satisfy the hypothesis, there is nothing to do.
:::

::: {.remark}
Let $C$ be an $(i_1,\ldots,i_{n-1},0)$-cell of a CAD $\mathcal{D}$ of $\R^n$ as described in Lemma \@ref(lem:ext-lazard-5-13) such that $i_1=i_k = 1$ for
some $1 < k < n$ while all other elements of the binary index are equal to $0$.
Suppose that the decomposition induced by $\mathcal{D}$ on $\R^{n-1}$ is strong about $\projops{n-1}(C)$.
The cell $D$, which projects onto a bad cell is necessarily a $(0,\ldots,0,1)$-cell and the cell $E$, which has dimension
$1$, is contained in $\cl{C}$. Hence, $E$ must have binary index either $(i_1 = 1,0,\ldots,0)$ or $(0,\ldots,0,i_k = 1,0,\ldots,0)$.
By Proposition \@ref(prp:delete-zero-index) [@bgv15, Lemma 3.3], the images of $C$, $D$ and $E$ under the projection map
$\projops{i_1,i_k,i_n}$ are cylindrical cells and satisfy Proposition \@ref(prp:lazard-5-13) [@lazard10, Lemma 5.13] in
$\R^3$. Furthermore, $C$ can be viewed as a cell in a sub-CAD above a $0$-dimensional cell. Hence, this method can be
applied to $(i_1,\ldots,i_{n-1},0)$-cells, where $1 \le i_{\ell_1} < i_{\ell_2} < n$ are equal to $1$ and all other
elements are equal to $0$.
:::

Note that Lazard's method for cylindrical decomposition of $\R^3$ relies on blow-ups in the frontier of $\projop{2}(C)$ having dimension at most $0$.
This is always true in $\R^3$.
However, in dimension greater than $3$, blow-ups of dimension greater than $0$ are possible.
This may occur in a $1$-dimensional cell $D'$ which is part of $\fr{\projop{n-1}(C)}$.
In this case, as described in Corollary \@ref(cor:ext-lazard-5-3), $C$ tends to $-\infty$
or $\infty$ as it approaches $D' \times \R$.

This implies that we should be able to use a similar technique to that described in Proposition \@ref(prp:lazard-5-14)
(@lazard10, Proposition 5.14) to lift above bad cells and satisfy the frontier condition on $2$-dimensional section cells in decompositions of arbitrary dimension.

Let us begin weth the situation described in Proposition \@ref(prp:lazard-5-14) to see how it can be extended.
Let $f \in \Q[x_{\ell_1},x_{\ell_2},x_n]$ be an irreducible polynomial and $\mathbf{p} \in \opspan{x_{\ell_1},
x_{\ell_2}}$ be a common root of the coefficients of $f$. Let $g \in \Q[x_{\ell_1}, x_{\ell_2}]$ be an irreducible
polynomial having $\mathbf{p}$ as a root.
Then Proposition \@ref(prp:lazard-5-14) asserts that there exists a polynomial $h \in \Q[x_{\ell_1}, x_{\ell_2}]$ such
that the zero set of the saturation of the ideal $\langle f,g \rangle$ by $h$ defines the limit points of $f$ and $g$ as
$(x_{\ell_1}, x_{\ell_2})$ approaches $\mathbf{p}$.

Consider the projection $D'$ onto $\opspan{x_{\ell_1}, x_{\ell_2} x_n}$ of a $1$-dimensional section cell $D$ (see case (1) of Lemma
\@ref(lem:ext-lazard-5-13)), which is part of the frontier of a $2$-dimensional section cell.
Since $D$ is a $(0,\ldots,0,i_{\ell_1} = 1, 0, \ldots, 0, i_{\ell_2} = 1, 0 \ldots, 0)$-cell, Proposition
\@ref(prp:delete-zero-index) [@bgv13, Lemma 3.3] states that $D$ is the graph of a continuous definable map
from $D' \subset \opspan{x_{\ell_1}, x_{\ell_2}}$ to $\opspan{x_1,\ldots,x_{\ell_1 - 1}, x_{\ell_1 + 1}, \ldots, x_{\ell_2 - 1}, x_{\ell_2 + 1}, \ldots, x_n}$.
The potential blow-up subset, contained in $\mathbf{p} \times \opspan{x_n}$, which is the projection of the line
$\mathbf{b} \times \R$, where $\mathbf{b}$ is a bad cell in $\R^{n-1}$, also satisfies this property.
Therefore, we can define, in $\R^n$, an algebraic set $\{ f = 0, g = 0, g_{j_1} = 0, \ldots, g_{j_{n-3}} = 0\} \supset D$, which
has dimension $1$ at every point in $D$, such that $\mathbf{b}$ is a common root of the polynomials
$g, g_{j_1}, \ldots, g_{j_{n-3}}$ and the coefficients of $f$.
We need to find a polynomial $h \in \Q[x_1,\ldots,x_{n-1}]$ such that the saturation $$
S := \langle f, g, g_{j_1}, \ldots, g_{j_{n-3}}, 1 - z h \rangle \cap \Q[x_1,\ldots,x_n]
$$
defines the required refinement point.
As before, $h$ can be taken to be a coefficient of $f$ which is not a multiple of any of $g, g_{j_1}, \ldots,
g_{j_{n-3}}$. This leads to the following conjecture:

::: {.conjecture #ext-lazard-5-14}
(Extension of @lazard10, Proposition 5.14)

Let $f \in \Q[x_1,\ldots,x_n]$ and $g_{j_1},\ldots,g_{j_{n-3}} \in \Q[x_1,\ldots,x_{n-1}]$ be a set of irreducible
polynomials which define an algebraic set of dimension $2$ in every point of the neighbourhood of a point $\mathbf{p}\in
\R^{n-1}$ (except, perhaps, for $\mathbf{p}$ itself, where $f$ may blow up). Suppose that $\mathbf{p}$ is a common root of $g_{j_1},\ldots,g_{j_{n-3}}$ and
the coefficients of $f$.
Let $g\in \Q[x_1,\ldots,x_{n-1}]$ be an irreducible polynomial which is algebraically independent of all of $f, g_{j_1},
\ldots, g_{j_{n-3}}$.
Then there exists a polynomial $h \in \Q[x_1,\ldots,x_{n-1}]$ such that the limit of the common
roots of $f, g, g_{j_1}, \ldots, g_{j_{n-3}}$ as $(x_1,\ldots,x_{n-1})$ approaches $\mathbf{p}$ can be computed as the
zero set of the saturation of the ideal $\langle f, g, g_{i_1}, \ldots, g_{i_{n-3}} \rangle$ by $h$.
:::

We now describe how this result can be applied.
Let $\mathcal{D}$ be an $\mathbf{F}$-invariant CAD of $\R^n$ as constructed by the algorithm in Section \@ref(sec:monotone-algorithm).
Recall that, for the previous results, we require the decomposition induced on $\R^{n-1}$ to be strong about the
projections of some cells of $\mathcal{D}$. Therefore, we need to proceed by induction on decompositions induced by
$\mathcal{D}$ on $\R^k, k \ge 1$ to be able to apply Lemma \@ref(lem:ext-lazard-5-13) and Conjecture \@ref(cnj:ext-lazard-5-14).

For $k\le 2$, we have a $\projop{k}(\mathbf{F})$-invariant CAD which already satisfies the frontier condition by @lazard10, Corollary 4.7.
For $k=3$, recall that every cell is well-bordered by Proposition \@ref(prp:lazard-5-4) (@lazard10, Corollary 5.4). We
already described how to construct a $\projop{3}(\mathbf{F})$-invariant CAD of $\R^3$ satisfying the frontier condition
using @lazard10, Algorithm 5.15 in Section \@ref(sec:lazard-algorithm).

For $k>3$ let $\mathcal{D'}$ be the decomposition induced by $\mathcal{D}$ on $\R^k$ and let $C$ be a cell of
$\mathcal{D'}$ such that $\projopinv{k}(C) \subset V_1 \cup \ldots \cup V_k$.
By the induction hypothesis, the decomposition induced by $\mathcal{D'}$ on $\R^{k-1}$ is strong about $\projop{k-1}(C)$.
The cell $C$ is topologically regular since the projection of a monotone cell is monotone and $C$ is well-bordered by Corollary \@ref(cor:ext-lazard-5-3) since $\dim(C) \le 2$.
If $\dim(C) < 2$, $C$ already satisfies the frontier condition since it is well-bordered.
If $\dim(C') = 2$, then $C$ is an $(i_1,\ldots,i_k)$-cell such that $i_{\ell_1} = i_{\ell_2} = 1$, for some
$1 \le i_{\ell_1} < i_{\ell_2} \le n$,
and all other elements
of the binary index are equal to zero.

First suppose that $\ell_1 = 1$. If $\ell_2 < k$ then $C$ is a section cell.
Let $C' = \projop{k-1}(C)$. $C'$ satisfies the frontier condition by the induction hypothesis and $C$ is the graph of a
continuous definable function $\varphi \colon C' \to \R$.
$\cl{C}$ is the graph of $\varphi$ for all but, possibly, a finite number of isolated blow-up points in $\cl{C'}$ (see Remark after Definition \@ref(def:blow-up-point)).
Let $\mathcal{A}_1,\ldots,\mathcal{A}_k$ be the set of projection polynomials defining $\mathcal{D'}$. By the
construction of CAD, these polynomials are irreducible and since $C$ is part of a smooth stratum of dimension $2$, it is
effectively nonsingular. Let
$$
C \subset \{ \mathbf{x} \in \R^k \mid g_{j_1}(\mathbf{x}) = 0, \ldots, g_{j_{k-3}}(\mathbf{x}) = 0, f(\mathbf{x}) = 0 \}
$$
where each $g_i \in \mathcal{A}_i$ for $i \in \{j_1,\ldots,j_{k-3}\} = \{1,\ldots,k-1\} \setminus \{{\ell_1}, {\ell_2} \}$ and $f \in \mathcal{A}_k$.
Since $C$ is effectively nonsingular, these polynomials are algebraically independent and therefore they define an
algebraic set of dimension $2$ at every point in $C$.
Suppose that there is a $(0,\ldots,0,1)$-cell $D$ such that $D \cap \fr{C}$ and $f(\mathbf{x}) = 0$ for all $\mathbf{x} \in D$. I.e., $\mathbf{b} := \projop{k-1}(D)$ is a bad cell and is a common root of $g_{j_1}, \ldots, g_{j_{k-3}}$ and some $g_{\ell_1} \in \mathcal{A}_{\ell_1}, g_{\ell_2} \in \mathcal{A}_{\ell_2}$.
Apply a method similar to that described in @lazard10, Algorithm 5.15 to $C$ and $D$ -- using Conjecture
\@ref(cnj:ext-lazard-5-14), compute the saturations by $g_{\ell_1}$ and $g_{\ell_2}$, respectively as follows:
\begin{equation}
I_1 := \langle f, g_{j_1}, \ldots, g_{j_{k-3}}, g_{\ell_2}, 1 - z g_{\ell_1} \rangle \cap \Z[x_1,\ldots,x_k]
(\#eq:lazard-n-1)
\end{equation}
and
\begin{equation}
I_2 := \langle f, g_{j_1}, \ldots, g_{j_{k-3}}, g_{\ell_1}, 1 - z g_{\ell_2} \rangle \cap \Z[x_1,\ldots,x_k],
(\#eq:lazard-n-2)
\end{equation}
where $z$ is a new variable.
Let $S_1, S_2$ be generator systems, e.g., Groebner bases, for $I_1,I_2$ respectively. The union of $0$-dimensional solutions to $S_1,S_2$ forms the set of refinement points $\mathcal{R}_\mathbf{b}$ which contains the endpoints of the open interval $D \cap \fr{C}$, By considering each bad cell in $\fr{\projop{k-1}(C)}$, $\mathcal{D}'$ can be refined such that $C$ satisfies the frontier condition.

On the other hand, if $\ell_1 = 1$ and $\ell_2 = k$, then $C$ is a sector cell. In this case, $C$ already satisfies the frontier condition
since its top and bottom, which are $1$-dimensional section cells, already satisfy the frontier condition and its
side-walls consist of at most two connected components -- points or closed intervals, whose endpoints coincide with the endpoints of the top and bottom of $C$.

Finaly, if $\ell_1 > 1$ then $C$ is a $(0,\ldots,0,i_{\ell_1},\ldots,i_k)$-cell. Apply the method described above to the
$(i_{\ell_1},\ldots,i_k)$-cell in the sub-CAD above $\projop{i_\ell - 1}(C)$.

Compute a refinement of $\mathcal{D}$ so that it is compatible with the set of refinement points $\mathcal{R}_\mathbf{b}$. These are refinements of the kind described in @bgv15, Lemma 3.11, and preserve the cylindrical structure and monotone cells in $\mathcal{D}$.
By repeating this process for each bad cell $\mathbf{b}$, $\mathcal{D'}$ is refined such that it satisfies the frontier
condition, hence it is strong about each cell $C$ such that $\projopinv{k}(C) \subset V_1\cup \ldots \cup V_k$. This completes the inductive step and, by induction, a cylindrical decomposition monotone with respect to each set $V_1,\ldots,V_k$ and satisfying the frontier condition has been constructed.

### Pseudo-code { #sec:ext-lazard-algorithm }

Let $\cal D$ be an $\mathbf{F}$-invariant cylindrical algebraic decomposition of $\R^n$ monotone with respect to each of
the bounded semialgebraic sets $V_1,\ldots, V_q$ such that $\dim(V_i) \le 2, 1,\le i \le q$ (e.g., the output produced by the algorithm from Section \@ref(sec:monotone-algorithm)).
We now extend @lazard10, Algorithm 5.15 to CAD of this kind.
First, prepare $\mathcal{D}$ by marking each cell $C' := \projop{r}(C)$, such that $C'$ is a $2$-dimensional section cell in the decomposition induced by $\mathcal{D}$ on $\R^r$ such that $C$ is a cell of $\mathcal{D}$ contained in $V_1,\ldots,V_k$ for $3 \le r \le n$.

::: {.algorithm data-latex="Extension of Lazard's Lifting With Bad Points, for $2$-dimensional cells in $\R^n$"}
[Extension of @lazard10, Algorithm 5.15]

$$\mathcal{R} := \textproc{LazardLift}({\cal D}, {\cal A})$$
**Input:**

  - $\cal D$: a CAD of $\R^k$, each cell having constant sign on $\mathcal{A}$.
A collection of cells $\mathcal{C} := \{ C_1,\ldots,C_m \}$ of $\mathcal{D}$ are marked as being projections of $V_1,\ldots,V_q$, a family of sets having $\dim(V_i) \le 2, 1 \le i \le q$.

  - ${\cal A} = {\cal A}_1,\ldots,{\cal A}_k$ is the family of projection polynomials for $\mathcal{D}$, each ${\cal A}_i \subset \Z[x_1,\ldots,x_i]$.

**Output:**
$$
{\cal R} := \{ {\cal R}_{\mathbf{b}} = \{ c_1,\ldots,c_t \} \subset \A \}
$$
where $\mathbf{b} \in \R^{k-1}$ is a $(0,\ldots,0)$-cell in the decomposition induced by ${\cal E}$ on $\R^k$.
A set of refinement points, as described in Section \@ref(sec:monotone-algorithm).

\begin{algorithmic}[1]
\Procedure{LazardLift}{$\mathcal{A}, \mathcal{D}$}
\State ${\cal R} \gets \emptyset$
\State Let $\cal D'$ be the decomposition induced by $\cal D$ on $\R^{k-1}$

\For{each $(i_1,\ldots,i_{k-1},0)$-cell $E$ in $\cal C$}
  \State \Comment{such that $i_{\ell_1} = i_{\ell_2} = 1$, all other elements $= 0$}
  \State $\mathbf{c} \gets \projop{\ell_1 - 1}(E)$
  \State $\mathcal{A'}_{j + \ell_1 - 1} := \{ {\textproc{sub}}_{\mathbf{c}} (f) \in \Z[x_{\ell_1},\ldots,x_j] \mid f \in \mathcal{A}_{j} \}$
  \State \Comment{set of polynomilas defining the sub-CAD above $\mathbf{c}$}
  \State $\{h_{\ell_1 + 1},\ldots,h_{\ell_2 - 1}, h_{\ell_2 + 1}, \ldots h_k\} :=
  \textproc{DefiningPolynomials}(C,\mathcal{A})$
  \State \Comment{algebraically independent defining polynomials for $C$}
  \State \Comment{determine whether it is a bad cell}
  \For {$\mathbf{b} \in \fr{\projop{k-1}(C)}, \dim(\mathbf{b}) = 0$}
  \If {$\textproc{IsBad}(\mathcal{D},\mathbf{b})$}
    \State $\mathcal{R}_{\mathbf{b}} \gets \emptyset$
    \State $g_{\ell_1} \in {\cal A}_{\ell_1}, g_{\ell_2} \in {\cal A}_{\ell_2}$ such that $g_{\ell_1}(\mathbf{b}) = 0$
    and $g_{\ell_2}(\mathbf{b}) = 0$
    \For {each $f_{\ell_1} \in \mathcal{A}_{\ell_1},f_{\ell_2} \in \mathcal{A}_{\ell_2}$}
      \State \Comment{compute saturations}
      \State $I_1 \gets \langle h_k,\ldots,h_{\ell_2 + 1}, g_{\ell_2}, h_{\ell_2 - 1}, \ldots, h_{\ell_1 + 1}, 1 - z f_{\ell_1} \rangle \cap \Z[x_1,\ldots,x_k]$
      \State $I_2 \gets \langle h_k,\ldots,h_{\ell_2 + 1}, h_{\ell_2 - 1}, \ldots, h_{\ell_1 + 1}, g_{\ell_1}, 1 - z f_{\ell_2} \rangle \cap \Z[x_1,\ldots,x_k]$
      \State \Comment{where $z$ is a new variable}
      \State \Comment{saturation of ideal by $h$}
      \State Let $S_1, S_2$ be generator systems for the ideals $I_1$ and $I_2$
      \State $L \gets \{ {\textproc{sub}}_{\mathbf{b}}(f') \in \Q[x_k] \mid f' \in S_1 \cup S_2 \}$
      \State compute real roots $(c_1,\ldots,c_t)$ of $L$
      \State Let ${\cal R}_{\mathbf{b}} := {\cal R}_{\mathbf{b}} \cup \{ c_1,\ldots,c_t \}$
    \EndFor
    \State \Comment{append refinement points for $\mathbf{b}$}
    \State \Comment{it will be helpful to sort them in ascending order}
    \State Let ${\cal R} := {\cal R} \cup \{ {\cal R}_{\mathbf{b}} = (c_1,\ldots,c_r) \}$
  \EndIf
  \EndFor
\EndFor \Comment{$(0,0)$-cells}
\State \Return $\cal R$.
\EndProcedure
\end{algorithmic}
:::

Apply this procedure to each decomposition, for $3 \le k \le n$ induced by $\mathcal{D}$ on $\R^k$ and compute the refinement of sections above bad cells using the same method described in Section \@ref(sec:compute-refinement) to obtain a refinement $\mathcal{E}$ of $\mathcal{D}$. Note that, since refinement points are algebraic numbers splitting $(1)$-cells in induced decompositions, @bgv15, Lemma 3.11 asserts that the cylindrical structure and monotone cells are preserved in $\mathcal{E}$.

### Correctness

Since zero- and $1$-dimensional cells already satisfy the frontier condition, it suffices to consider cells of dimension
$2$.
Let $\mathcal{D}$ be a CAD of $\R^k$ and $C$ be a $2$-dimensional section cell of $\mathcal{D}$ such that the
decomposition induced by $\mathcal{D}$ on $\R^{k-1}$ is strong about $C$. Corollary \@ref(cor:ext-lazard-5-3) asserts
that $C$ is well-bordered, so its frontier consists of the closure of some $1$-dimensional cells of $\mathcal{D}$. The frontier condition fails in the region of sector cells of $\mathcal{D}$ above $0$-dimensional bad cells in the decomposition induced by $\mathcal{D}$ on $\R^{k-1}$.
The procedure described above explains how to obtain some new polynomials which allow these $1$-dimensional sectors to be refined such that they are compatible with the frontier of $C$. By performing this refinement, $C$ is made to satisfy the frontier condition.

If $C$ is a $2$-dimensional sector cell, then its top and bottom are $1$-dimensional sector cells of $\mathcal{D}$ and
the side-walls of $C$ is contained in cylinders $\mathbf{c} \times \R$, where $\mathbf{c}$ is a $0$-dimensional cell
which is an endpoint of $\projop{k-1}(C)$. It follows that $C$ satisfies the frontier condition since its top and
bottom, which are $1$-dimensional cells, satisfy the frontier condition.

### Complexity

We will see, in Section \@ref(sec:novel-frontier), that there is an algorithm for obtaining the frontier condition on a
CAD compatible with a semialgebraic set of arbitrary dimension. This algorithm has complexity $(sd)^{\O(1)^{n2^n}}$ --
triply exponential in the number of variables. However, in the particular case of semialgebraic sets having dimension at
most $2$, the complexity may be lower. This is now discussed.

Let us first discuss complexity in relation to the procedure described by @bgv15 in Theorem 3.20. Given the family $V_1,\ldots,V_k$, $\fr{C}$ is computed for each $2$-dimensional cell $C \subset V_1\cup \ldots \cup V_k$. According to Lemma \@ref(lem:frontier), there is an algorithm, which uses @bpr2006 Algorithm 14.21 as its main subroutine, for computing $\fr{C}$, having complexity $$
(sd)^{\O(n^2)},
$$
where $C$ is defined by $s$ different polynomials of maximum degree $d$.
$C$ has constant sign on all polynomials defining the CAD, so, using the bounds discussed in Sections \@ref(sec:quasi-complexity) and \@ref(sec:monotone-complexity), the complexity upper bound for computing $\fr{C}$ is
$$
\left(\left(s(d+1)\right)^{\O(1)^{n}}\cdot\left(s(d+1)\right)^{\O(1)^{n}}\right)^{\O(n^2)},
$$
which is asymptotically the same as
$$
(s(d+1))^{\O(1)^{n}}.
$$
Note that, in some cases, only some of the $\left(s(d+1)\right)^{\O(1)^{n}}$ polynomials are required to define the cell $C$.
This is, according to Lemma \@ref(lem:frontier), an upper bound on the number of polynomials and their degrees in the QFF defining $\fr{C}$.
The procedure requires us to partition $\fr{C}$ into points and monotone curve intervals.
In order to do this, a similar process  that used to obtain monotone cells (see Section \@ref(sec:monotone-cells)) can be used. This will be repeated for each of the $2$-dimensional cells contained in $V_1\cup \ldots \cup V_k$. As such, the overall complexity will be the same as that presented in Section \@ref(sec:monotone-complexity). I.e.,
$$
(s(d+1))^{\O(1)^{n}}.
$$

Now let us consider the extension of @lazard10, discussed in Section \@ref(sec:lazard-n).
For each $1$-dimensional sector cell which projects onto a $0$-dimensional bad cell, the saturation of ideals, defined in Equations \@ref(eq:lazard-n-1) and \@ref(eq:lazard-n-2) are computed. There will be at most $n$ polynomials, in $n+1$ variables, appearing in these ideals. The saturation of these ideals is computed by finding a Groebner basis for them.
According to @lakshman1991, if the ideal $I = \langle f_1,\ldots,f_k\rangle$ where $f_1,\ldots,f_k$ are polynomials in $n$ variables, then a Groebner basis for $I$ can be computed in time singly exponential in $n$.
However, in our case, only the saturation of the ideal over the real numbers is $0$-dimensional, rather than the
original ideal over complex numbers before eliminating the new variable $z$. Therefore, the complexity of computing a
Groebner basis is doubly exponential in the number of variables -- $2^{2^n}$ [@mayr1997]. In the worst case, we may be considering a $(1,1,0,\ldots,0)$-cell, part of whose frontier projects onto a bad $(0,0)$-cell in the induced decomposition of $\R^2$. It follows that at most $n-2$ Groebner basis computations will be required. Thus, the total complexity for lifting above a bad cell is at most $n \cdot 2^{2^n}$, which is asymptotically the same as $2^{n 2^n}$.
The bound on the number of bad cells is unknown, but it is obviously bounded from above by the total number of cells in
the induced decomposition of $\R^{n-1}$. I.e., $(s(d+1))^{\O(1)^{n-1}}$.
It follows that the complexity of the algorithm arising from the generalisation of Lazard is
$$
(s(d+1))^{\O(1)^{n-1}} \cdot 2^{n 2^n},
$$
which is bounded from above by
$$
(s(d+1))^{\O(1)^{n}}.
$$

Both approaches -- @bgv15 and the generalisation of @lazard10 -- have the same complexity upper bound.
In addition, it is conjectured that both approaches will produce the same set of refinement points. This is because, in
a sign-invariant, monotone CAD, the two-dimensional cells contained in $V$ will be well-bordered. Therefore, the
algorithm following @bgv15, Theorem 3.20 will only have to refine sectors above $0$-dimensional bad cells.
However, the CAD constructed in Chapter \@ref(sec:quasi-affine) only has to be sign-invariant so that Lazard's method
can be applied. Therefore, if an efficient method for computing the frontiers of $2$-dimensional cells and refining them
into points and effectively nonsingular, monotone curve intervals, the requirement for a sign-invariant CAD can be
dropped and the approach following @bgv15 can be used. This will not reduce the overall asymptotic complexity of the
algorithm, but it is likely to produce a CAD with fewer cells.

## Completing the construction

To summarise, each of the three stages -- quasi-affine, monotone and frontier condition -- of the algorithm for
computing a CAD which is monotone with respect to all $V_1,\ldots,V_k$, such that $\dim(V_i) \le 2$ for all $1 \le i \le
k$, and satisfying the frontier condition each has complexity $(s(d+1))^{\O(1)^{n}}$.
Thus, the overall complexity of this algorithm is
$$
(s(d+1))^{\O(1)^{n}}.
$$
By Proposition \@ref(prp:collins), this is also an upper bound on the number of cells, number of polynomials and their degrees defining this CAD.

Recall that the complexity of computing a
classical CAD (from Proposition \@ref(prp:collins)) is $$
(sd)^{\O(1)^n}.
$$
Therefore, the monotone CAD algorithm has, as expected, a slightly higher complexity than that of the classical algorithm.
However, the complexity is not significantly worse, still being doubly exponential in the number of variables.

Overall we have proved the following

::: { .theorem #bgv-algorithm }
Let
$$
F_1,\ldots,F_k
$$
be quantifier-free Boolean formulas containing $s$ different polynomials $\mathbf{F} = \{ f_1,\ldots, f_s \} \in \Z[x_1,\ldots,x_n]$, having maximum degree $d$, such that $F_i, 1\le i \le k$ defines a bounded semialgebraic set $V_i \subset \R^n$ such that $\dim(V_i) \le 2$.

Then there is an algorithm, taking $F_1,\ldots,F_k$ as input, which constructs a cylindrical algebraic decomposition $\mathcal{D}$ of $\R^n$ satisfying the frontier condition, and monotone with respect to each $V_1, \ldots, V_k$.
This algorithm has complexity
$$
\left(s\left(d+1\right)\right)^{\O(1)^n},
$$
which is also an upper bound on the number of cells in the CAD, number of polynomials and their degrees.
:::


